Repository the-events-calendar/event-tickets, pull requests merged in 2018-03, with the labels that each got.

#667 Fix auto-return issues
  src/Tribe/Commerce/PayPal/Endpoints.php
  src/Tribe/Commerce/PayPal/Errors.php
  src/Tribe/Commerce/PayPal/Frontend/Tickets_Form.php
  src/Tribe/Commerce/PayPal/Gateway.php
  src/Tribe/Tickets.php
  src/admin-views/tribe-options-tickets.php
Labels: code review, merge

#675 Fix back-compat with out of date ET+ plugin
  composer.json
  composer.lock
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
Labels: merge

#674 Restore RSVP email functionality
  src/Tribe/RSVP.php
Labels: merge

#676 bump version to `4.7`
  src/views/login-before-purchase.php
  src/views/login-to-purchase.php
  src/views/tickets/orders-pp-tickets.php
  src/views/tickets/orders.php
  src/views/tickets/rsvp.php
  src/views/tickets/tpp-success.php
  src/views/tickets/tpp.php
Labels: merge

#677 Add dynamic parents when a venue or organizer has tickets
  readme.txt
  src/Tribe/Attendees.php
Labels: merge

#680 Fix/84675 updater class
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Updater.php
Labels: code review, merge

#681 Fix missing EDD attendee meta issue
  src/views/tickets/email.php
Labels: merge

#682 Support attendee list display optout option
  src/Tribe/Commerce/PayPal/Main.php
  src/views/tickets/tpp.php
Labels: merge

#683 Fix/91471 stock manage warning
  readme.txt
  src/admin-views/editor/list-row.php
Labels: merge

#679 Make sure slug for tickets are consistent
  readme.txt
  src/views/tickets/orders-link.php
Labels: merge

#684 Fix/95098 base panel warnings
  readme.txt
  src/resources/js/tickets.js
  src/resources/js/tickets.min.js
Labels: merge

#689 Expanded the correct parent when visiting the list of attendees
  readme.txt
  src/Tribe/Attendees.php
Labels: merge

#673 Count ticketd / unticketd events that are in trash
  readme.txt
  src/Tribe/Cache/Abstract_Cache.php
  src/Tribe/Cache/Central.php
  src/Tribe/Cache/Transient_Cache.php
Labels: merge

#691 Make sure to send the context to the email template
  readme.txt
  src/Tribe/Attendees.php
Labels: merge

#693 Prevent tests from failing
  composer.json
  composer.lock
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/RSVP.php
  src/Tribe/Tickets_Handler.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Tickets/CSV_Importer/RSVP_ImporterTest.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Frontend/Tickets_FormTest.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Frontend/__snapshots__/Tickets_FormTest__test_render_snapshot_with_available_tickets__1.php
Labels: merge

#685 Fix/100165 rsvp change status capacity
  readme.txt
  src/Tribe/RSVP.php
  src/Tribe/Tickets_View.php
Labels: code review, merge

#670 Populate RSV form if user is already logged in
  readme.txt
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
  src/views/tickets/rsvp.php
Labels: code review, merge

#671 Make sure the description of an RSVP is sanitized correctly
  readme.txt
Labels: code review, merge

#696 Allow to set the number of stock for an RSVP on tests
  src/Tribe/RSVP.php
  src/Tribe/Tickets_Handler.php
  tests/wpunit/Tribe/Tickets/RSVPTest.php
Labels: merge

#698 Regenerate the assets to avoid merge conflicts
  src/resources/css/accordion.css
  src/resources/css/accordion.min.css
  src/resources/css/rsvp.css
  src/resources/css/rsvp.min.css
  src/resources/css/tickets-refresh.css
  src/resources/css/tickets-refresh.min.css
  src/resources/js/tickets.min.js
Labels: merge

#695 Add query params as input values to the form
  readme.txt
  src/template-tags/tickets.php
Labels: code review, merge

#700 Make it easier to set Tribe Commerce as default module
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Tickets.php
Labels: merge

#699 Prevent to overwrite the start date of a ticket if was already set
  readme.txt
  src/Tribe/Tickets_Handler.php
Labels: merge

#702 Prevent fatals on plugin activation
  src/Tribe/Attendees.php
Labels: code review, merge

#704 #95098 - add back coding to trigger tribe dependency on base panel
  src/resources/js/tickets.js
  src/resources/js/tickets.min.js
Labels: code review, merge

#703 Add JSON-LD for custom post types with support for tickets
  readme.txt
  src/Tribe/JSON_LD/Order.php
  src/Tribe/JSON_LD/Type.php
  src/Tribe/Main.php
Labels: merge

#706 Update URL for tickets to work with plain permalink structure
  src/Tribe/Tickets_View.php
  src/views/tickets/orders-link.php
Labels: merge

#707 Make sure function exists before call it.
  src/Tribe/Commerce/Currency.php
Labels: merge

#701 Fixes glitch with Event Tickets + Enfold + WooCommerce
  readme.txt
  src/views/tickets/rsvp.php
Labels: merge

#708 Use timezones when comparing dates on a ticket
  readme.txt
  src/Tribe/Commerce/PayPal/Frontend/Tickets_Form.php
  src/Tribe/RSVP.php
  src/Tribe/Ticket_Object.php
Labels: merge

#669 Cache calls to `get_all_event_tickets` to avoid duplicates
  readme.txt
  src/Tribe/Tickets.php
Labels: code review

#705 Fix/1007336 unify upsell
  readme.txt
  src/admin-views/tribe-options-tickets.php
Labels: merge

#711 Fallback to numbers if any fail to use DateTime object
  src/Tribe/Ticket_Object.php
Labels: code review, merge

#713 Fix/102182 tc disabled by default
  readme.txt
  src/admin-views/tribe-options-tickets.php
Labels: merge

#712 Use a generic type for all other types for JSON-LD
  readme.txt
  src/Tribe/JSON_LD/Order.php
  src/Tribe/JSON_LD/Type.php
  src/Tribe/Tickets.php
Labels: code review, merge

#714 Prevent render two totals sections on the Attendanees tab
  src/Tribe/Commerce/PayPal/Attendance_Totals.php
  src/Tribe/Commerce/PayPal/Main.php
Labels: merge

#715 Remove old logic with date_in_range call
  src/template-tags/tickets.php
Labels: merge

#718 Make sure `Tribe__Events__Timezones` is present
  src/Tribe/Ticket_Object.php
Labels: merge

#721 Tweak js event for RSVP number field
  src/resources/css/accordion.css
  src/resources/css/accordion.min.css
  src/resources/css/rsvp.css
  src/resources/css/rsvp.min.css
  src/resources/css/tickets-refresh.css
  src/resources/css/tickets-refresh.min.css
  src/resources/js/rsvp.js
  src/resources/js/rsvp.min.js
Labels: merge
