Repository the-events-calendar/event-tickets, pull requests merged in 2018-12, with the labels that each got.

#983 Fix/119053 cancel button ux
  src/modules/blocks/rsvp/action-dashboard/container.js
  src/modules/blocks/ticket/dashboard/container.js
Labels: merge

#984 add focus styles for add and remove buttons
  src/styles/tickets/frontend.pcss
Labels: merge

#985 Fix/117627 new ticket issue
  src/modules/blocks/tickets/action-dashboard/container.js
  src/modules/blocks/tickets/action-dashboard/template.js
  src/modules/blocks/tickets/container/container.js
  src/modules/blocks/tickets/container/style.pcss
  src/modules/blocks/tickets/container/template.js
  src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
  src/modules/data/blocks/ticket/__tests__/selectors.test.js
  src/modules/data/blocks/ticket/selectors.js
Labels: merge

#968 Add Block Ticket Item registration
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Editor/Blocks/Tickets_Item.php
  src/Tribe/Editor/Provider.php
Labels: merge

#987 Set initial value of a ticket if has been created
  src/modules/data/blocks/ticket/sagas.js
Labels: merge

#966 Remove dependency from TEC for tickets
  src/modules/data/blocks/rsvp/sagas.js
  src/modules/data/blocks/ticket/sagas.js
Labels: merge

#982 Add display Title/Subtitle functionality for the attendees block
  src/modules/blocks/attendees/container.js
  src/modules/blocks/attendees/index.js
  src/modules/blocks/attendees/style.pcss
  src/modules/blocks/attendees/template.js
  src/modules/data/blocks/attendees/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/attendees/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/attendees/__tests__/actions.test.js
  src/modules/data/blocks/attendees/__tests__/reducer.test.js
  src/modules/data/blocks/attendees/__tests__/sagas.test.js
  src/modules/data/blocks/attendees/__tests__/selectors.test.js
  src/modules/data/blocks/attendees/__tests__/types.test.js
  src/modules/data/blocks/attendees/actions.js
  src/modules/data/blocks/attendees/reducer.js
  src/modules/data/blocks/attendees/sagas.js
  src/modules/data/blocks/attendees/selectors.js
  src/modules/data/blocks/attendees/types.js
  src/views/blocks/attendees/description.php
  src/views/blocks/attendees/title.php
Labels: code review

#990 Ensure 'Tribe__Events__Main' is called if exists
  src/Tribe/Editor/Compatibility/Tickets.php
Labels: merge

#992 Render <TicketsDashboard> only if has providers
  src/Tribe/REST/V1/Endpoints/Base.php
  src/modules/blocks/tickets/container.js
  src/modules/blocks/tickets/template.js
Labels: merge

#994 Prevent RSVP from showing on Tickets List Block
  src/Tribe/Editor/Blocks/Rsvp.php
  src/Tribe/Editor/Blocks/Tickets_Item.php
  src/views/blocks/tickets/item.php
Labels: code review

#995 Prevent to include RSVP as tickets
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Editor/Meta.php
Labels: merge

#993 Fix > RSVP > Login is required for purchase not working>
  src/views/blocks/attendees/description.php
  src/views/blocks/rsvp/details/availability.php
  src/views/blocks/rsvp/form/email.php
  src/views/blocks/rsvp/form/error.php
  src/views/blocks/rsvp/form/name.php
  src/views/blocks/rsvp/form/opt-out.php
  src/views/blocks/rsvp/form/submit-button.php
  src/views/blocks/rsvp/form/submit-login.php
  src/views/blocks/rsvp/icon.php
  src/views/blocks/rsvp/messages/success.php
  src/views/blocks/rsvp/status/full.php
  src/views/blocks/rsvp/status/going.php
  src/views/blocks/rsvp/status/not-going.php
  src/views/blocks/tickets/extra-available-quantity.php
  src/views/blocks/tickets/extra-available-unlimited.php
  src/views/blocks/tickets/extra-available.php
  src/views/blocks/tickets/quantity-add.php
  src/views/blocks/tickets/quantity-remove.php
  src/views/blocks/tickets/quantity-unavailable.php
  src/views/blocks/tickets/registration/attendee/fields/select.php
  src/views/blocks/tickets/registration/summary/ticket-quantity.php
  src/views/blocks/tickets/registration/summary/title.php
  src/views/blocks/tickets/submit-button.php
  src/views/blocks/tickets/submit-login.php
Labels: merge

#997 Spotfix/merge m18.18
  event-tickets.php
  lang/event-tickets-de_DE.mo
  lang/event-tickets-de_DE.po
  lang/event-tickets-eu.mo
  lang/event-tickets-eu.po
  lang/event-tickets-nb_NO.mo
  package.json
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Editor/Blocks/Rsvp.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Editor/Blocks/Tickets_Item.php
  src/Tribe/Editor/Compatibility/Tickets.php
  src/Tribe/Editor/Meta.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Editor/REST/Compatibility.php
  src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
  src/Tribe/Main.php
  src/Tribe/REST/V1/Endpoints/Base.php
  src/modules/blocks/attendees/container.js
  src/modules/blocks/attendees/index.js
  src/modules/blocks/attendees/style.pcss
  src/modules/blocks/attendees/template.js
  src/modules/blocks/tickets/action-dashboard/container.js
  src/modules/blocks/tickets/action-dashboard/template.js
  src/modules/blocks/tickets/container.js
  src/modules/blocks/tickets/container/container.js
  src/modules/blocks/tickets/container/style.pcss
  src/modules/blocks/tickets/container/template.js
  src/modules/blocks/tickets/template.js
  src/modules/data/blocks/attendees/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/attendees/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/attendees/__tests__/actions.test.js
  src/modules/data/blocks/attendees/__tests__/reducer.test.js
  src/modules/data/blocks/attendees/__tests__/sagas.test.js
  src/modules/data/blocks/attendees/__tests__/selectors.test.js
  src/modules/data/blocks/attendees/__tests__/types.test.js
  src/modules/data/blocks/attendees/actions.js
  src/modules/data/blocks/attendees/reducer.js
  src/modules/data/blocks/attendees/sagas.js
  src/modules/data/blocks/attendees/selectors.js
  src/modules/data/blocks/attendees/types.js
  src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
  src/modules/data/blocks/ticket/__tests__/selectors.test.js
  src/modules/data/blocks/ticket/sagas.js
  src/modules/data/blocks/ticket/selectors.js
  src/views/blocks/attendees/description.php
  src/views/blocks/attendees/title.php
  src/views/blocks/tickets/item.php
  src/views/registration/attendees/fields/select.php
Labels: merge

#999 Feature/118337 rsvp default sale
  src/modules/data/blocks/rsvp/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/rsvp/__tests__/__snapshots__/sagas.test.js.snap
  src/modules/data/blocks/rsvp/__tests__/sagas.test.js
  src/modules/data/blocks/rsvp/reducers/__tests__/__snapshots__/details.test.js.snap
  src/modules/data/blocks/rsvp/reducers/__tests__/__snapshots__/temp-details.test.js.snap
  src/modules/data/blocks/rsvp/reducers/details.js
  src/modules/data/blocks/rsvp/sagas.js
  src/modules/data/blocks/rsvp/selectors.js
  src/modules/data/blocks/rsvp/thunks.js
  src/modules/data/blocks/ticket/constants.js
  src/modules/data/blocks/ticket/reducers/tickets/ticket/details.js
  src/modules/data/blocks/ticket/reducers/tickets/ticket/temp-details.js
  src/modules/data/blocks/ticket/sagas.js
Labels: merge

#1001 fix rsvp is inactive check
  src/modules/blocks/rsvp/container.js
  src/modules/data/blocks/rsvp/thunks.js
Labels: merge

#1003 Fix RSVPs from showing in ticket block
  src/modules/data/blocks/ticket/constants.js
  src/modules/data/blocks/ticket/sagas.js
Labels: merge

#1000 Register blocks on `tribe_editor_register_blocks`
  src/Tribe/Editor/Provider.php
Labels: code review, merge

#1006 add focus styles for rsvp add and remove buttons
  src/styles/rsvp/frontend.pcss
Labels: merge

#1005 Tribe Commerce > only show "Log in before purchasing" when login is required
  readme.txt
  src/Tribe/Commerce/PayPal/Frontend/Tickets_Form.php
  src/views/tickets/tpp.php
Labels: merge

#1007 On Tickets Item block we prevent duplicated Items to the list
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Editor/Blocks/Tickets_Item.php
Labels: merge

#1008 Prevent the creation of q cache on empty $post_id
  src/Tribe/Attendees.php
  src/Tribe/Editor/Blocks/Attendees.php
Labels: merge

#1009 Sync MR 18.18 into MR.18.19
  src/Tribe/Attendees.php
  src/Tribe/Editor/Blocks/Attendees.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Editor/Blocks/Tickets_Item.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Main.php
  src/modules/blocks/rsvp/container.js
  src/modules/data/blocks/rsvp/thunks.js
  src/styles/rsvp/frontend.pcss
Labels: code review

#1020 Display only tickets that are in date range
  readme.txt
  src/Tribe/Editor/Blocks/Tickets_Item.php
Labels: merge

#1017 Add actions to update the Event Tickets blocks
  readme.txt
  src/Tribe/Editor.php
  src/Tribe/Editor/Compatibility/Tickets.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Editor/Template/Overwrite.php
  src/modules/blocks/tickets/index.js
Labels: merge

#1022 Blocks Inactive on TEC deactivated
  readme.txt
  src/Tribe/Editor.php
  src/Tribe/Editor/Compatibility/Tickets.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Editor/Template/Overwrite.php
  src/modules/blocks/tickets/index.js
Labels: merge

#1023 Prevent flush_blocks on older versions
  src/Tribe/Editor.php
Labels: merge

#1024 ⌗117794 TEC and ET Welcome Page Refreshes
  readme.txt
  src/Tribe/Main.php
  src/admin-views/admin-welcome-message.php
Labels: code review, merge

#1025 ⌗119644 ET Spotfix — Increase "Tested Up To" Value to 5.0
  readme.txt
Labels: merge

#1015 Feature/119049 ticket block default sale
  src/modules/data/blocks/rsvp/__tests__/__snapshots__/sagas.test.js.snap
  src/modules/data/blocks/rsvp/__tests__/sagas.test.js
  src/modules/data/blocks/rsvp/sagas.js
  src/modules/data/blocks/ticket/__tests__/__snapshots__/constants.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/sagas.test.js.snap
  src/modules/data/blocks/ticket/__tests__/sagas.test.js
  src/modules/data/blocks/ticket/sagas.js
  src/modules/data/shared/__tests__/__snapshots__/sagas.test.js.snap
  src/modules/data/shared/__tests__/sagas.test.js
  src/modules/data/shared/sagas.js
Labels: merge

#1021 Set custom date format to date pickers
  readme.txt
  src/resources/js/tickets.js
  src/resources/js/tickets.min.js
Labels: code review, merge

#1028 RSVP block shouldn't use Tickets as context variable
  src/Tribe/Editor/Blocks/Rsvp.php
  src/views/blocks/rsvp.php
Labels: merge

#1032 M18.19 Spotfix — Change Help Desk Links
  src/admin-views/admin-welcome-message.php
Labels: merge

#1036 Revert the new Welcome pages, they included external JS, not good for WP.org
  readme.txt
  src/admin-views/admin-welcome-message.php
Labels: code review, merge
