Repository the-events-calendar/event-tickets, pull requests merged in 2018-11, with the labels that each got.

#899 ⌗116853 Show Correct End-Sale Date Tooltips Based on Post Type
  readme.txt
  src/admin-views/editor/fieldset/advanced.php
Labels: merge

#900 Fix checkbox markup
  src/views/registration/attendees/fields/checkbox.php
  src/views/registration/attendees/fields/radio.php
Labels: merge

#901 Registration page QA Fixes
  src/admin-views/tribe-options-tickets.php
  src/resources/css/tickets-registration-page.css
  src/resources/css/tickets-registration-page.min.css
  src/resources/images/select.png
  src/resources/js/tickets-registration-page.js
  src/resources/js/tickets-registration-page.min.js
  src/resources/postcss/tickets-registration-page.pcss
  src/views/registration/attendees/content.php
  src/views/registration/attendees/fields.php
  src/views/registration/attendees/fields/checkbox.php
  src/views/registration/attendees/fields/radio.php
  src/views/registration/attendees/fields/select.php
  src/views/registration/attendees/fields/text.php
Labels: code review, merge

#902 Fix for QA findings on the attendee registration functionality
  src/resources/js/tickets-registration-page.js
  src/resources/js/tickets-registration-page.min.js
  src/views/registration/attendees/fields.php
  src/views/registration/attendees/fields/checkbox.php
  src/views/registration/attendees/fields/radio.php
Labels: merge

#903 Initial builds
  package-lock.json
  package.json
  src/modules/data/blocks/rsvp/sagas.js
  src/modules/data/blocks/ticket/sagas.js
  src/modules/package.json
  webpack.config.js
Labels: merge

#909 Update RSVP and ticket block initial start date to be published date
  src/modules/data/blocks/rsvp/sagas.js
  src/modules/data/blocks/ticket/sagas.js
Labels: merge

#904 Show the tickets without fields in the attendee registration summary
  src/Tribe/Attendee_Registration/View.php
  src/views/registration/attendees/content.php
Labels: code review, merge

#907 Add JS validation as HTML doesn't handle checkboxes, radios, etc
  src/resources/css/tickets-registration-page.css
  src/resources/css/tickets-registration-page.min.css
  src/resources/js/tickets-registration-page.js
  src/resources/js/tickets-registration-page.min.js
  src/resources/postcss/tickets-registration-page.pcss
  src/views/registration/attendees/error.php
  src/views/registration/attendees/fields/select.php
  src/views/registration/content.php
Labels: code review, merge

#916 Remove duplicate declaration of the `tickets.editor`
  src/Tribe/Editor/Provider.php
  src/Tribe/Service_Provider.php
Labels: merge

#917 Make sure Missing connection doesnt throw errors
  src/Tribe/Tickets_Handler.php
Labels: merge

#919 Update default end date to 100 years in the future
  src/modules/data/blocks/rsvp/reducers/details.js
  src/modules/data/blocks/ticket/reducers/ticket.js
Labels: merge

#923 Favor the usage of the constant for plugin registration
  src/modules/data/index.js
Labels: merge

#925 Rename prebuild script
  package.json
Labels: merge

#926 Render parts of the view conditionally if tickets+ is present
  src/modules/blocks/rsvp/action-dashboard/container.js
  src/modules/blocks/rsvp/action-dashboard/template.js
  src/modules/blocks/rsvp/advanced-options/container.js
  src/modules/blocks/rsvp/advanced-options/template.js
  src/modules/blocks/ticket/edit-container/container.js
  src/modules/blocks/ticket/edit-container/content/capacity/container.js
  src/modules/blocks/ticket/edit-container/content/capacity/style.pcss
  src/modules/blocks/ticket/edit-container/content/capacity/template.js
  src/modules/blocks/ticket/edit-container/content/template.js
  src/modules/blocks/ticket/edit-container/template.js
  src/modules/blocks/tickets/action-dashboard/container.js
  src/modules/blocks/tickets/action-dashboard/template.js
  src/modules/blocks/tickets/settings/container.js
  src/modules/blocks/tickets/settings/template.js
  src/modules/data/blocks/index.js
  src/modules/data/blocks/ticket/actions.js
  src/modules/data/blocks/ticket/sagas.js
  src/modules/data/blocks/ticket/selectors.js
  src/modules/data/blocks/ticket/types.js
  src/modules/data/index.js
  src/modules/data/sagas.js
Labels: merge

#922 Make the purchase flow work with tickets w/only non-mandatory fields in cart
  src/Tribe/Attendee_Registration/View.php
  src/Tribe/Tickets.php
  src/views/registration/button-checkout.php
  src/views/registration/content.php
Labels: code review, merge

#927 Make sure we load betas correctly with min version from ET+ and ET
  src/Tribe/Main.php
Labels: code review, merge

#930 Fix/tests
  __mocks__/@wordpress/blocks.js
  __mocks__/@wordpress/components.js
  __mocks__/@wordpress/data.js
  __mocks__/@wordpress/editor.js
  __mocks__/@wordpress/element.js
  __mocks__/@wordpress/i18n.js
  __mocks__/chrono-node.js
  __mocks__/icons.js
  __mocks__/uniqid.js
  jest.config.json
  jsconfig.json
  package-lock.json
  src/modules/data/blocks/rsvp/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/rsvp/reducers/__tests__/__snapshots__/details.test.js.snap
  src/modules/data/blocks/rsvp/reducers/__tests__/__snapshots__/temp-details.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
  src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/ticket.test.js.snap
  src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/tickets.test.js.snap
Labels: merge

#931 Import modules from the root of the package
  src/Tribe/Main.php
  src/modules/data/blocks/ticket/sagas.js
Labels: merge

#933 Add missing asssets from migration for FE view
  src/resources/js/views/rsvp.js
  src/resources/js/views/tickets.js
Labels: merge

#934 Capitalize *Unlimited*
  src/modules/blocks/ticket/edit-container/content/capacity/template.js
Labels: merge

#935 Fix: Tickets & RSVP blocks > Attendee and Order links are underlined
  src/modules/elements/action-button/style.pcss
Labels: code review

#936 Use tickets icon for child ticket block
  src/modules/blocks/ticket/__tests__/__snapshots__/index.test.js.snap
  src/modules/blocks/ticket/index.js
Labels: code review

#937 Prevent to trigger the cache on empty $post_id
  src/Tribe/Tickets.php
Labels: merge

#938 Fix/117446 rsvp date cutoff
  src/modules/blocks/rsvp/duration-picker/style.pcss
Labels: merge

#939 Fix/adjust lost block styles
  src/modules/blocks/rsvp/container-content/style.pcss
  src/modules/blocks/rsvp/duration-label/style.pcss
  src/modules/blocks/ticket/container-content/style.pcss
Labels: merge

#940 attendee registration opens in same window
  src/modules/blocks/rsvp/attendee-registration/template.js
  src/modules/blocks/ticket/container-content/attendees-registration/template.js
Labels: merge

#942 Make sure header image is a string
  src/modules/data/blocks/ticket/selectors.js
Labels: merge

#946 Show attendees block subtitle in the BE preview
  src/modules/blocks/attendees/template.js
Labels: merge

#943 Specify the type of header on Template level
  src/modules/blocks/tickets/container.js
  src/modules/blocks/tickets/template.js
  src/modules/data/blocks/ticket/selectors.js
Labels: code review

#949 Fix text for #946
  src/modules/blocks/attendees/template.js
Labels: merge

#953 Fix version compare for versions containing a hash within the string
  src/Tribe/Main.php
Labels: code review

#944 Display the ticket icon according to the date of the event
  src/modules/blocks/ticket/container/container.js
  src/modules/blocks/ticket/container/template.js
  src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
  src/modules/data/blocks/ticket/__tests__/selectors.test.js
  src/modules/data/blocks/ticket/selectors.js
Labels: code review

#957 Add "Move ticket" nonce
  src/Tribe/Editor/Configuration.php
Labels: code review

#958 Fix/rsvp tickets styles
  src/modules/blocks/rsvp/container-header/style.pcss
  src/modules/blocks/ticket/container-header/description/style.pcss
  src/modules/blocks/ticket/container-header/title/style.pcss
  src/modules/blocks/tickets/capacity-table/style.pcss
  src/modules/elements/action-button/style.pcss
  src/modules/elements/action-dashboard/style.pcss
  src/modules/elements/inactive-block/style.pcss
  src/modules/elements/settings-dashboard/style.pcss
Labels: merge

#955 Add support of Tickets for other types
  src/Tribe/Editor/Blocks/Attendees.php
  src/Tribe/Editor/Blocks/Rsvp.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Editor/Template.php
  src/Tribe/Editor/Template/Overwrite.php
  src/Tribe/Tickets.php
  src/views/blocks/attendees.php
Labels: code review

#945 Create tickets blocks associated to an event dynamically attached / removed
  src/Tribe/Editor/Meta.php
  src/Tribe/Editor/Provider.php
  src/modules/blocks/ticket/container-header/quantity/template.js
  src/modules/blocks/ticket/container/template.js
  src/modules/blocks/tickets/index.js
  src/modules/data/blocks/ticket/sagas.js
  src/modules/data/blocks/ticket/selectors.js
  src/modules/data/utils.js
Labels: code review

#959 Prevent to include blocks on non event types
  src/Tribe/Editor.php
Labels: merge

#961 fix import to ticket container
  src/modules/blocks/ticket/container/template.js
Labels: merge

#960 Community Tickets
  readme.txt
  src/Tribe/Metabox.php
Labels: merge

#956 Feature/117225 117226 ticket rsvp delete move
  src/modules/blocks/rsvp/advanced-options/container.js
  src/modules/blocks/rsvp/advanced-options/move-delete/container.js
  src/modules/blocks/rsvp/advanced-options/move-delete/style.pcss
  src/modules/blocks/rsvp/advanced-options/move-delete/template.js
  src/modules/blocks/rsvp/advanced-options/template.js
  src/modules/blocks/rsvp/container-content/template.js
  src/modules/blocks/rsvp/container.js
  src/modules/blocks/rsvp/container/template.js
  src/modules/blocks/rsvp/template.js
  src/modules/blocks/ticket/container-content/advanced-options/container.js
  src/modules/blocks/ticket/container-content/advanced-options/move-delete/container.js
  src/modules/blocks/ticket/container-content/advanced-options/move-delete/style.pcss
  src/modules/blocks/ticket/container-content/advanced-options/move-delete/template.js
  src/modules/blocks/ticket/container-content/advanced-options/template.js
  src/modules/blocks/ticket/container.js
  src/modules/blocks/ticket/template.js
  src/modules/blocks/tickets/container/template.js
  src/modules/data/blocks/rsvp/sagas.js
  src/modules/data/blocks/ticket/__tests__/sagas.test.js
  src/modules/data/blocks/ticket/sagas.js
  src/modules/data/reducers.js
  src/modules/data/sagas.js
  src/modules/data/shared/move/actions.js
  src/modules/data/shared/move/reducers/index.js
  src/modules/data/shared/move/reducers/modal.js
  src/modules/data/shared/move/reducers/postTypes.js
  src/modules/data/shared/move/reducers/posts.js
  src/modules/data/shared/move/reducers/ui.js
  src/modules/data/shared/move/sagas.js
  src/modules/data/shared/move/selectors.js
  src/modules/data/shared/move/types.js
  src/modules/elements/move-modal/container.js
  src/modules/elements/move-modal/index.js
  src/modules/elements/move-modal/style.pcss
  src/modules/elements/move-modal/template.js
Labels: merge

#963 Update events-gutenberg to events-tickets
  src/modules/blocks/attendees/index.js
  src/modules/blocks/attendees/template.js
  src/modules/blocks/rsvp/action-buttons/attendees-action-button/template.js
  src/modules/blocks/rsvp/action-buttons/settings-action-button/template.js
  src/modules/blocks/rsvp/action-dashboard/template.js
  src/modules/blocks/rsvp/advanced-options/template.js
  src/modules/blocks/rsvp/attendee-registration/template.js
  src/modules/blocks/rsvp/container-content/template.js
  src/modules/blocks/rsvp/container-header/template.js
  src/modules/blocks/rsvp/container/template.js
  src/modules/blocks/rsvp/counters/template.js
  src/modules/blocks/rsvp/duration-label/template.js
  src/modules/blocks/rsvp/header-image/template.js
  src/modules/blocks/rsvp/inactive-block/template.js
  src/modules/blocks/rsvp/index.js
  src/modules/blocks/ticket/container-content/advanced-options/duration/template.js
  src/modules/blocks/ticket/container-content/advanced-options/sku/template.js
  src/modules/blocks/ticket/container-content/advanced-options/template.js
  src/modules/blocks/ticket/container-content/attendees-registration/template.js
  src/modules/blocks/ticket/container-content/capacity/template.js
  src/modules/blocks/ticket/container-content/ecommerce-options/template.js
  src/modules/blocks/ticket/container-header/description/template.js
  src/modules/blocks/ticket/container-header/price/template.js
  src/modules/blocks/ticket/container-header/quantity/quantity-bar/element.js
  src/modules/blocks/ticket/container-header/quantity/template.js
  src/modules/blocks/ticket/container-header/title/template.js
  src/modules/blocks/ticket/dashboard/template.js
  src/modules/blocks/ticket/index.js
  src/modules/blocks/tickets/action-buttons/attendees/template.js
  src/modules/blocks/tickets/action-buttons/orders/template.js
  src/modules/blocks/tickets/action-buttons/settings/template.js
  src/modules/blocks/tickets/action-dashboard/template.js
  src/modules/blocks/tickets/availability/template.js
  src/modules/blocks/tickets/capacity-table/template.js
  src/modules/blocks/tickets/container/template.js
  src/modules/blocks/tickets/controls/template.js
  src/modules/blocks/tickets/header-image/template.js
  src/modules/blocks/tickets/index.js
  src/modules/data/blocks/ticket/options.js
  src/modules/elements/settings-dashboard/element.js
Labels: merge

#972 Attendee Registration > Fix select saved data
  src/views/registration/attendees/fields/select.php
Labels: merge

#969 Update reference to the right action
  src/modules/blocks/ticket/container-content/capacity/container.js
Labels: merge

#965 moved ecommerce options into advanced options
  src/modules/blocks/ticket/container-content/advanced-options/ecommerce-options/container.js
  src/modules/blocks/ticket/container-content/advanced-options/ecommerce-options/style.pcss
  src/modules/blocks/ticket/container-content/advanced-options/ecommerce-options/template.js
  src/modules/blocks/ticket/container-content/advanced-options/template.js
  src/modules/blocks/ticket/container-content/template.js
Labels: merge

#973 RSVP: Remove dotted border when the icon wrapper takes the whole width
  readme.txt
  src/styles/rsvp/frontend.pcss
Labels: code review

#975 Fix/119073 fatal fixes follow up
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
Labels: merge

#976 Static call syntax
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
Labels: code review, merge

#978 fix styles for attendees block title
  src/modules/blocks/attendees/style.pcss
Labels: merge

#977 Spotfix: Fix Version_Compare Check of ET and ET+ | ⌗119100
  event-tickets.php
  package.json
  readme.txt
  src/Tribe/Main.php
Labels: merge

#981 Sync hotfixes with MR18.17
  lang/event-tickets-de_DE.mo
  lang/event-tickets-de_DE.po
  lang/event-tickets-eu.mo
  lang/event-tickets-eu.po
  lang/event-tickets-nb_NO.mo
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
  src/Tribe/Main.php
Labels: code review, merge
