Repository the-events-calendar/event-tickets, pull requests merged in 2018-06, with the labels that each got.

#762 Don't manipulate stock when we shouldn't
  readme.txt
  src/Tribe/RSVP.php
Labels: merge

#765 Feature/75647 et welcome add https links
  readme.txt
  src/admin-views/admin-welcome-message.php
Labels: merge

#764 Feature/87686 non attendance email tweaks
  readme.txt
  src/views/tickets/email-non-attendance.php
Labels: merge

#767 Change filter default value to always show event date in RSVP ticket …
  readme.txt
  src/views/tickets/email-non-attendance.php
  src/views/tickets/email.php
Labels: merge

#766 Feature/79878 add action to tickets email template
  readme.txt
  src/views/tickets/email.php
Labels: code review, merge

#769 Fix missing headers issue
  src/Tribe/REST/V1/Main.php
Labels: merge

#742 Switch from esc_html() to esc_html__() | spotfix
  src/admin-views/tribe-options-tickets.php
Labels: merge

#770 Make sure we update the RSVP stock when we generate_tickets_for()
  src/Tribe/RSVP.php
  tests.md
  tests/_support/_generated/IntegrationTesterActions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/integration/RSVP_Tickets_Test.php
Labels: code review, merge

#768 Add a fallback transient check to make sure invoice number is reset
  src/Tribe/Commerce/PayPal/Gateway.php
Labels: code review, merge

#773 Add GDPR docs
  data_collection_disclosure.html
  site_owner_data_collection_statement.html
Labels: code review, merge

#774 Do some stylin'
  data_collection_disclosure.html
  site_owner_data_collection_statement.html
Labels: merge

#772 Fix/79877 display product image on email
  readme.txt
  src/views/tickets/email.php
Labels: merge

#776 Add files to whitelist
  package-whitelist.json
Labels: code review, merge

#771 Add notice if user doesn't have tickets
  readme.txt
  src/views/tickets/orders.php
Labels: merge

#777 Whenever we adjust sales, adjust stock
  composer.lock
  package-lock.json
  src/Tribe/RSVP.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Tickets/RSVPTest.php
Labels: merge

#778 Ensure the stock/sales are updated upon deleting an attendee from the admin
  src/Tribe/RSVP.php
Labels: code review

#782 Few fixes for M18.09
  lang/event-tickets-de_DE.mo
  lang/event-tickets-de_DE.po
  package-whitelist.json
  readme.txt
  tests/wpunit/Tribe/Tickets/RSVPTest.php
Labels: code review, merge

#783 Fix filename
  package-whitelist.json
Labels: merge

#780 Spotfix/108436 paypal purchase record
  readme.txt
  src/Tribe/Commerce/PayPal/Custom_Argument.php
Labels: bug, code review

#786 Bump version number on `views/tickets/orders.php`
  src/views/tickets/orders.php
Labels: merge

#785 Process and generate Paypal orders
  src/Tribe/Commerce/PayPal/Custom_Argument.php
  tests/_support/_generated/WpunitTesterActions.php
Labels: code review, merge

#787 Update changelog date.
  readme.txt
Labels: merge

#791 Init hotfix release
  event-tickets.php
  package.json
  readme.txt
  src/Tribe/Main.php
Labels: code review

#792 #109102 - fix fatal error when sending tickets other then woo
  readme.txt
  src/views/tickets/email.php
Labels: code review, merge

#793 #109115- Fix RSVP Check In with QR App
  src/Tribe/RSVP.php
Labels: code review

#794 Spotfix/merge 18.09.01 hotfix
  event-tickets.php
  package.json
  readme.txt
  src/Tribe/Main.php
  src/views/tickets/email.php
Labels: code review, merge

#795 Feature/105775 remove purchase limit
  src/Tribe/Commerce/PayPal/Gateway.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Ticket_Object.php
  src/Tribe/Tickets.php
Labels: merge

#797 Fix Issues with calculating and displaying ticketed events on the admin list
  readme.txt
  src/Tribe/Query.php
Labels: merge

#784 Corrections for Ticket ID
  src/Tribe/Commerce/PayPal/Main.php
Labels: merge

#799 Do not enable tickets on events by default when activating TEC
  readme.txt
  src/admin-views/tribe-options-tickets.php
Labels: merge

#800 Spotfix. Making string translatable.
  src/admin-views/tribe-options-tickets.php
Labels: merge

#796 Update RSVP.php for 81334
  src/Tribe/RSVP.php
Labels: code review, merge

#805 Remove patch for #73599
  readme.txt
  src/admin-views/tribe-options-tickets.php
Labels: code review, merge

#803 Spotfix: string didn't make it to POT
  src/admin-views/tribe-options-tickets.php
Labels: merge
