Repository the-events-calendar/event-tickets, pull requests merged in 2018-07, with the labels that each got.

#806 Add privacy policy guide for ET
  readme.txt
  src/Tribe/Main.php
  src/Tribe/Privacy.php
  src/admin-views/privacy.php
Labels: merge

#808 Gutenberg Compatibility
  src/Tribe/Tickets.php
Labels: merge

#810 Move Capacity hook properly setup
  src/Tribe/Tickets.php
Labels: code review, merge

#802 Update readme.txt for 81334
  readme.txt
Labels: merge

#811 Bump version number, and replace TBD refs.
  event-tickets.php
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Commerce/PayPal/Custom_Argument.php
  src/Tribe/Privacy.php
  src/Tribe/REST/Interfaces/Post_Repository.php
  src/Tribe/REST/V1/Documentation/Ticket_Definition_Provider.php
  src/Tribe/REST/V1/Endpoints/Base.php
  src/Tribe/REST/V1/Endpoints/Swagger_Documentation.php
  src/Tribe/REST/V1/Headers/Base.php
  src/Tribe/REST/V1/Main.php
  src/Tribe/REST/V1/Messages.php
  src/Tribe/REST/V1/Post_Repository.php
  src/Tribe/REST/V1/Service_Provider.php
  src/Tribe/REST/V1/Settings.php
  src/Tribe/REST/V1/System.php
  src/Tribe/Ticket_Object.php
  src/Tribe/Tickets.php
  src/Tribe/Validator/Base.php
  src/Tribe/Validator/Interface.php
  src/functions/advanced-functions/rest-v1.php
Labels: merge

#813 Update required common version to latest
  src/Tribe/Main.php
Labels: code review, merge

#814 M1810 - Update release date & i18n catalogs
  lang/event-tickets-af.po
  lang/event-tickets-bg_BG.po
  lang/event-tickets-ca.po
  lang/event-tickets-cs_CZ.po
  lang/event-tickets-da_DK.po
  lang/event-tickets-de_DE.mo
  lang/event-tickets-de_DE.po
  lang/event-tickets-el.mo
  lang/event-tickets-el.po
  lang/event-tickets-en_CA.mo
  lang/event-tickets-en_CA.po
  lang/event-tickets-en_GB.mo
  lang/event-tickets-en_GB.po
  lang/event-tickets-en_NZ.po
  lang/event-tickets-es_ES.po
  lang/event-tickets-et.po
  lang/event-tickets-eu.po
  lang/event-tickets-fi.po
  lang/event-tickets-fr_FR.po
  lang/event-tickets-hu_HU.mo
  lang/event-tickets-hu_HU.po
  lang/event-tickets-id_ID.po
  lang/event-tickets-is_IS.po
  lang/event-tickets-it_IT.po
  lang/event-tickets-ja.po
  lang/event-tickets-lt_LT.po
  lang/event-tickets-lv.po
  lang/event-tickets-nb_NO.po
  lang/event-tickets-nl_NL.po
  lang/event-tickets-pl_PL.po
  lang/event-tickets-pt_BR.po
  lang/event-tickets-pt_PT.po
  lang/event-tickets-ro_RO.mo
  lang/event-tickets-ro_RO.po
  lang/event-tickets-ru_RU.po
  lang/event-tickets-sk_SK.po
  lang/event-tickets-sl_SI.po
  lang/event-tickets-sr_RS.po
  lang/event-tickets-sv_SE.mo
  lang/event-tickets-sv_SE.po
  lang/event-tickets-tr_TR.po
  lang/event-tickets-uk.po
  lang/event-tickets-zh_CN.po
  lang/event-tickets-zh_TW.po
  readme.txt
Labels: merge

#815 #110248 - fix tribe_is_event fatal if the events calendar is not active
  event-tickets.php
  package.json
  readme.txt
  src/Tribe/Main.php
  src/Tribe/REST/V1/Headers/Base.php
Labels: merge

#816 Implement 'show description' setting for tribe commerce tickets
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
  src/views/tickets/tpp.php
Labels: merge

#818 Add post ID parameter to the_title filter in Tribe Commerce
  readme.txt
  src/Tribe/Commerce/Orders_Tabbed_View.php
Labels: code review, merge

#819 Make attendee list browser title translatable
  readme.txt
  src/Tribe/Attendees.php
Labels: code review, merge

#821 Stop showing tickets for past events with no end sale date.
  readme.txt
  src/Tribe/Ticket_Object.php
Labels: merge

#825 add waitlock config parameter to xDb modules
  tests/acceptance.suite.dist.yml
  tests/functional.suite.dist.yml
  tests/restv1.suite.dist.yml
Labels: code review

#822 Stop showing posts with "pending review" status in the blog page.
  readme.txt
  src/Tribe/Commerce/PayPal/Stati.php
Labels: merge

#820 Added parent post and order ID to a bunch of Tribe Commerce email filters
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
Labels: merge

#826 Adding filters so ET+ can hook here and add custom fields for RSVPs and TPPs
  src/Tribe/Privacy.php
Labels: code review, merge

#827 Add a filter for the tickets email image
  readme.txt
  src/views/tickets/email.php
Labels: merge

#829 GDPR: Added erasers & exporters
  readme.txt
  src/Tribe/Privacy.php
Labels: merge

#830 GDPR Eraser: Add missing variables and early bail
  src/Tribe/Privacy.php
Labels: merge

#834 Correct shortcode reference (spotfix) | #111011
  readme.txt
  src/admin-views/tribe-options-tickets.php
Labels: merge

#833 GDPR: Fix var name
  src/Tribe/Privacy.php
Labels: merge

#832 Jentheo patch 83857
  readme.txt
  src/Tribe/Tickets.php
Labels: merge

#837 M18.11 Update release date
  readme.txt
Labels: merge
