Repository the-events-calendar/event-tickets, pull requests merged in 2018-10, with the labels that each got.

#878 Use standalone localization for datepicker format
  src/Tribe/Assets.php
  src/resources/js/tickets.js
  src/resources/js/tickets.min.js
Labels: code review, merge

#882 Prevent fatal with latest ET alongside ET+ < 4.8
  event-tickets.php
  package.json
  readme.txt
  src/Tribe/Main.php
Labels: code review, merge

#884 Fix/109729 datepicker start on
  readme.txt
  src/resources/js/tickets.js
  src/resources/js/tickets.min.js
Labels: merge

#888 Add the Metabox backwards compat argument for Gutenberg
  src/Tribe/Metabox.php
Labels: merge

#889 REST API > Make the currency values dependants on the ticket provider
  readme.txt
  src/Tribe/Commerce/Currency.php
  src/Tribe/REST/V1/Post_Repository.php
Labels: merge

#890 M18.15 Spotfix: Add Launch Date
  readme.txt
Labels: merge

#891 M18.15 Spotfix: i18n
  lang/event-tickets-de_DE.mo
  lang/event-tickets-de_DE.po
  lang/event-tickets-es_ES.mo
  lang/event-tickets-es_ES.po
  lang/event-tickets-pt_BR.mo
  lang/event-tickets-pt_BR.po
  lang/event-tickets-ro_RO.mo
  lang/event-tickets-ro_RO.po
  package-lock.json
  readme.txt
Labels: code review

#893 Fix/104356 remaining qty shared capacity capped sales
  readme.txt
  src/resources/js/frontend-ticket-form.js
  src/resources/js/frontend-ticket-form.min.js
  src/resources/js/rsvp.js
  src/resources/js/rsvp.min.js
Labels: code review, merge

#885 Feature/108891 status manager class ttp
  src/Tribe/Attendee_Repository.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Commerce/PayPal/Orders/Sales.php
  src/Tribe/Commerce/PayPal/Orders/Table.php
  src/Tribe/Commerce/PayPal/Stati.php
  src/Tribe/Commerce/PayPal/Status/Complete.php
  src/Tribe/Commerce/PayPal/Status/Denied.php
  src/Tribe/Commerce/PayPal/Status/Not_Completed.php
  src/Tribe/Commerce/PayPal/Status/Pending.php
  src/Tribe/Commerce/PayPal/Status/Refunded.php
  src/Tribe/Commerce/PayPal/Status/Undefined.php
  src/Tribe/Commerce/PayPal/Status_Manager.php
  src/Tribe/Commerce/PayPal/Tickets_View.php
  src/Tribe/Status/Manager.php
  tests/wpunit/Tribe/Tickets/Status/ManagerTest.php
  tests/wpunit/Tribe/Tickets/Status/TTPManagerTest.php
Labels: hold, merge
