Repository the-events-calendar/event-tickets, pull requests merged in 2018-02, with the labels that each got.

#638 updating message language
  src/Tribe/Commerce/PayPal/Oversell/Admin_Notice_Decorator.php
Labels: code review, merge

#637 add some checks and casts to avoid notices
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Tickets_Handler.php
Labels: code review, merge

#639 Prevent free tickets on first creation too
  src/Tribe/Commerce/PayPal/Main.php
  src/admin-views/editor/fieldset/price.php
  src/admin-views/editor/panel/ticket.php
  src/resources/js/tickets.js
  src/resources/js/tickets.min.js
  src/resources/js/tpp-admin.js
  src/resources/js/tpp-admin.min.js
Labels: code review, merge

#635 Revert code from Tribe Commerce Email feature
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/RSVP.php
  src/admin-views/tribe-options-tickets.php
Labels: code review, merge

#641 format the price according to locale settings
  src/Tribe/Commerce/Currency.php
Labels: code review, merge

#643 Check for empty string too to find capacity
  src/Tribe/Tickets_Handler.php
Labels: merge

#640 add snapshot tests for the front-end tickets form
  composer.json
  composer.lock
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Frontend/Tickets_FormTest.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Frontend/__snapshots__/Tickets_FormTest__test_render_snapshot_with_available_tickets__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Frontend/__snapshots__/Tickets_FormTest__test_render_snapshot_with_no_available_tickets__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Frontend/__snapshots__/Tickets_FormTest__test_render_snapshot_with_no_tickets__1.php
Labels: merge

#646 Fix the display and calculation of sales for oversold orders
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Commerce/PayPal/Orders/Report.php
  src/Tribe/Commerce/PayPal/Orders/Sales.php
  src/Tribe/Commerce/PayPal/Oversell/Attendee_Handling_Decorator.php
  src/Tribe/Commerce/PayPal/Oversell/No_Oversell.php
  src/Tribe/Commerce/PayPal/Oversell/Policy.php
  src/Tribe/Commerce/PayPal/Oversell/Sell_All.php
  src/Tribe/Commerce/PayPal/Oversell/Sell_Available.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Frontend/__snapshots__/Tickets_FormTest__test_render_snapshot_with_available_tickets__1.php
Labels: code review

#645 Update release versions from 4.6.3 to 4.6.4
  event-tickets.php
  package.json
  readme.txt
  src/Tribe/Main.php
Labels: code review, merge

#648 Fix the Orders and currency display
  src/Tribe/Commerce/Currency.php
  src/admin-views/editor/button-view-orders.php
Labels: code review, merge

#650 try to fetch the tickt provider from the new settings first'
  src/Tribe/Tickets_Handler.php
Labels: merge

#651 pass the post ID when formatting the line total entry
  src/Tribe/Commerce/PayPal/Orders/Table.php
Labels: merge

#652 remove deprecated ticket saving code
  src/Tribe/Tickets_Handler.php
Labels: merge

#654 Update version numbers to match next release version
  event-tickets.php
  package.json
  readme.txt
  src/Tribe/Main.php
Labels: code review, merge

#658 Update source of the confirmation message
  src/Tribe/Commerce/PayPal/Main.php
Labels: merge

#659 Don't remove items from the array, just fetch them
  src/Tribe/Tickets.php
Labels: merge

#644 Update references to the correct class
  readme.txt
  src/Tribe/Attendees.php
Labels: merge

#660 Update the KB article link
  composer.json
  composer.lock
  src/admin-views/tribe-options-tickets.php
Labels: code review, merge

#663 Fix currency symbol position in display
  src/Tribe/Commerce/Currency.php
Labels: merge

#662 correctly handle unlimited capacity tickets
  src/Tribe/Tickets.php
Labels: merge

#661 update plugin description
  event-tickets.php
Labels: merge

#665 Fix the login requirement issue with EDD and Woo tickets
  src/Tribe/Tickets.php
Labels: code review, merge

#666 Check for woo and edd functions existence before trying to use them
  src/Tribe/Commerce/Currency.php
Labels: code review, merge
