Repository the-events-calendar/event-tickets, pull requests merged in 2018-05, with the labels that each got.

#743 Feature/105930 allow empty value for tickets enabled post types
  readme.txt
  src/admin-views/tribe-options-tickets.php
Labels: merge

#744 Display the correct number of attendees on the events list in the admin section
  readme.txt
  src/Tribe/Admin/Columns/Tickets.php
Labels: merge

#745 Display the correct number of available tickets on list and day view
  readme.txt
  src/Tribe/Tickets.php
Labels: code review

#746 Ensure that the ticket start and end sale date respect the event timezone
  readme.txt
  src/Tribe/Commerce/PayPal/Gateway.php
  src/Tribe/Ticket_Object.php
  src/views/tickets/rsvp.php
Labels: merge

#747 Add methods to handle refunds
  readme.txt
  src/Tribe/Ticket_Object.php
  src/template-tags/tickets.php
Labels: code review

#748 Making "Search attendees" translatable
  src/admin-views/attendees.php
Labels: merge

#749 #74523 - enable tickets view on front end even when hide from event l…
  readme.txt
  src/Tribe/Tickets_View.php
Labels: merge

#750 ⌗41649 Make QR Code Optional
  readme.txt
  src/admin-views/tribe-options-tickets.php
Labels: merge

#752 Fixes for Return to Cart link
  src/Tribe/Commerce/PayPal/Cart/Unmanaged.php
  src/Tribe/Commerce/PayPal/Gateway.php
  src/Tribe/Main.php
  src/Tribe/Redirections.php
  tests/_support/_generated/FunctionalTesterActions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/functional/Commerce/PayPal/ReturnToCartCest.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Cart/UnmanagedTest.php
Labels: merge

#753 ⌗97583 Better Handle Display of WC Membership Discounts on Tickets
  readme.txt
  src/admin-views/editor/fieldset/price.php
  src/template-tags/tickets.php
Labels: merge

#754 Spotfix: Bump Version Numbers for M18.08
  event-tickets.php
  package.json
  readme.txt
  src/Tribe/Main.php
Labels: merge

#755 ⌗41649 Ensure QR Code Option Only Shows when Event Tickets Plus is Active
  src/admin-views/tribe-options-tickets.php
Labels: code review

#760 Strip changelog entry that was applicable to ET+ | #41649
  readme.txt
Labels: code review

#758 Make sure the ticket creation is compatible with object cache.
  readme.txt
  src/Tribe/Cache/Transient_Cache.php
Labels: code review, merge

#759 Purge attendees transient on checkin/uncheckin
  readme.txt
  src/Tribe/Tickets.php
Labels: code review, merge

#761 Fix package-whitelist.json for datatables change
  package-whitelist.json
  readme.txt
Labels: code review, merge
