Repository the-events-calendar/event-tickets, pull requests merged in 2019-11, with the labels that each got.

#1431 Fix/135409 get event
  readme.txt
  src/Tribe/Editor/Blocks/Rsvp.php
Labels: merge

#1429 Some tweaks per Slack convo about reducing API calls.
  composer.lock
  src/Tribe/Assets.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/resources/js/tickets-block.js
Labels: merge

#1428 help IDE, formatting, typo, improved comments
  src/Tribe/Tickets.php
  src/template-tags/tickets.php
Labels: merge

#1423 correct global stock, including APM's display
  composer.lock
  package-lock.json
  package.json
  src/Tribe/Admin/Columns/Tickets.php
  src/Tribe/Admin/Move_Ticket_Types.php
  src/Tribe/Admin/Move_Tickets.php
  src/Tribe/Assets.php
  src/Tribe/Attendee_Registration/View.php
  src/Tribe/Commerce/PayPal/Endpoints/Success_Template.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Commerce/PayPal/Order.php
  src/Tribe/Editor/REST/Compatibility.php
  src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
  src/Tribe/Editor/REST/V1/Service_Provider.php
  src/Tribe/Global_Stock.php
  src/Tribe/Metabox.php
  src/Tribe/REST/V1/Post_Repository.php
  src/Tribe/RSVP/Attendance_Totals.php
  src/Tribe/Status/Abstract_Commerce.php
  src/Tribe/Ticket_Object.php
  src/Tribe/Ticket_Repository.php
  src/Tribe/Tickets.php
  src/Tribe/Tickets_Handler.php
  src/admin-views/editor/button-view-orders.php
  src/admin-views/editor/panel/list.php
  src/admin-views/editor/panel/settings.php
  src/template-tags/tickets.php
  tests/_support/Commerce/Attendee_Maker.php
  tests/_support/Commerce/PayPal/Order_Maker.php
  tests/_support/Commerce/PayPal/Ticket_Maker.php
  tests/wpunit/Tribe/Tickets/Template_Tags/GlobalStockTest.php
Labels: merge

#1432 Set interval to 60 seconds
  src/Tribe/Editor/Blocks/Tickets.php
Labels: merge

#1433 Add localizing of cart and checkout urls.
  src/Tribe/Assets.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/resources/js/tickets-block.js
Labels: merge

#1435 feat(modal form submit): Change the way we submit the modal forms.
  src/Tribe/Attendee_Registration/Modal.php
  src/resources/js/tickets-block.js
  src/resources/js/tickets-registration-page.js
  src/resources/postcss/tickets.pcss
  src/views/blocks/tickets.php
  src/views/blocks/tickets/submit-button-modal.php
  src/views/modal/cart.php
  src/views/modal/registration-js.php
  src/views/modal/registration.php
  src/views/registration-js/attendees/fields.php
Labels: code review

#1436 Remove commented out line
  src/Tribe/Attendee_Registration/Modal.php
Labels: merge

#1434 Update Cart handling so it's not just REST context only
  composer.lock
  package.json
  src/Tribe/Commerce/Cart.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Main.php
  src/Tribe/REST/V1/Endpoints/Base.php
  src/Tribe/REST/V1/Endpoints/Cart.php
  src/Tribe/Tickets_Handler.php
  tests/restv1/PayPal/CartCest.php
  tests/restv1/PayPal/CartUpdateCest.php
Labels: merge

#1439 Run hooks for cart so that we can check if the $_POST request is happening
  src/Tribe/Main.php
Labels: merge

#1440 Add stripslashes so data is parsed correctly.
  src/Tribe/Commerce/Cart.php
Labels: merge

#1438 Correct total calcs in modal ticket block.
  src/resources/js/tickets-block.js
Labels: merge

#1441 only send numerics to number format
  src/template-tags/tickets.php
Labels: merge

#1442 Tweak the logic that determines if we are on the AR page
  src/Tribe/Attendee_Registration/Main.php
Labels: merge

#1443 Fix AR page saving so it is not additive; Redirect to AR Page if meta not up to date for TC
  src/Tribe/Commerce/Cart.php
Labels: merge

#1444 Alter AR page so we do a regular form submit.
  src/resources/js/tickets-registration-page.js
  src/resources/postcss/tickets-registration-page.pcss
  src/views/modal/registration-js.php
  src/views/registration-js/content.php
Labels: merge

#1445 Fix cart fatals
  composer.lock
  src/Tribe/Editor/Blocks/Tickets.php
Labels: merge

#1446 Fix/classic classic form submission
  src/resources/js/tickets-block.js
  src/resources/js/tickets-registration-page.js
  src/views/blocks/tickets.php
Labels: merge

#1377 Feature/132348 orm tests attendees
  tests/_support/Commerce/ORMTestCase.php
  tests/wpunit/Tribe/Tickets/ORM/Attendees/FilterTest.php
Labels: merge

#1447 Style tweaks and a patch for price calcs
  src/resources/js/tickets-block.js
  src/resources/postcss/tickets.pcss
Labels: merge

#1448 Feature/136322 old wp
  composer.lock
  src/Tribe/Assets.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Tickets.php
  src/resources/js/frontend-ticket-form.js
  src/resources/js/tickets-block.js
Labels: merge

#1457 Fix ticketed event saves.
  readme.txt
  src/Tribe/Editor/Meta.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Tickets_Handler.php
Labels: code review

#1456 VR > ET Integration
  src/views/v2/day/event/cost.php
  src/views/v2/list/event/cost.php
  src/views/v2/map/event-cards/event-card/event/actions/cost.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cost.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/cost.php
  src/views/v2/photo/event/cost.php
  src/views/v2/week/grid-body/events-day/event/tooltip/cost.php
  src/views/v2/week/mobile-events/day/event/cost.php
Labels: code review, needs release

#1459 Implement _or_null methods and don't update/delete fake meta fields
  readme.txt
  src/Tribe/Editor/Meta.php
  src/Tribe/Tickets_Handler.php
Labels: merge

#1460 Hotfix - Add same for RSVP
  composer.lock
  src/modules/blocks/rsvp/attendee-registration/container.js
Labels: merge

#1464 Definition of Views V2 should rely on Events Function
  src/functions/views/provider.php
Labels: merge

#1465 version bump
  event-tickets.php
  readme.txt
  src/Tribe/Main.php
Labels: merge

#1462 #135919 & #136900 - add hooks for registration and attendee meta upda…
  src/Tribe/RSVP.php
Labels: merge

#1466 Fixes an undefined var issue
  composer.lock
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Tickets.php
Labels: merge

#1467 Correct namespacing to all files + Composer autoload
  composer.json
  package-lock.json
  src/Tribe/Events/Views/V2/Hooks.php
  src/Tribe/Events/Views/V2/Models/Tickets.php
  src/Tribe/Events/Views/V2/Service_Provider.php
  src/Tribe/Main.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/Day_View/Event/CostTest.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/Day_View/Event/__snapshots__/CostTest__test_render_with_cost__1.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/Day_View/Event/__snapshots__/CostTest__test_render_without_cost__1.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/List_View/Event/CostTest.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/List_View/Event/__snapshots__/CostTest__test_render_with_cost__1.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/List_View/Event/__snapshots__/CostTest__test_render_without_cost__1.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/CostTest.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/CostTest__test_render_with_cost__1.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/CostTest__test_render_without_cost__1.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/CostTest.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/__snapshots__/CostTest__test_render_with_cost__1.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/Month_View/Mobile_Events/Mobile_Day/Mobile_Event/__snapshots__/CostTest__test_render_without_cost__1.php
  tests/views_integration/_bootstrap.php
Labels: code review

#1468 Fixes missing admin stylesheet.
  src/Tribe/Assets.php
Labels: merge

#1469 Fix ARI checkbox saving from AR Modal / AR Page
  src/Tribe/Attendee_Registration/Main.php
  src/Tribe/Attendee_Registration/View.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Tickets.php
  src/views/blocks/tickets/item.php
  src/views/registration-js/attendees/fields/checkbox.php
Labels: merge

#1470 Fix missing block on ticketed page.
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Tickets.php
Labels: merge

#1471 Fix EDD cart bugs and redirect problems
  src/Tribe/Attendee_Registration/View.php
  src/Tribe/Tickets.php
  src/views/blocks/tickets/quantity-number.php
Labels: merge

#1472 Past RSVP no longer breaks views
  src/views/v2/day/event/cost.php
  src/views/v2/list/event/cost.php
  src/views/v2/map/event-cards/event-card/event/actions/cost.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cost.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/cost.php
  src/views/v2/photo/event/cost.php
  src/views/v2/week/grid-body/events-day/event/tooltip/cost.php
  src/views/v2/week/mobile-events/day/event/cost.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/Day_View/Event/__snapshots__/CostTest__test_render_with_cost__1.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/List_View/Event/__snapshots__/CostTest__test_render_with_cost__1.php
  tests/views_integration/Tribe/Tickets/Events/Views/V2/Partials/Month_View/Calendar_Body/Day/Calendar_Events/Calendar_Event/Tooltip/__snapshots__/CostTest__test_render_with_cost__1.php
Labels: merge

#1474 Remove line from readme for item that got held back
  readme.txt
Labels: merge

#1477 Move all attendee options to ET+,
  src/Tribe/Attendee_Registration/Main.php
  src/admin-views/tribe-options-tickets.php
Labels: merge

#1478 Whitespace fail.
  src/resources/js/tickets-block.js
Labels: merge

#1479 Ensure that session storage is cleared on successful submit of modal.
  src/resources/js/frontend-ticket-form.js
  src/resources/js/tickets-block.js
Labels: merge

#1480 Fix additive handling of meta saves from AR page
  src/Tribe/Commerce/Cart.php
Labels: merge

#1481 Correct number format handling on AR page.
  src/resources/js/tickets-block.js
  src/resources/js/tickets-registration-page.js
Labels: merge

#1482 Fix getPrice() - stop using parseFloat for money!
  src/resources/js/tickets-block.js
  src/resources/js/tickets-registration-page.js
Labels: merge

#1483 Don't output extra hdiden inputs for each event
  src/views/registration-js/content.php
Labels: code review, merge

#1487 Version bump
  event-tickets.php
  package.json
  readme.txt
  src/Tribe/Main.php
Labels: merge

#1485 fix(ticket end date): Correct the automatic generation of ticket end dates.
  readme.txt
  src/Tribe/Tickets.php
  src/Tribe/Tickets_Handler.php
Labels: merge

#1495 Fix/test gitignore
  .env.testing
  .gitignore
Labels: merge
