Repository the-events-calendar/event-tickets, pull requests merged in 2019-10, with the labels that each got.

#1382 Loaders and Tweaks
  composer.lock
  src/Tribe/Assets.php
  src/Tribe/Attendee_Registration/Modal.php
  src/Tribe/Tickets.php
  src/Tribe/Tickets_View.php
  src/resources/js/tickets-block.js
  src/resources/js/tickets-registration-page.js
  src/resources/postcss/components/_all.pcss
  src/resources/postcss/components/_loader.pcss
  src/resources/postcss/reset.pcss
  src/resources/postcss/tickets-registration-page.pcss
  src/resources/postcss/tickets.pcss
  src/views/blocks/rsvp/form/opt-out.php
  src/views/blocks/tickets/extra-available-quantity.php
  src/views/blocks/tickets/submit-button-modal.php
  src/views/components/loader.php
  src/views/modal/cart.php
  src/views/modal/registration-js.php
  src/views/registration-js/content.php
  src/views/registration-js/mini-cart.php
  src/views/registration/summary/title.php
Labels: merge

#1384 Fix/134108 orders info capacity reached
  readme.txt
  src/Tribe/Status/Abstract_Commerce.php
Labels: merge

#1386 Fix fatal errors and adjust formatting
  src/Tribe/Attendee_Registration/Main.php
  src/Tribe/Main.php
  src/Tribe/RSVP.php
  src/views/registration-js/content.php
Labels: merge

#1388 Template tweak to correct missing message
  readme.txt
  src/views/blocks/tickets.php
Labels: merge

#1387 Correct bad attendee #s getting passed.
  readme.txt
  src/Tribe/RSVP.php
Labels: merge

#1371 Fix timezone problems and add tests
  composer.lock
  package-lock.json
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Editor/Blocks/Rsvp.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Main.php
  src/Tribe/REST/V1/Post_Repository.php
  src/Tribe/Ticket_Object.php
  src/Tribe/Ticket_Repository.php
  src/Tribe/Tickets.php
  src/views/tickets/tpp.php
  tests/_support/Testcases/Ticket_Object_TestCase.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Main/AmericaTest.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Main/AustraliaTest.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Main/UTCTest.php
  tests/wpunit/Tribe/Tickets/Main/Event/AmericaTest.php
  tests/wpunit/Tribe/Tickets/Main/Event/AustraliaTest.php
  tests/wpunit/Tribe/Tickets/Main/Event/UTCTest.php
  tests/wpunit/Tribe/Tickets/Main/Post/AmericaTest.php
  tests/wpunit/Tribe/Tickets/Main/Post/AustraliaTest.php
  tests/wpunit/Tribe/Tickets/Main/Post/UTCTest.php
  tests/wpunit/Tribe/Tickets/MainTest.php
  tests/wpunit/Tribe/Tickets/Ticket_Object/AmericaTest.php
  tests/wpunit/Tribe/Tickets/Ticket_Object/AustraliaTest.php
  tests/wpunit/Tribe/Tickets/Ticket_Object/UTCTest.php
  tests/wpunit/Tribe/Tickets/Ticket_ObjectTest.php
  tests/wpunit/Tribe/Tickets/Tickets/AmericaTest.php
  tests/wpunit/Tribe/Tickets/Tickets/AustraliaTest.php
  tests/wpunit/Tribe/Tickets/Tickets/UTCTest.php
  tests/wpunit/Tribe/Tickets/TicketsTest.php
Labels: code review, hold, in-qa

#1390 Correct bad version test.
  src/Tribe/Main.php
  src/admin-views/tribe-options-tickets.php
Labels: merge

#1392 Implement the new loader and move the loader to inside the tickets-block.
  src/Tribe/Tickets_View.php
  src/resources/js/tickets-block.js
  src/resources/postcss/common/components/_all.pcss
  src/resources/postcss/common/components/_loader.pcss
  src/resources/postcss/components/_loader.pcss
  src/resources/postcss/tickets.pcss
  src/views/blocks/tickets.php
  src/views/blocks/tickets/footer.php
  src/views/blocks/tickets/submit-button-modal.php
  src/views/components/loader.php
  src/views/modal/cart.php
  src/views/modal/registration-js.php
  src/views/registration-js/attendees/content.php
  src/views/tickets/orders.php
  src/views/tickets/tpp-success.php
Labels: merge

#1393 Adding a GitHub Action to perform automated code reviews with phpcs
  .github/workflows/main.yml
Labels: merge

#1394 Add eslint Workflow
  .github/workflows/eslint.yml
  .github/workflows/main.yml
  .github/workflows/phpcs.yml
Labels: merge

#1397 fix(tickets block): Fixes duplicate block on posts/pages.
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/REST/V1/Endpoints/Cart.php
  src/resources/js/tickets-block.js
  src/resources/js/tickets-registration-page.js
  src/resources/postcss/common/base/typography/_headings.pcss
  src/resources/postcss/common/resets/_twentyseventeen.pcss
  src/resources/postcss/components/_notice.pcss
  src/resources/postcss/tickets-registration-page.pcss
  src/resources/postcss/tickets.pcss
  src/views/blocks/tickets.php
  src/views/blocks/tickets/footer.php
  src/views/blocks/tickets/item.php
  src/views/blocks/tickets/submit.php
  src/views/components/notice.php
  src/views/modal/registration-js.php
  src/views/registration-js/content.php
  src/views/registration-js/mini-cart.php
Labels: merge

#1402 Fix RSVP/Tickets view links
  src/Tribe/Tickets_View.php
  src/views/blocks/tickets.php
Labels: code review, merge

#1405 Handle back button and reloading data.
  src/resources/js/tickets-block.js
  src/resources/postcss/tickets.pcss
Labels: merge

#1404 Tweak cart handling to always handle cart from session properly
  src/Tribe/Commerce/PayPal/Cart/Unmanaged.php
Labels: merge

#1406 Add invalid style to radio/checkboxes.
  src/resources/js/tickets-block.js
  src/resources/postcss/tickets.pcss
Labels: merge

#1408 Fix AR flow handling of AR meta being up to date
  composer.lock
  src/resources/js/tickets-block.js
  src/resources/js/tickets-registration-page.js
Labels: merge

#1409 feat(API loader): Add loader indicator for all API calls.
  src/resources/js/tickets-block.js
  src/resources/js/tickets-registration-page.js
  src/resources/postcss/tickets-registration-page.pcss
  src/views/blocks/tickets.php
  src/views/components/loader.php
  src/views/modal/cart.php
  src/views/modal/registration.php
  src/views/registration-js/content.php
Labels: merge

#1410 fix(provider in template): Add check for incorrect provider `tribe_events_has_tickets_on_sale`
  src/template-tags/tickets.php
Labels: merge

#1412 Fix 'My Tickets' link handling for RSVP/tickets
  src/Tribe/Tickets_View.php
  src/views/blocks/rsvp.php
  src/views/tickets/rsvp.php
  src/views/tickets/view-link.php
Labels: merge

#1415 update repo names to be lowercase | spotfix
  composer.json
  composer.lock
Labels: merge

#1414 Add quantity notice action to new content template
  src/views/registration-js/content.php
Labels: merge

#1416 Adds a "clean" function to strip separators
  composer.lock
  src/resources/js/tickets-block.js
Labels: merge

#1417 Fix/136300 currency in calcs
  src/resources/js/tickets-block.js
Labels: merge

#1419 A few style fixes from @niconerd 's spreadsheet.
  src/resources/postcss/common/base/typography/_body.pcss
  src/resources/postcss/tickets.pcss
  src/views/blocks/tickets/content-description.php
Labels: merge

#1418 On older (4.7) WP tribe() fails here - let's not use it.
  src/Tribe/Editor/Provider.php
Labels: merge

#1422 A few spacing tweaks via mattcr
  src/resources/postcss/tickets.pcss
  src/views/registration-js/attendees/fields.php
Labels: merge

#1420 Remove js that disables TCC tickets when one is selected.
  composer.lock
  src/resources/js/tickets-block.js
Labels: merge

#1421 Feature/129440 api messaging
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/REST/V1/Messages.php
  src/resources/js/tickets-block.js
Labels: merge

#1425 Prevent fadeout in modal. Fix calcs.
  src/resources/js/tickets-block.js
Labels: merge

#1426 Add block for tickets/rsvps with correct text.
  src/admin-views/editor/panel/ticket.php
Labels: merge
