Repository the-events-calendar/event-tickets, pull requests merged in 2019-12, with the labels that each got.

#1488 Use the same loading icon for the RSVP block that we're using for the tickets block.
  readme.txt
  src/resources/js/rsvp-block.js
  src/resources/postcss/rsvp.pcss
  src/styles/rsvp/frontend.pcss
  src/template-tags/tickets.php
  src/views/blocks/rsvp.php
  src/views/blocks/rsvp/loader.php
  src/views/blocks/tickets.php
Labels: merge

#1486 fix(rsvp image): Fix rsvp header image attachment.
  readme.txt
  src/modules/blocks/rsvp/header-image/container.js
Labels: merge

#1496 Fix Tribe Commerce AR meta flow handling (non-AR modal)
  src/Tribe/Attendee_Registration/View.php
  src/Tribe/Commerce/Cart.php
  src/Tribe/Commerce/PayPal/Cart/Unmanaged.php
  src/Tribe/Commerce/PayPal/Gateway.php
  src/Tribe/Commerce/PayPal/Main.php
  src/views/registration-js/content.php
Labels: merge

#1490 Help IDE
  src/Tribe/Abstract_Attendance_Totals.php
  src/Tribe/Attendee_Repository.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Commerce/PayPal/Orders/Report.php
  src/Tribe/Commerce/PayPal/Orders/Sales.php
  src/Tribe/Commerce/PayPal/Orders/Table.php
  src/Tribe/Commerce/PayPal/Stati.php
  src/Tribe/Commerce/PayPal/Tickets_View.php
  src/Tribe/Data_API.php
  src/Tribe/RSVP.php
  src/Tribe/Status/Abstract_Commerce.php
  src/Tribe/Ticket_Object.php
  src/Tribe/Tickets_View.php
Labels: merge

#1499 Fix additive handling for Tribe Commerce coming from ticket block
  src/Tribe/Commerce/Cart.php
  src/Tribe/Commerce/PayPal/Main.php
  src/template-tags/tickets.php
  src/views/registration-js/content.php
Labels: merge

#1493 fix(tickets block): Prevent duplicate blocks on provider change.
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
Labels: merge

#1494 Fix/133432 filterable qty limit
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Ticket_Object.php
  src/Tribe/Tickets_View.php
  src/views/blocks/rsvp/details/availability.php
  src/views/blocks/rsvp/form/quantity-input.php
  src/views/blocks/tickets/extra-available-quantity.php
  src/views/blocks/tickets/extra-available.php
  src/views/blocks/tickets/extra.php
  src/views/blocks/tickets/item.php
  src/views/blocks/tickets/quantity.php
  src/views/tickets/rsvp.php
Labels: merge

#1507 Update ticket maker for PayPal to set ticket provider field on post
  composer.lock
  package-lock.json
  tests/_support/Commerce/PayPal/Ticket_Maker.php
Labels: merge

#1508 Fix fatal error when tribe() container doesn't exist
  src/Tribe/Tickets.php
Labels: merge

#1500 Fix/124403 asset loading
  readme.txt
  src/Tribe/Assets.php
  src/Tribe/Main.php
  src/template-tags/tickets.php
Labels: merge

#1510 Fix RSVP saving of capacity and not going fields
  readme.txt
  src/Tribe/Editor/Meta.php
Labels: merge

#1511 refactor(change button text): Change text of AR page submit button.
  src/views/blocks/tickets/registration/attendee/submit.php
Labels: merge

#1501 feat(ticket left display): Add threshold checks to RSVP and ticket templates.
  .gitignore
  readme.txt
  src/Tribe/Editor/Blocks/Rsvp.php
  src/Tribe/Views/V2/Models/Tickets.php
  src/template-tags/tickets.php
  src/views/blocks/rsvp/details/availability.php
  src/views/blocks/tickets/extra-available.php
  src/views/tickets/rsvp.php
  src/views/tickets/tpp.php
Labels: merge

#1449 Task/137152 orm tests attendees
  tests/_support/Commerce/Attendee_Maker.php
  tests/_support/Commerce/ORMTestCase.php
Labels: merge

#1513 Make get_tickets() protected again
  readme.txt
  src/Tribe/Tickets.php
Labels: merge

#1512 When setting up assets, don't load all tickets on every page
  composer.lock
  event-tickets.php
  readme.txt
  src/Tribe/Attendee_Registration/View.php
  src/Tribe/Commerce/Currency.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Main.php
  src/Tribe/Tickets.php
Labels: merge

#1514 Release G19.14.2
  composer.lock
  event-tickets.php
  readme.txt
  src/Tribe/Attendee_Registration/View.php
  src/Tribe/Commerce/Currency.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Main.php
  src/Tribe/Tickets.php
Labels: hold

#1454 Feature/136595 maybe submit on enter
  readme.txt
  src/resources/js/tickets-block.js
Labels: merge

#1515 improve sizing on +/- for tickets
  readme.txt
  src/styles/tickets/frontend.pcss
Labels: merge

#1516 Handle special characters for Event Ticket field labels like single quotes and colons so they don't break the saving
  readme.txt
  src/resources/js/tickets.js
Labels: merge

#1491 fix(API security): Don't allow viewing "private" attendees if user can't
  readme.txt
  src/Tribe/Attendee_Repository.php
  src/Tribe/REST/V1/Attendee_Repository.php
  tests/restv1/AttendeeArchiveByAttendeeMetaCest.php
  tests/restv1/AttendeeArchiveByCheckedinCest.php
  tests/restv1/AttendeeArchiveByDateCest.php
  tests/restv1/AttendeeArchiveByIdsCest.php
  tests/restv1/AttendeeArchiveByPriceCest.php
  tests/restv1/AttendeeArchiveByProviderCest.php
  tests/restv1/AttendeeArchiveByRelatedPostCest.php
  tests/restv1/AttendeeArchiveOffsetCest.php
  tests/restv1/AttendeeArchiveOrderCest.php
  tests/restv1/AttendeeArchiveSearchCest.php
Labels: merge

#1518 Enforce string when getting capacity amount and fix threshold restriction
  src/Tribe/Tickets_Handler.php
  src/views/blocks/rsvp/details/availability.php
  src/views/blocks/tickets/extra-available.php
  src/views/tickets/rsvp.php
  src/views/tickets/tpp.php
Labels: merge

#1519 Don't try to laod RSVPs into the tickets block
  readme.txt
  src/Tribe/Editor/Blocks/Tickets.php
Labels: merge

#1517 Correct shared cap and tweak keyboad controls on ticket block.
  composer.lock
  readme.txt
  src/Tribe/Editor/Blocks/Attendees.php
  src/resources/js/frontend-ticket-form.js
  src/resources/js/tickets-block.js
  src/views/blocks/tickets/item.php
Labels: merge

#1522 Removing jquery-ui-datepicker from the frontend because it is unused
  src/Tribe/Assets.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Editor/Blocks/Rsvp.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/RSVP.php
Labels: code review
