Repository the-events-calendar/event-tickets, pull requests merged in 2019-05, with the labels that each got.

#1246 #102636 - update stock on move of rsvp tickets
  src/Tribe/Admin/Move_Tickets.php
Labels: merge

#1248 refactor(attendee report): Change the text of tooltips on the attendee report page.
  readme.txt
  src/Tribe/Abstract_Attendance_Totals.php
  src/Tribe/Commerce/PayPal/Attendance_Totals.php
  src/admin-views/order-available.php
  src/admin-views/order-pending-completion.php
Labels: merge

#1249 fix(report tooltips): Correct one message that was C&P wrong.
  src/Tribe/Abstract_Attendance_Totals.php
Labels: merge

#1251 Fix a string and format the Orders tab availability tooltip.
  src/Tribe/Abstract_Attendance_Totals.php
  src/admin-views/order-available.php
Labels: merge

#1252 fix(attendee registration shortcode): Correct issue with TC
  readme.txt
  src/Tribe/Attendee_Registration/Shortcode.php
  src/Tribe/Attendee_Registration/Template.php
Labels: merge

#1253 Fix/126216 tpp attendance totals tests
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/AttendanceTotalsTest.php
Labels: merge

#1235 Add moar template tag tests!
  src/Tribe/Data_API.php
  src/template-tags/tickets.php
  tests.md
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Tickets/Admin/Screen_Options/Screen_OptionsTest.php
  tests/wpunit/Tribe/Tickets/Template_TagsTest.php
Labels: merge

#1256 fix(Main): fix autoloader related issues
  src/Tribe/Main.php
  tests/acceptance.suite.dist.yml
  tests/functional.suite.dist.yml
  tests/restv1.suite.dist.yml
Labels: bug, hold

#1255 Spotfix/cant add tickets
  src/modules/blocks/tickets/action-dashboard/container.js
  src/modules/blocks/tickets/container/template.js
  tests/_support/_generated/AcceptanceTesterActions.php
Labels: merge

#1264 fix(admin ticket blocks): Remove ability to add multiple tickets or rsvp blocks to a single event/post
  readme.txt
  src/modules/blocks/rsvp/index.js
  src/modules/blocks/tickets/index.js
Labels: merge

#1265 Fix attendees tickets counts in block view
  .gitignore
  .travis.yml
  dev/functions.sh
  src/Tribe/Attendee_Repository.php
  src/Tribe/Tickets.php
  src/Tribe/Tickets_View.php
  tests/_support/_generated/AcceptanceTesterActions.php
  tests/_support/_generated/FunctionalTesterActions.php
  tests/_support/_generated/IntegrationTesterActions.php
  tests/_support/_generated/Restv1TesterActions.php
  tests/_support/_generated/UnitTesterActions.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/Tribe/Tickets/TicketsTest.php
Labels: merge

#1266 Fix optout ORM logic
  src/Tribe/Attendee_Repository.php
Labels: merge

#1267 Fix RSVP by Order ORM filtering
  src/Tribe/Attendee_Repository.php
  tests/wpunit/Tribe/Tickets/Attendees_TableTest.php
Labels: merge

#1270 Fix attendees count user logic
  dev/functions.sh
  src/Tribe/Tickets_View.php
Labels: merge

#1269 feat(admin tickets editor): Add class to wrapper div.
  readme.txt
  src/admin-views/editor/panel/list.php
Labels: merge

#1268 Fix/127710 restv1 tests
  .travis.yml
  tests/_data/REST/V1/mu-plugins/test-attendees.php
  tests/restv1.suite.dist.yml
  tests/restv1/AttendeeArchiveCest.php
Labels: merge

#1271 Fix RSVP queries
  src/Tribe/Attendee_Repository.php
  src/Tribe/REST/V1/Attendee_Repository.php
  src/Tribe/REST/V1/Endpoints/Attendee_Archive.php
  src/Tribe/RSVP.php
  src/Tribe/RSVP/Attendance_Totals.php
  src/Tribe/Repositories/Attendee/Commerce.php
  src/Tribe/Repositories/Attendee/RSVP.php
Labels: code review

#1272 Add support selecting field to search in Attendees admin
  composer.lock
  lang/event-tickets.pot
  readme.txt
  src/Tribe/Attendee_Repository.php
  src/Tribe/Attendees_Table.php
  src/Tribe/Repositories/Attendee/Commerce.php
  src/Tribe/Repositories/Attendee/RSVP.php
  src/Tribe/Tickets.php
  src/admin-views/attendees-table-search.php
  tests/wpunit/Tribe/Tickets/Attendees_TableTest.php
Labels: merge

#1273 Fix attendees by order error
  src/Tribe/Commerce/PayPal/Endpoints/Success_Template.php
Labels: code review, merge
