Repository the-events-calendar/event-tickets, pull requests merged in 2019-09, with the labels that each got.

#1334 Fix/119822 qa fail
  readme.txt
  src/Tribe/Commerce/PayPal/Gateway.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Commerce/PayPal/Orders/Sales.php
  src/Tribe/Data_API.php
  src/Tribe/REST/V1/Post_Repository.php
  src/Tribe/Ticket_Object.php
  src/Tribe/Tickets.php
  src/Tribe/Tickets_Handler.php
  src/admin-views/tpp-metabox-capacity.php
  src/admin-views/tribe-options-tickets.php
  src/template-tags/tickets.php
  src/views/blocks/tickets/quantity-number.php
  src/views/tickets/rsvp.php
  src/views/tickets/tpp.php
Labels: merge

#1335 Fix/132248 qa feedback
  readme.txt
  src/Tribe/Attendees_Table.php
  src/Tribe/Commerce/PayPal/Orders/Table.php
  src/admin-views/attendees.php
Labels: merge

#1337 Prevent formulas from being exported when exporting attendees to CSV
  event-tickets.php
  readme.txt
  src/Tribe/Attendees.php
  src/Tribe/Main.php
  tests/_support/Commerce/Attendee_Maker.php
  tests/wpunit/Tribe/Tickets/Attendees_Test.php
Labels: merge

#1339 Fix usage of sanitize_csv_rows in maybe_generate_csv
  event-tickets.php
  readme.txt
  src/Tribe/Attendees.php
  src/Tribe/Main.php
  tests/_support/Commerce/Attendee_Maker.php
  tests/wpunit/Tribe/Tickets/Attendees_Test.php
Labels: code review

#1324 Feature/132279 modal cart
  src/Tribe/Attendee_Registration/Modal.php
  src/Tribe/Attendee_Registration/Service_Provider.php
  src/resources/js/tickets-block.js
  src/views/blocks/tickets/item.php
  src/views/blocks/tickets/submit-button-modal.php
  src/views/blocks/tickets/submit-button.php
  src/views/modal/cart-totals.php
  src/views/modal/cart.php
  src/views/modal/item-remove.php
  src/views/modal/item-total.php
Labels: merge

#1341 Fix cancelled / sold calculation
  src/Tribe/Commerce/PayPal/Main.php
Labels: merge

#1312 Feature/128280 orm filters
  tests/_support/Commerce/ORMTestCase.php
  tests/_support/Commerce/RSVP/Ticket_Maker.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/LinksTest.php
  tests/wpunit/Tribe/Tickets/ORM/Attendees/FilterTest.php
Labels: hold

#1342 Remove extra column.
  .gitignore
  src/Tribe/Attendees_Table.php
  src/resources/postcss/tickets-report.pcss
  tests/wpunit/Tribe/Tickets/Attendees_Test.php
Labels: merge

#1345 change tooltip per ticket
  src/admin-views/tribe-options-tickets.php
Labels: merge

#1344 Feature/133179 currency formatting
  readme.txt
  src/Tribe/Commerce/Currency.php
  src/Tribe/Data_API.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Status/Manager.php
  src/resources/js/tickets-block.js
  src/views/blocks/tickets/extra-price.php
  src/views/blocks/tickets/footer-total.php
  src/views/modal/cart-totals.php
  src/views/modal/cart.php
  src/views/modal/item-total.php
Labels: merge

#1347 Fix/131896 php errors
  readme.txt
  src/views/registration/button-cart.php
  src/views/registration/content.php
Labels: merge

#1352 Add action hooks at beginning and end of AR page
  readme.txt
  src/views/registration/content.php
Labels: merge

#1343 Add new cart REST API endpoint
  .env
  composer.lock
  readme.txt
  src/Tribe/Attendee_Registration/View.php
  src/Tribe/Commerce/Currency.php
  src/Tribe/Commerce/PayPal/Cart/Interface.php
  src/Tribe/Commerce/PayPal/Cart/Unmanaged.php
  src/Tribe/Commerce/PayPal/Gateway.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/REST/V1/Endpoints/Base.php
  src/Tribe/REST/V1/Endpoints/Cart.php
  src/Tribe/REST/V1/Endpoints/Ticket_Archive.php
  src/Tribe/REST/V1/Service_Provider.php
  src/Tribe/Status/Manager.php
  src/Tribe/Ticket_Object.php
  src/resources/js/tickets-block.js
  src/views/blocks/tickets.php
  tests/functional/Commerce/PayPal/ReturnToCartCest.php
  tests/restv1/BaseRestCest.php
  tests/restv1/PayPal/CartCest.php
  tests/restv1/PayPal/CartUpdateCest.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Cart/UnmanagedTest.php
Labels: code review, merge

#1355 Update meta hooks for /cart/ REST API endpoint
  package-lock.json
  package.json
  src/Tribe/REST/V1/Endpoints/Cart.php
  tests/restv1/PayPal/CartUpdateCest.php
Labels: code review, merge

#1358 Fix/128521 attendee link in block without et+
  readme.txt
  src/modules/blocks/rsvp/action-dashboard/template.js
  src/modules/blocks/tickets/action-dashboard/template.js
Labels: merge

#1357 Fix/125496 fix genesis excerpt
  readme.txt
  src/Tribe/Attendee_Registration/Template.php
Labels: merge

#1359 Fix/125021 hide events when no ar
  readme.txt
  src/Tribe/Attendee_Registration/Main.php
  src/views/registration/content.php
  tests/wpunit/Tribe/Tickets/Attendee_RegistrationTest.php
Labels: merge

#1361 Remove post ID from cart endpoint
  src/Tribe/Commerce/PayPal/Gateway.php
  src/Tribe/REST/V1/Endpoints/Cart.php
  src/Tribe/REST/V1/Service_Provider.php
  tests/restv1/BaseRestCest.php
  tests/restv1/PayPal/CartCest.php
  tests/restv1/PayPal/CartUpdateCest.php
Labels: merge

#1351 #134358 - Fixed capitalization
  readme.txt
  src/Tribe/RSVP/Status/Not_Going.php
  tests/wpunit/Tribe/Tickets/Status/RSVPManagerTest.php
Labels: merge

#1362 Fix build issues
  package-whitelist.json
Labels: merge

#1363 #132961 - add check if form submitted to prevent multiple entries fro…
  readme.txt
  src/resources/js/tpp.js
Labels: merge

#1364 Fix url in form and send optout with ticket data.
  src/resources/js/tickets-block.js
  src/views/blocks/tickets.php
Labels: merge

#1365 Support exceptions in cart/meta update, check if ticket exists, check if ticket has capacity, add optout
  src/Tribe/Commerce/PayPal/Cart/Interface.php
  src/Tribe/Commerce/PayPal/Cart/Unmanaged.php
  src/Tribe/Commerce/PayPal/Gateway.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/REST/V1/Endpoints/Cart.php
  src/Tribe/REST/V1/Messages.php
  tests/_support/Commerce/Attendee_Maker.php
  tests/restv1/BaseRestCest.php
  tests/restv1/PayPal/CartCest.php
  tests/restv1/PayPal/CartUpdateCest.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Cart/UnmanagedTest.php
Labels: code review, merge

#1353 Notify promoter when an event is deleted
  readme.txt
  src/Tribe/Promoter/Observer.php
Labels: merge

#1303 Feature/130897 filterable ticket labels
  readme.txt
  src/Tribe/Admin/Move_Ticket_Types.php
  src/Tribe/Admin/Move_Tickets.php
  src/Tribe/Admin/Ticket_Settings.php
  src/Tribe/Assets.php
  src/Tribe/Attendees.php
  src/Tribe/Attendees_Table.php
  src/Tribe/CSV_Importer/Column_Names.php
  src/Tribe/CSV_Importer/Rows.php
  src/Tribe/Commerce/PayPal/Attendance_Totals.php
  src/Tribe/Commerce/PayPal/Errors.php
  src/Tribe/Commerce/PayPal/Frontend/Tickets_Form.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Commerce/PayPal/Oversell/Admin_Notice_Decorator.php
  src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
  src/Tribe/Main.php
  src/Tribe/Metabox.php
  src/Tribe/Plugin_Register.php
  src/Tribe/REST/V1/Documentation/Attendee_Definition_Provider.php
  src/Tribe/REST/V1/Documentation/Capacity_Details_Definition_Provider.php
  src/Tribe/REST/V1/Documentation/Checkin_Details_Definition_Provider.php
  src/Tribe/REST/V1/Documentation/RSVP_Report_Definition_Provider.php
  src/Tribe/RSVP.php
  src/Tribe/RSVP/Attendance_Totals.php
  src/Tribe/Tickets.php
  src/Tribe/Tickets_View.php
  src/admin-views/editor/column-body-price.php
  src/admin-views/editor/fieldset/advanced.php
  src/admin-views/editor/list-table.php
  src/admin-views/editor/panel/settings.php
  src/admin-views/editor/panel/ticket.php
  src/admin-views/privacy.php
  src/admin-views/ticket-type-history.php
  src/admin-views/tribe-options-tickets.php
  src/template-tags/tickets.php
  src/views/blocks/attendees/view-link.php
  src/views/blocks/rsvp/form/error.php
  src/views/blocks/rsvp/form/quantity.php
  src/views/blocks/rsvp/form/submit-button.php
  src/views/blocks/rsvp/icon.php
  src/views/blocks/rsvp/messages/success.php
  src/views/blocks/rsvp/status/full.php
  src/views/blocks/tickets/registration/summary/title.php
  src/views/tickets/orders-pp-tickets.php
  src/views/tickets/orders-rsvp.php
  src/views/tickets/rsvp.php
  src/views/tickets/tpp-success.php
  src/views/tickets/tpp.php
  src/views/tickets/view-link.php
Labels: merge

#1308 Tickets REST - Editor or better sees Attendees Info
  readme.txt
  src/Tribe/REST/V1/Post_Repository.php
  src/Tribe/REST/V1/Ticket_Repository.php
  tests/_support/Commerce/RSVP/Ticket_Maker.php
  tests/restv1/TicketArchivePermissionsCest.php
  tests/restv1/TicketSingularPermissionsCest.php
Labels: merge

#1367 Fix/133179 currency formatting latest
  src/resources/js/tickets-block.js
  src/views/blocks/tickets/footer-total.php
  src/views/modal/item-total.php
Labels: code review, merge

#1368 Feature/130897 more strings
  src/Tribe/Admin/Views/Ticketed.php
  src/Tribe/Main.php
  src/Tribe/REST/V1/Documentation/Capacity_Details_Definition_Provider.php
  src/Tribe/Tickets.php
  src/admin-views/editor/fieldset/price.php
  src/admin-views/editor/list-row.php
  src/admin-views/editor/panel/list.php
  src/admin-views/editor/panel/settings.php
  src/admin-views/editor/panel/ticket.php
  src/admin-views/meta-box.php
  src/admin-views/tribe-options-tickets.php
  src/views/blocks/rsvp/content-inactive.php
  src/views/tickets/email.php
  src/views/tickets/orders.php
  src/views/tickets/rsvp.php
Labels: merge

#1369 Fix intercepting of template to override silence.php used by TEC
  readme.txt
  src/Tribe/Tickets_View.php
Labels: merge

#1372 Additional tweaks for My Tickets / My RSVPs areas
  src/Tribe/Tickets_View.php
Labels: code review, merge

#1373 AR Page styling
  src/Tribe/Attendee_Registration/Modal.php
  src/Tribe/Attendee_Registration/View.php
  src/resources/js/tickets-block.js
  src/resources/js/tickets-registration-page.js
  src/resources/postcss/tickets-registration-page.pcss
  src/resources/postcss/tickets.pcss
  src/resources/postcss/utilities/_all.pcss
  src/views/blocks/tickets.php
  src/views/blocks/tickets/content-title.php
  src/views/blocks/tickets/content.php
  src/views/blocks/tickets/extra-price.php
  src/views/blocks/tickets/extra.php
  src/views/blocks/tickets/footer-total.php
  src/views/blocks/tickets/footer.php
  src/views/blocks/tickets/item.php
  src/views/blocks/tickets/registration/attendee/submit.php
  src/views/blocks/tickets/registration/content.php
  src/views/blocks/tickets/registration/summary/content.php
  src/views/blocks/tickets/registration/summary/title.php
  src/views/blocks/tickets/submit.php
  src/views/modal/item-total.php
  src/views/modal/registration-js.php
  src/views/registration-js/attendees/content.php
  src/views/registration-js/content.php
  src/views/registration-js/mini-cart.php
  src/views/registration/button-cart.php
  src/views/registration/content.php
  src/views/registration/summary/content.php
  src/views/registration/summary/description.php
  src/views/registration/summary/title.php
  tests/restv1/TicketArchiveByCurrencyCest.php
Labels: merge

#1375 Add support for cart REST check; Bypass AR screen redirect if in cart REST
  src/Tribe/Attendee_Registration/Main.php
  src/Tribe/REST/V1/Endpoints/Cart.php
  src/Tribe/Tickets.php
Labels: merge

#1376 update to .env.testing.local
  .gitignore
  tests.md
Labels: merge

#1378 Release/g19.12 readme
  readme.txt
  src/Tribe/Admin/Move_Ticket_Types.php
  src/Tribe/Admin/Move_Tickets.php
  src/Tribe/Admin/Ticket_Settings.php
  src/Tribe/Assets.php
  src/Tribe/Attendee_Registration/Main.php
  src/Tribe/Attendee_Registration/Template.php
  src/Tribe/Commerce/PayPal/Attendance_Totals.php
  src/Tribe/Commerce/PayPal/Errors.php
  src/Tribe/Commerce/PayPal/Frontend/Tickets_Form.php
  src/Tribe/Commerce/PayPal/Oversell/Admin_Notice_Decorator.php
  src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
  src/Tribe/Metabox.php
  src/Tribe/Promoter/Observer.php
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
  src/Tribe/Views/V2/Hooks.php
  src/Tribe/Views/V2/Models/Tickets.php
  src/Tribe/Views/V2/Service_Provider.php
  src/admin-views/privacy.php
  src/admin-views/tribe-options-tickets.php
  src/functions/views/provider.php
  src/resources/js/tpp.js
  src/template-tags/tickets.php
  src/views/blocks/attendees/view-link.php
  src/views/blocks/rsvp/content-inactive.php
  src/views/blocks/rsvp/form/error.php
  src/views/blocks/rsvp/form/quantity.php
  src/views/blocks/rsvp/form/submit-button.php
  src/views/blocks/rsvp/icon.php
  src/views/blocks/rsvp/messages/success.php
  src/views/blocks/rsvp/status/full.php
  src/views/blocks/tickets/registration/summary/title.php
  src/views/registration/content.php
  src/views/tickets/email.php
  src/views/tickets/orders-pp-tickets.php
  src/views/tickets/orders-rsvp.php
  src/views/tickets/orders.php
  src/views/tickets/rsvp.php
  src/views/tickets/tpp-success.php
  src/views/tickets/tpp.php
  src/views/tickets/view-link.php
  src/views/v2/day/event/cost.php
  src/views/v2/list/event/cost.php
  src/views/v2/map/event-cards/event-card/event/actions/cost.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cost.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/cost.php
  src/views/v2/photo/event/cost.php
  src/views/v2/week/grid-body/events-day/event/tooltip/cost.php
  src/views/v2/week/mobile-events/day/event/cost.php
Labels: merge

#1379 G19.12 - Update Filters and View Changes
  readme.txt
Labels: merge

#1380 G19.12 - Update View Version and @Since
  src/views/registration/content.php
Labels: merge
