Repository the-events-calendar/event-tickets, pull requests merged in 2020-10, with the labels that each got.

#1795 Fix the since and version TBD replacements
  src/Tribe/Editor/Blocks/Rsvp.php
  src/Tribe/Events/Attendees_List.php
  src/Tribe/RSVP.php
  src/resources/js/tickets-block.js
  src/resources/js/v2/rsvp-ari.js
  src/resources/js/v2/rsvp-block.js
  src/resources/js/v2/rsvp-manager.js
  src/resources/js/v2/rsvp-tooltip.js
  src/resources/postcss/forms.pcss
  src/resources/postcss/rsvp.pcss
  src/resources/postcss/rsvp/_actions.pcss
  src/resources/postcss/rsvp/_all.pcss
  src/resources/postcss/rsvp/_attendee-registration.pcss
  src/resources/postcss/rsvp/_form.pcss
  src/resources/postcss/rsvp/_rsvp.pcss
  src/views/v2/rsvp-kitchen-sink/form-going.php
  src/views/v2/rsvp-kitchen-sink/form-not-going.php
  src/views/v2/rsvp.php
  src/views/v2/rsvp/actions/success/title.php
  src/views/v2/rsvp/actions/success/toggle.php
  src/views/v2/rsvp/ari.php
  src/views/v2/rsvp/ari/form.php
  src/views/v2/rsvp/ari/form/buttons.php
  src/views/v2/rsvp/ari/form/error.php
  src/views/v2/rsvp/ari/form/fields.php
  src/views/v2/rsvp/ari/form/fields/email.php
  src/views/v2/rsvp/ari/form/fields/meta.php
  src/views/v2/rsvp/ari/form/fields/name.php
  src/views/v2/rsvp/ari/form/guest-template.php
  src/views/v2/rsvp/ari/form/guest.php
  src/views/v2/rsvp/ari/form/template/fields.php
  src/views/v2/rsvp/ari/form/template/title.php
  src/views/v2/rsvp/ari/form/title.php
  src/views/v2/rsvp/ari/sidebar/guest-list.php
  src/views/v2/rsvp/ari/sidebar/guest-list/guest-template.php
  src/views/v2/rsvp/ari/sidebar/guest-list/guest.php
  src/views/v2/rsvp/form/buttons.php
  src/views/v2/rsvp/form/fields/email.php
  src/views/v2/rsvp/form/fields/name.php
  src/views/v2/rsvp/form/fields/quantity.php
  src/views/v2/rsvp/form/form.php
  src/views/v2/rsvp/messages/error.php
  src/views/v2/rsvp/messages/success.php
  src/views/v2/rsvp/messages/success/going.php
  src/views/v2/rsvp/messages/success/not-going.php
Labels: merge

#1799 Update template path for `src/views/tickets/view-link.php`
  src/views/tickets/view-link.php
Labels: merge

#1798 [ETP-455] Tickets views V2 > Componetize loader library.
  src/Tribe/Assets.php
  src/resources/js/v2/rsvp-manager.js
  src/resources/js/v2/tickets-loader.js
Labels: merge

#1787 [ETP-473] Tests/v2 snapshots Part 1
  src/views/v2/tickets/commerce/fields/tribe-commerce.php
  src/views/v2/tickets/footer.php
  src/views/v2/tickets/item.php
  src/views/v2/tickets/item/content.php
  src/views/v2/tickets/item/content/description.php
  src/views/v2/tickets/item/content/inactive.php
  src/views/v2/tickets/item/content/title.php
  src/views/v2/tickets/item/extra.php
  src/views/v2/tickets/item/inactive.php
  src/views/v2/tickets/item/opt-out.php
  src/views/v2/tickets/item/quantity.php
  src/views/v2/tickets/item/quantity/add.php
  src/views/v2/tickets/opt-out/hidden.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Commerce/FieldsTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Commerce/__snapshots__/FieldsTest__test_should_render_input_field_with_provider_class_name__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Footer/QuantityTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Footer/Return_To_Cart_Test.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Footer/TotalTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Footer/__snapshots__/QuantityTest__test_should_render_quantity_block__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Footer/__snapshots__/Return_To_Cart_Test__test_should_not_render_if_cart_and_checkout_url_same__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Footer/__snapshots__/Return_To_Cart_Test__test_should_not_render_if_not_is_mini__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Footer/__snapshots__/Return_To_Cart_Test__test_should_render_if_is_mini_and_different_cart_and_checkout_url__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Footer/__snapshots__/TotalTest__test_should_render_footer_total_block__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/FooterTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/NoticeTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/TitleTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/FooterTest__test_should_not_render_if_not_is_mini_and_empty_ticket_on_sale__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/FooterTest__test_should_render_ar_page_mini_cart_footer_if_is_mini_and_empty_ticket_on_sale__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/FooterTest__test_should_render_ar_page_mini_cart_footer_with_cart_url_if_is_mini_and_has_ticket_on_sale__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/FooterTest__test_should_render_ticket_form_footer_if_not_is_mini_and_has_ticket_on_sale__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/NoticeTest__test_should_render_ticket_form_notice_block__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/TitleTest__test_should_render_tickets_title_field__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/TicketsTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_not_render_if_empty_provider__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_not_render_if_empty_tickets__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_not_render_if_not_is_sale_future__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_regular_tickets_block__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_mini__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_modal__1.php
Labels: merge

#1792 [ETP-473]Tests/v2 snapshots part 2
  src/views/v2/tickets/item.php
  src/views/v2/tickets/item/content/description-toggle.php
  src/views/v2/tickets/item/content/inactive.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/DescriptionTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/Description_ToggleTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/InactiveTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/TitleTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/DescriptionTest__test_should_not_render_if_is_mini__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/DescriptionTest__test_should_not_render_if_ticket_description_is_empty__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/DescriptionTest__test_should_not_render_if_ticket_show_description_is_false__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/DescriptionTest__test_should_render_if_not_is_mini_and_valid_ticket__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/DescriptionTest__test_should_render_only_description_if_is_modal_false__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/Description_ToggleTest__test_should_not_render_if_is_modal_empty__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/Description_ToggleTest__test_should_not_render_if_ticket_description_is_empty__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/Description_ToggleTest__test_should_not_render_if_ticket_show_description_is_false__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/Description_ToggleTest__test_should_render_if_is_modal_and_valid_ticket__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/InactiveTest__test_should_show_not_available_message__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/InactiveTest__test_should_show_ticket_not_yet_available_message__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/TitleTest__test_should_not_show_description_if_is_mini__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/TitleTest__test_should_not_show_description_if_ticket_description_empty__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/TitleTest__test_should_render_title_block__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/ContentTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/__snapshots__/ContentTest__test_should_not_render_if_ticket_is_empty__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/__snapshots__/ContentTest__test_should_render_if_has_ticket_object__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/ItemTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/ItemsTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_not_render_if_empty_provider__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_not_render_if_provider_not_same__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_if_has_provider_and_provider_has_same_class_as_ticket_provider__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemsTest__test_should_not_render_if_empty_tickets_on_sale__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemsTest__test_should_render_if_not_empty_tickets_on_sale__1.php
Labels: merge

#1793 [ETP-473] Tests/v2 snapshots Part 3
  src/views/v2/tickets/item/extra/available.php
  src/views/v2/tickets/item/extra/available/quantity.php
  src/views/v2/tickets/item/extra/available/unlimited.php
  src/views/v2/tickets/item/extra/price.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/QuantityTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/UnlimitedTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/__snapshots__/QuantityTest__test_should_not_render_quantity_block_if_threshold_smaller_than_available_quantity__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/__snapshots__/QuantityTest__test_should_render_quantity_block__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/__snapshots__/QuantityTest__test_should_render_quantity_block_if_threshold_greater_than_available_quantity__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/__snapshots__/UnlimitedTest__test_should_not_render_if_available_quantity_is_not_unlimited__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/__snapshots__/UnlimitedTest__test_should_not_render_if_show_unlimited_is_false__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Available/__snapshots__/UnlimitedTest__test_should_render_unlimited_text__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/AvailableTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/Description_ToggleTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/PriceTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/AvailableTest__test_should_not_render_available_block_if_is_mini__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/AvailableTest__test_should_render_available_block__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/Description_ToggleTest__test_should_not_render_if_is_mini__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/Description_ToggleTest__test_should_not_render_if_is_modal__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/Description_ToggleTest__test_should_not_render_if_ticket_description_is_empty__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/Description_ToggleTest__test_should_not_render_if_ticket_show_description_is_false__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/Description_ToggleTest__test_should_render_if_is_not_modal_or_mini_and_has_description__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/PriceTest__test_should_render_price_block_for_product_on_sale__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/PriceTest__test_should_render_price_block_for_regular_product__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Extra/__snapshots__/PriceTest__test_should_render_price_block_with_price_suffix__1.php
Labels: merge

#1797 ETP-464 new tickets views settings
  src/Tribe/Attendee_Registration/Meta.php
  src/Tribe/Attendee_Registration/Rewrite.php
  src/Tribe/Attendee_Registration/Service_Provider.php
  src/Tribe/Attendee_Registration/Shortcode.php
  src/Tribe/Commerce/PayPal/Gateway.php
  src/Tribe/Tickets.php
  src/admin-views/tribe-options-display.php
  src/template-tags/tickets.php
Labels: bug, code review

#1796 ET-915 correctly detect ticket provider
  readme.txt
  src/Tribe/Attendee_Registration/Meta.php
  src/Tribe/Attendee_Registration/View.php
  src/Tribe/Tickets.php
Labels: merge

#1801 [ETP-460] Add copies of JS for v2 purposes
  src/resources/js/v2/tickets-block.js
Labels: merge

#1803 welcome page refresh
  src/Tribe/Integrations/Freemius.php
  src/Tribe/Main.php
  src/admin-views/admin-welcome-message.php
  src/resources/js/admin/welcome-message.js
Labels: merge

#1806 [ET-919] correct some template override comments
  readme.txt
  src/views/blocks/attendees/title.php
  src/views/blocks/attendees/view-link.php
  src/views/blocks/tickets/registration/summary/ticket-price.php
  src/views/tickets/view-link.php
Labels: code review

#1804 Move AR page JS to ET+ for V2.
  src/Tribe/Assets.php
Labels: merge

#1800 [ETP-460][V2] Tickets block, and tickets utils.
  src/Tribe/Assets.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Tickets.php
  src/resources/js/v2/tickets-block.js
  src/resources/js/v2/tickets-utils.js
  src/views/v2/tickets.php
Labels: code review

#1808 [ET-918] don't escape the title
  src/views/v2/tickets/item/content/title.php
Labels: code review

#1812 [ETP-459] Move modal stylesheet to ET+
  src/resources/postcss/tickets/_all.pcss
  src/resources/postcss/tickets/_block.pcss
  src/resources/postcss/tickets/_modal.pcss
Labels: merge

#1811 [ETP-459] Use ET AR page stylesheet only for V1.
  src/Tribe/Assets.php
Labels: merge

#1816 [ETP-423] Tweaks for IAC meta handling
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/REST/V1/Post_Repository.php
  src/Tribe/RSVP.php
  src/views/tickets/orders.php
Labels: merge

#1813 [ETP-423] Abstract the meta enabled checks
  src/Tribe/Data_API.php
  src/Tribe/Ticket_Object.php
  src/views/blocks/rsvp/form/attendee-meta.php
  src/views/modal/registration-js.php
  src/views/registration-js/attendees/content.php
  src/views/registration-js/content.php
  src/views/registration/attendees/content.php
  src/views/v2/rsvp/ari/form/fields/meta.php
  src/views/v2/rsvp/ari/form/template/fields.php
Labels: merge

#1814 [ETP-459] Update CSS class naming for V2.
  src/resources/js/v2/tickets-block.js
  src/resources/postcss/tickets.pcss
  src/resources/postcss/tickets/_attendee-registration.pcss
  src/resources/postcss/tickets/_block-details.pcss
  src/resources/postcss/tickets/_block-extras.pcss
  src/resources/postcss/tickets/_block-footer.pcss
  src/resources/postcss/tickets/_block-quantity.pcss
  src/resources/postcss/tickets/_block.pcss
  src/views/v2/tickets.php
  src/views/v2/tickets/footer.php
  src/views/v2/tickets/footer/quantity.php
  src/views/v2/tickets/footer/return-to-cart.php
  src/views/v2/tickets/footer/total.php
  src/views/v2/tickets/item.php
  src/views/v2/tickets/item/content/description-toggle.php
  src/views/v2/tickets/item/content/description.php
  src/views/v2/tickets/item/content/inactive.php
  src/views/v2/tickets/item/content/title.php
  src/views/v2/tickets/item/extra.php
  src/views/v2/tickets/item/extra/available.php
  src/views/v2/tickets/item/extra/available/quantity.php
  src/views/v2/tickets/item/extra/description-toggle.php
  src/views/v2/tickets/item/extra/price.php
  src/views/v2/tickets/item/inactive.php
  src/views/v2/tickets/item/opt-out.php
  src/views/v2/tickets/item/quantity.php
  src/views/v2/tickets/item/quantity/add.php
  src/views/v2/tickets/item/quantity/number.php
  src/views/v2/tickets/item/quantity/remove.php
  src/views/v2/tickets/item/quantity/unavailable.php
  src/views/v2/tickets/opt-out/hidden.php
  src/views/v2/tickets/submit/button.php
  src/views/v2/tickets/title.php
Labels: merge

#1823 Tickets V2 Block > Use tickets view logic for rendering.
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Tickets_View.php
Labels: merge

#1825 [ETP-390] Block Editor - Add IAC support to the ticket block and add tests
  src/Tribe/Ticket_Object.php
  src/modules/blocks/rsvp/__tests__/__snapshots__/index.test.js.snap
  src/modules/blocks/ticket/container-content/attendee-collection/container.js
  src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/__tests__/template.test.js
  src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/container.js
  src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/template.js
  src/modules/blocks/ticket/container-content/attendee-collection/style.pcss
  src/modules/blocks/ticket/container-content/attendee-collection/template.js
  src/modules/blocks/ticket/container-content/template.js
  src/modules/blocks/ticket/dashboard/container.js
  src/modules/blocks/tickets/__tests__/__snapshots__/index.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/constants.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/types.test.js.snap
  src/modules/data/blocks/ticket/__tests__/actions.test.js
  src/modules/data/blocks/ticket/__tests__/sagas.test.js
  src/modules/data/blocks/ticket/__tests__/selectors.test.js
  src/modules/data/blocks/ticket/actions.js
  src/modules/data/blocks/ticket/reducer.js
  src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/tickets.test.js.snap
  src/modules/data/blocks/ticket/reducers/tickets.js
  src/modules/data/blocks/ticket/reducers/tickets/__tests__/__snapshots__/ticket.test.js.snap
  src/modules/data/blocks/ticket/reducers/tickets/ticket.js
  src/modules/data/blocks/ticket/reducers/tickets/ticket/__tests__/__snapshots__/details.test.js.snap
  src/modules/data/blocks/ticket/reducers/tickets/ticket/__tests__/__snapshots__/temp-details.test.js.snap
  src/modules/data/blocks/ticket/reducers/tickets/ticket/__tests__/details.test.js
  src/modules/data/blocks/ticket/reducers/tickets/ticket/__tests__/temp-details.test.js
  src/modules/data/blocks/ticket/reducers/tickets/ticket/details.js
  src/modules/data/blocks/ticket/reducers/tickets/ticket/temp-details.js
  src/modules/data/blocks/ticket/sagas.js
  src/modules/data/blocks/ticket/selectors.js
  src/modules/data/blocks/ticket/types.js
Labels: code review

#1819 Revert changed class name to keep compatibility with V1 templates
  src/resources/postcss/tickets-registration-page.pcss
Labels: merge

#1826 [ET-922] Fix specificity on the V1 stylesheet for radios and checkboxes.
  readme.txt
  src/resources/postcss/tickets-v1.pcss
Labels: merge

#1821 [ET-876] Fix double RSVP capacity problem
  readme.txt
  src/template-tags/tickets.php
Labels: merge

#1828 [ET-921] Fix ternary on string concatenation.
  src/views/v2/tickets/item/content/description-toggle.php
  src/views/v2/tickets/item/content/description.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/DescriptionTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/DescriptionTest__test_should_render_if_not_is_mini_and_valid_ticket__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Content/__snapshots__/Description_ToggleTest__test_should_render_if_is_modal_and_valid_ticket__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_modal__1.php
Labels: merge

#1822 [ETP-459] Move attendee tickets CSS to ET+.
  src/Tribe/Assets.php
  src/Tribe/Tickets_View.php
  src/resources/postcss/tickets-forms.pcss
  src/resources/postcss/tickets/_all.pcss
  src/resources/postcss/tickets/_attendee-fields.pcss
Labels: merge

#1820 Send `select` type data over Ajax for saving ticket meta box info
  src/resources/js/tickets.js
Labels: merge

#1830 [ETP-423] My Tickets - Handle IAC attendee edit
  composer.lock
  package-lock.json
  src/Tribe/REST/V1/Flags.php
  src/Tribe/Service_Provider.php
  src/Tribe/Tickets.php
  src/Tribe/Tickets_View.php
  tests/restv1/PayPal/FlagsCest.php
  tests/restv1/RSVP/FlagsCest.php
Labels: merge

#1831 [ETP-395] Add entry point for IAC support
  src/admin-views/attendees.php
Labels: merge

#1833 [ETP-437] Disable resend of emails using filters on attendee email update
  src/views/tickets/orders.php
Labels: merge

#1832 [ETP-436] ET - My Tickets - Show IAC re-send email checkbox
  src/Tribe/Assets.php
  src/Tribe/Tickets_View.php
  src/resources/js/v2/tickets-page.js
  src/views/tickets/orders.php
Labels: merge

#1836 [ETP-551] Updated IAC settings helper text on Block Editor
  src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/template.js
Labels: merge
