Repository the-events-calendar/event-tickets, pull requests merged in 2020-04, with the labels that each got.

#1627 Notice > Early return if there's no content & title, remove "Whoops" parameter.
  readme.txt
  src/views/components/notice.php
  src/views/registration-js/content.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 0__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 1__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 2__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 3__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 4__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 5__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 0__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 10__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 11__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 12__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 13__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 14__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 15__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 16__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 17__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 18__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 19__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 1__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 20__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 21__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 22__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 23__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 24__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 25__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 26__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 27__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 28__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 29__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 2__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 3__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 4__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 5__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 6__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 7__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 8__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 9__1.php
Labels: merge

#1629 Tickets block > handle value when there are empty decimal/separators
  readme.txt
  src/resources/js/tickets-block.js
Labels: merge

#1632 Tickets > Remove "Whoops" from AR modal.
  src/views/modal/registration-js.php
Labels: merge

#1630 ETP-235
  readme.txt
  src/Tribe/Attendee_Repository.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Editor/Blocks/Rsvp.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
Labels: merge

#1628 Tickets > Quantity markup
  readme.txt
  src/resources/postcss/tickets.pcss
  src/views/blocks/tickets/quantity-add.php
  src/views/blocks/tickets/quantity-remove.php
  tests/wpunit/Tribe/Tickets/Partials/Tickets/__snapshots__/QuantityAdd__test_render_quantity__1.php
  tests/wpunit/Tribe/Tickets/Partials/Tickets/__snapshots__/QuantityRemove__test_render_quantity__1.php
  tests/wpunit/Tribe/Tickets/Partials/Tickets/__snapshots__/Quantity__test_should_render_quantity_available__1.php
Labels: code review

#1631 VR > Sold out message for views.
  readme.txt
  src/Tribe/Events/Views/V2/Models/Tickets.php
  src/views/v2/day/event/cost.php
  src/views/v2/list/event/cost.php
  src/views/v2/map/event-cards/event-card/actions/cost.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cost.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/cost.php
  src/views/v2/photo/event/cost.php
  src/views/v2/week/grid-body/events-day/event/tooltip/cost.php
  src/views/v2/week/mobile-events/day/event/cost.php
Labels: merge

#1638 Update dump sql
  tests/_data/dump.sql
Labels: merge

#1641 Updated restv1-dump.sql
  tests/_data/restv1-dump.sql
Labels: merge

#1634 Fix/ct 21 ce form shared cap2
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
  src/Tribe/Tickets_Handler.php
  src/admin-views/editor/button-view-orders.php
  src/admin-views/editor/panel/list.php
  src/template-tags/tickets.php
  tests/wpunit/Tribe/Tickets/GetTotalEventCapacityTest.php
Labels: merge

#1642 load text domain on 'init'
  readme.txt
  src/Tribe/Main.php
Labels: merge

#1643 correct ticket# and consistent quoting
  readme.txt
Labels: merge

#1636 Tickets > Update dependencies to make block work in WP < 5.0
  readme.txt
  src/Tribe/Editor/Blocks/Tickets.php
Labels: merge

#1637 [ETP-292] ar form overrides page content
  readme.txt
  src/Tribe/Attendee_Registration/Shortcode.php
  src/Tribe/Attendee_Registration/Template.php
  src/Tribe/Attendee_Registration/View.php
  src/views/blocks/tickets/footer-total.php
  src/views/blocks/tickets/footer.php
  src/views/registration-js/content.php
  src/views/registration-js/mini-cart.php
  src/views/registration/button-cart.php
  tests/_bootstrap.php
  tests/_support/Testcases/Ticket_Object_TestCase.php
  tests/functional/Tribe/Tickets/Attendee_RegistrationCest.php
  tests/views_integration/_bootstrap.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 0__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 1__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 2__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 3__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 4__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 5__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 0__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 10__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 11__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 12__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 13__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 14__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 15__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 16__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 17__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 18__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 19__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 1__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 20__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 21__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 22__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 23__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 24__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 25__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 26__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 27__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 28__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 29__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 2__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 3__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 4__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 5__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 6__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 7__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 8__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 9__1.php
  tests/wpunit/Tribe/Tickets/Partials/Tickets/__snapshots__/FooterTest__test_should_render__1.php
  tests/wpunit/Tribe/Tickets/Partials/Tickets/__snapshots__/FooterTest__test_should_render_mini__1.php
  tests/wpunit/Tribe/Tickets/Template_Tags/GetPostTotalsTest.php
  tests/wpunit/Tribe/Tickets/Ticket_Object/UTCTest.php
Labels: code review

#1633 EP-234: Hide opt-in if Attendee List is not being shown
  readme.txt
  src/Tribe/Events/Attendees_List.php
  src/Tribe/Events/Service_Provider.php
  src/Tribe/Main.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 0__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 1__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 2__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 3__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 4__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 5__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 0__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 10__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 11__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 12__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 13__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 14__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 15__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 16__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 17__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 18__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 19__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 1__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 20__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 21__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 22__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 23__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 24__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 25__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 26__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 27__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 28__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 29__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 2__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 3__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 4__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 5__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 6__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 7__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 8__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 9__1.php
  tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Content__test_should_render_content__1.php
  tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Content__test_should_render_out_of_stock__1.php
  tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Content__test_should_render_unlimited__1.php
  tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Form__test_should_render_form__1.php
  tests/wpunit/Tribe/Tickets/Partials/Tickets/OptOutHiddenTest.php
Labels: merge

#1635 Task/tec 3187 et bedm
  src/modules/blocks/attendees/container.js
  src/modules/blocks/hoc/with-save-data.js
  src/modules/blocks/rsvp/container.js
  src/modules/blocks/ticket/container.js
  src/modules/blocks/tickets/container.js
  src/modules/blocks/tickets/controls/container.js
Labels: code review, in-qa, needs artifact, needs changelog

#1645 Fix/etp 309 ar shortcode amendments
  src/Tribe/Attendee_Registration/Shortcode.php
  src/resources/postcss/tickets-registration-page.pcss
Labels: merge

#1644 [ET-777] Block/Shortcode Attendees List migration script
  readme.txt
  src/Tribe/Editor/Blocks/Attendees.php
  src/Tribe/Editor/Blocks/Rsvp.php
  src/Tribe/Events/Attendees_List.php
  src/Tribe/Events/Service_Provider.php
  src/Tribe/Migration/Queue.php
  src/Tribe/Migration/Queue_4_12.php
  src/Tribe/Service_Provider.php
  src/Tribe/Tickets_Handler.php
  src/Tribe/Updater.php
  src/views/blocks/rsvp/content.php
  src/views/blocks/rsvp/form.php
  src/views/blocks/rsvp/form/details.php
  src/views/blocks/rsvp/form/form.php
  src/views/blocks/rsvp/form/opt-out.php
  src/views/blocks/tickets/opt-out-hidden.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 0__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 1__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 2__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 3__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 4__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block with data set 5__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 0__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 10__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 11__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 12__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 13__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 14__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 15__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 16__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 17__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 18__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 19__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 1__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 20__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 21__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 22__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 23__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 24__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 25__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 26__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 27__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 28__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 29__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 2__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 3__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 4__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 5__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 6__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 7__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 8__1.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/__snapshots__/TicketsBlockTest__test_should_render_ticket_block_after_update with data set 9__1.php
  tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Content__test_should_render_content__1.php
  tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Content__test_should_render_out_of_stock__1.php
  tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Content__test_should_render_unlimited__1.php
  tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Form__test_should_render_form__1.php
  tests/wpunit/Tribe/Tickets/Partials/Tickets/__snapshots__/OptOutHidden__test_should_render_empty__1.php
  tests/wpunit/Tribe/Tickets/Partials/Tickets/__snapshots__/OptOutHidden__test_should_render_input__1.php
Labels: merge

#1647 [ETP-315] AR > Set margins for the mini cart title.
  src/resources/postcss/tickets-registration-page.pcss
Labels: merge
