Repository the-events-calendar/event-tickets, pull requests merged in 2020-02, with the labels that each got.

#1579 Merge pull request #1579 from moderntribe/fix/ET-614-remove-code
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
Labels: merge

#1580 fix(event date checks): Don't test a post as an event!
  src/Tribe/Ticket_Object.php
Labels: merge

#1575 ET > Fix: Hitting enter change quantities.
  readme.txt
  src/resources/js/tickets-block.js
Labels: code review

#1581 VR > Update docblocks for views
  readme.txt
  src/views/v2/day/event/cost.php
  src/views/v2/list/event/cost.php
  src/views/v2/map/event-cards/event-card/actions/cost.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cost.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/cost.php
  src/views/v2/photo/event/cost.php
  src/views/v2/week/grid-body/events-day/event/tooltip/cost.php
  src/views/v2/week/mobile-events/day/event/cost.php
Labels: merge

#1587 Reset local template vars since render runs twice, fix PHP notices
  composer.lock
  readme.txt
  src/Tribe/Attendee_Registration/Modal.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/views/modal/registration-js.php
Labels: merge

#1588 Resolve potential fatal errors when an object is passed to determine a CSS class where we had expected a string
  readme.txt
  src/Tribe/Attendee_Registration/View.php
  src/views/registration-js/content.php
Labels: merge

#1589 Fix Tribe Commerce PayPal redirects to prevent TEC taking over
  readme.txt
  src/Tribe/Commerce/PayPal/Gateway.php
Labels: merge

#1590 Better detect the post ID to use on normal pages for Tribe Commerce
  readme.txt
  src/Tribe/Tickets.php
Labels: merge

#1592 Add tribe_redirected to one more spot
  src/Tribe/Commerce/PayPal/Gateway.php
Labels: merge

#1591 Release/g20.01.1
  composer.lock
  event-tickets.php
  readme.txt
  src/Tribe/Attendee_Registration/Modal.php
  src/Tribe/Attendee_Registration/View.php
  src/Tribe/Commerce/PayPal/Gateway.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Main.php
  src/Tribe/Tickets.php
  src/views/modal/registration-js.php
  src/views/registration-js/content.php
Labels: hold

#1582 AR Modal > Add theme compatibility for overlaps.
  readme.txt
  src/Tribe/Attendee_Registration/Template.php
  src/Tribe/Main.php
  src/Tribe/Theme_Compatibility.php
Labels: merge

#1594 AR > Fix broken AR page in IE11
  readme.txt
  src/resources/js/tickets-registration-page.js
Labels: code review

#1595 When Classic Editor plugin is activated, prevent ticket availability AJAX errors by temporarily disabling the AJAX requests
  readme.txt
  src/Tribe/Tickets.php
Labels: merge

#1593 ET > Fix common styles dependency
  readme.txt
  src/Tribe/Assets.php
  src/Tribe/Main.php
Labels: code review

#1586 AR > Page > Redirection, template, title.
  readme.txt
  src/Tribe/Attendee_Registration/Main.php
  src/Tribe/Attendee_Registration/Template.php
  src/resources/postcss/tickets-registration-page.pcss
  src/views/registration-js/content.php
Labels: merge

#1597 Prevent The Events Calendar plugin from overriding the Attendee Registration page content when Events Page is set as site home page
  readme.txt
  src/Tribe/Attendee_Registration/Template.php
Labels: merge

#1599 Resolve problems where "View My Tickets" (or RSVPs) page would be blank or not load
  readme.txt
  src/Tribe/Tickets_View.php
Labels: merge

#1598 Use the default `datepickerFormat` value if the option hasn't been set yet when setting up validation rules for the ticket add/edit admin form
  readme.txt
  src/admin-views/editor/fieldset/advanced.php
Labels: merge

#1601 ET > Use common a11y classes
  readme.txt
  src/views/blocks/tickets/content-description.php
  src/views/blocks/tickets/extra.php
  src/views/blocks/tickets/quantity-add.php
  src/views/blocks/tickets/quantity-remove.php
Labels: merge

#1602 Save initial shared capacity value for global stock correctly on first Tribe Commerce ticket so availability shows as expected instead of zero
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Global_Stock.php
  src/Tribe/Tickets_Handler.php
Labels: merge

#1603 Fix JS selector
  src/resources/js/tickets-registration-page.js
Labels: merge
