Repository the-events-calendar/event-tickets, pull requests merged in 2020-12, with the labels that each got.

#1882 Manual Attendees > Add compatibility fix for inputs in admin.
  src/resources/postcss/tickets-forms.pcss
Labels: merge

#1879 [ET-957] Add warning if no commerce provider available
  readme.txt
  src/Tribe/Editor/Warnings.php
Labels: merge

#1870 [ET-648]Tweak/ Show delete confirmation dialogue on delete
  readme.txt
  src/Tribe/Attendees.php
  src/resources/js/tickets-attendees.js
Labels: merge

#1878 [ET-947] Feature/Move recurring warning into ET with new design
  readme.txt
  src/Tribe/Editor/Provider.php
  src/Tribe/Editor/Warnings.php
  src/resources/postcss/tickets-admin.pcss
Labels: merge

#1877 [ET-952] Adjust Sale End time for tickets and RSVPs
  readme.txt
  src/Tribe/Editor/Configuration.php
  src/modules/data/blocks/rsvp/reducers/details.js
  src/modules/data/blocks/rsvp/sagas.js
  src/modules/data/blocks/ticket/reducers/tickets/ticket/details.js
  src/modules/data/blocks/ticket/reducers/tickets/ticket/temp-details.js
Labels: merge

#1873 Tweak/et 949 notice ecp rec tickets
  readme.txt
  src/Tribe/Admin/Notices.php
  src/Tribe/Editor.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Editor/Template/Overwrite.php
Labels: merge

#1876 [ET-953] fix multiple providers
  readme.txt
  src/Tribe/Editor/Configuration.php
  src/Tribe/Metabox.php
  src/admin-views/editor/fieldset/settings-provider.php
Labels: merge

#1880 Feature/ Create attendee API for RSVP
  src/Tribe/Attendee_Repository.php
  src/Tribe/Attendees.php
  src/Tribe/RSVP.php
  src/Tribe/Repositories/Attendee/RSVP.php
Labels: merge

#1883 [ET-955] Remove extraneous "Save and checkout" heading from the registration-js/content.php view
  readme.txt
  src/views/registration-js/content.php
  src/views/registration-js/mini-cart.php
Labels: merge

#1884 [ET-960] Remove support for customClassName in the ET blocks
  readme.txt
  src/modules/blocks/attendees/index.js
  src/modules/blocks/rsvp/index.js
  src/modules/blocks/ticket/index.js
  src/modules/blocks/tickets/index.js
Labels: code review

#1886 open ‘Configure Settings’ in new tab
  readme.txt
  src/admin-views/admin-welcome-message.php
Labels: merge

#1887 add period
  src/modules/blocks/tickets/controls/template.js
Labels: merge

#1889 [ET-947] Changes made as per DQA suggestion
  src/resources/postcss/tickets-admin.pcss
Labels: merge

#1888 [ETP-499] Add action hook to show Add new button for Report page
  src/admin-views/attendees.php
Labels: code review, merge

#1869 [ET-950] Tweak/et 950 advanced options
  readme.txt
  src/admin-views/editor/fieldset/advanced.php
  src/admin-views/editor/panel/ticket.php
  src/resources/postcss/tickets-admin.pcss
Labels: merge

#1890 [ET-957] - Remove brackets from kb link as per DQA
  src/Tribe/Editor/Warnings.php
Labels: merge

#1891 [ET-947] DQA JS Update - Added dependency conditional support for notices
  src/Tribe/Editor/Warnings.php
Labels: merge

#1892 [ETP-588] Loader fix
  readme.txt
  src/views/components/loader.php
  src/views/v2/components/loader/loader.php
  tests/wpunit/Tribe/Tickets/Partials/Tickets/QuantityTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Components/Loader/__snapshots__/LoaderTest__test_should_render_loader__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Components/Loader/__snapshots__/LoaderTest__test_should_render_loader_with_custom_classes__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_regular_tickets_block__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_mini__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_modal__1.php
Labels: code review

#1893 ‘front end’ to ‘frontend’ & move Description under Type
  src/admin-views/editor/panel/ticket.php
Labels: code review

#1896 [ETP-599] ET > Prevent php notices from interacting with tickets not prepared by current commerce provider
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
Labels: merge

#1895 [ETP-541] Manual Attendees > form meta validation
  src/Tribe/Assets.php
Labels: merge

#1897 [ET-950] text change
  src/admin-views/editor/panel/ticket.php
Labels: merge

#1894 [ETP-589] Fixed showing recurring warning on other post types and article link update
  src/Tribe/Editor/Warnings.php
Labels: merge

#1899 [ET-952] Fixed showing 2 years buffer for RSVP block
  src/modules/data/blocks/rsvp/sagas.js
Labels: code review

#1900 [ET-947] Resolve CSS display conflict with Tribe Dependency for Warning notice
  src/resources/postcss/tickets-admin.pcss
Labels: merge

#1901 [ET-599] Fix one more AR page notice appearing
  src/Tribe/Tickets.php
Labels: merge

#1902 [ETP-601] Use jQuery.ready() and prevent potential event conflicts
  readme.txt
  src/resources/js/tickets-registration-page.js
Labels: merge

#1904 Task / v2 customizer update changelog
  readme.txt
Labels: merge

#1907 [ET-947] Fix showing notice on fragment refresh
  src/resources/js/tickets.js
Labels: merge

#1905 [ET-924] Modify Ticket Sent counter to track emails
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
  tests/wpunit/Tribe/Tickets/Email/Email_Test.php
Labels: code review

#1908 [ET-925] Feature/Attendee Activity logger
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
  tests/wpunit/Tribe/Tickets/Email/Email_Test.php
Labels: merge

#1915 Add changelog props
  readme.txt
Labels: code review
