Repository the-events-calendar/event-tickets, pull requests merged in 2020-01, with the labels that each got.

#1526 Fetch checkout at a depth high enough to be able to codesniff | PDTOOLS-67
  .github/workflows/phpcs.yml
Labels: merge

#1525 Properly make filtering for Tickets page for V2
  src/Tribe/Tickets_View.php
Labels: merge

#1524 VR > Map View > Add cost to tooltip
  src/views/v2/map/event-cards/event-card/tooltip/cost.php
Labels: code review, needs changelog

#1528 Use new func to verify tickets are available for current date window | TEC-3033
  readme.txt
  src/template-tags/tickets.php
  src/views/v2/day/event/cost.php
  src/views/v2/list/event/cost.php
  src/views/v2/map/event-cards/event-card/actions/cost.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cost.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/cost.php
  src/views/v2/photo/event/cost.php
  src/views/v2/week/grid-body/events-day/event/tooltip/cost.php
  src/views/v2/week/mobile-events/day/event/cost.php
Labels: merge

#1523 [ETP-51] 138725 work even if post only has RSVPs
  readme.txt
  src/template-tags/tickets.php
  src/views/blocks/tickets.php
Labels: merge

#1527 Fix/et 590 attendees listed vert
  readme.txt
  src/resources/postcss/attendees.pcss
  src/styles/attendees/frontend.pcss
Labels: merge

#1529 ET-587 - add check for classic editor option to load assets with tick…
  readme.txt
  src/Tribe/Tickets_View.php
Labels: merge

#1535 ET-589 close open div
  readme.txt
  src/views/blocks/attendees.php
Labels: code review

#1534 Fix/etp 50 page template
  readme.txt
  src/Tribe/Tickets_View.php
  src/views/tickets/orders.php
Labels: merge

#1543 Fix/etp 51 redo
  readme.txt
  src/template-tags/tickets.php
  src/views/blocks/tickets.php
Labels: merge

#1536 Fix/etp 59 page password protected
  readme.txt
  src/Tribe/Tickets_View.php
Labels: merge

#1544 fix(attendees block): fix div closure
  src/views/blocks/attendees.php
Labels: merge

#1546 Fix/etp 41 woo widget checkout link
  readme.txt
  src/Tribe/Attendee_Registration/Shortcode.php
Labels: merge

#1550 ETP-51: back to #tribe-tickets
  readme.txt
  src/Tribe/Views/V2/Models/Tickets.php
  src/template-tags/tickets.php
  src/views/blocks/tickets.php
Labels: merge

#1531 fix(ticket header image): Allow adding ticket header image on non-event posts.
  readme.txt
  src/modules/data/blocks/rsvp/sagas.js
  src/modules/data/blocks/ticket/sagas.js
Labels: merge

#1548 fix(tickets buy button): Ensure disabled when form total count is 0
  composer.lock
  src/resources/js/tickets-block.js
  src/resources/postcss/tickets.pcss
  src/views/blocks/rsvp/form/quantity-minus.php
  src/views/blocks/rsvp/form/quantity-plus.php
  src/views/blocks/tickets/content-description.php
  src/views/blocks/tickets/extra.php
  src/views/blocks/tickets/quantity-add.php
  src/views/blocks/tickets/quantity-remove.php
  src/views/blocks/tickets/submit-button-modal.php
  src/views/blocks/tickets/submit-button.php
  src/views/modal/item-remove.php
  src/views/modal/registration-js.php
  src/views/tickets/orders.php
  src/views/tickets/tpp.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Frontend/__snapshots__/Tickets_FormTest__test_render_snapshot_with_available_tickets__1.php
Labels: merge

#1537 WooCommerce price suffix
  readme.txt
  src/Tribe/Commerce/Currency.php
Labels: merge

#1552 fix(RSVP stock): Correct front end form when one RSVP becomes sold out.
  readme.txt
  src/views/tickets/rsvp.php
Labels: merge

#1542 feat(no tickets notice): Refine logic for the notice on the "my tickets" page. ETP-612, ETP-46
  readme.txt
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
  src/views/blocks/attendees.php
  src/views/tickets/orders.php
Labels: merge

#1551 fix(global stock): Incorrect global stock on new tickets.
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
Labels: merge

#1554 fix(ticket-block.js): Correct js issues due to eslint fixes.
  composer.lock
  src/resources/js/tickets-block.js
Labels: merge

#1547 ET-596 - Initial removal of frontend-tickets script
  readme.txt
  src/Tribe/Commerce/PayPal/Frontend/Tickets_Form.php
  src/Tribe/Tickets.php
  src/resources/js/frontend-ticket-form.js
  src/resources/js/tickets-block.js
Labels: merge

#1538 Code reformatting
  src/views/blocks/tickets/extra-price.php
  src/views/blocks/tickets/extra.php
  src/views/blocks/tickets/footer-total.php
  src/views/modal/item-total.php
Labels: merge

#1545 Fix/etp 53 thousand as decimal display
  readme.txt
  src/resources/js/tickets-block.js
Labels: merge

#1553 ET-608 formatting as part of QA repair
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Tickets_View.php
Labels: merge

#1555 fix(tickets block js): Ensure we have the post ID. ET-640
  readme.txt
  src/Tribe/Tickets.php
  src/resources/js/tickets-block.js
Labels: merge

#1541 ET-609 fix(get_post_totals): Fix event total calcs.
  .gitignore
  composer.lock
  it_should_get_the_correct_capacity_for_an_unlimited_rsvp
  readme.txt
  src/Tribe/Global_Stock.php
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
  src/Tribe/Tickets_Handler.php
  src/template-tags/tickets.php
  src/views/blocks/tickets/item.php
  tests/_support/Commerce/PayPal/Ticket_Maker.php
  tests/_support/Commerce/RSVP/Ticket_Maker.php
  tests/wpunit/Tribe/Tickets/GetTotalEventCapacityTest.php
  tests/wpunit/Tribe/Tickets/RSVPTest.php
  tests/wpunit/Tribe/Tickets/Template_Tags/GetEventCapacityTest.php
  tests/wpunit/Tribe/Tickets/Template_Tags/GetPostTotalsTest.php
  tests/wpunit/Tribe/Tickets/Template_Tags/GlobalStockTest.php
  tests/wpunit/Tribe/Tickets/Template_TagsTest.php
  tests/wpunit/Tribe/Tickets/Ticket_ObjectTest.php
Labels: merge

#1557 fix(modal background): Override the modal background in ET
  src/resources/postcss/tickets.pcss
Labels: merge

#1558 feat(ticket price): Show original price on ticket block if ticket is on sale.
  readme.txt
  src/resources/postcss/tickets-registration-page.pcss
  src/resources/postcss/tickets.pcss
  src/styles/tickets/frontend.pcss
  src/views/blocks/tickets/extra-price.php
Labels: merge

#1540 ET-619 - IE11 fixes
  readme.txt
  src/resources/js/tickets-block.js
  src/resources/postcss/tickets.pcss
  src/views/blocks/tickets/quantity-add.php
  src/views/blocks/tickets/quantity-remove.php
Labels: merge

#1556 refactor(ticket opt-out): Centralize the messaging for the opt out ch…
  readme.txt
  src/Tribe/Editor.php
  src/Tribe/Privacy.php
  src/Tribe/REST/V1/Post_Repository.php
  src/modules/blocks/tickets/settings-dashboard/template.js
  src/views/blocks/rsvp/form/opt-out.php
  src/views/blocks/tickets/extra-available.php
  src/views/tickets/rsvp.php
Labels: merge

#1561 Move Woo-specific to ET+
  readme.txt
  src/Tribe/Commerce/Currency.php
Labels: merge

#1559 Correct reference error in tickets-block.js
  composer.lock
  src/resources/js/tickets-block.js
  src/views/registration-js/attendees/ticket.php
Labels: merge

#1563 fix(optout logic): Correct the logic for hiding the optout.
  composer.lock
  src/views/blocks/rsvp/form/opt-out.php
  src/views/blocks/tickets/opt-out-hidden.php
Labels: merge

#1560 Manually cherry pick code introduced on #1548.
  composer.lock
  package-lock.json
  src/Tribe/Commerce/PayPal/Frontend/Tickets_Form.php
  src/Tribe/Tickets.php
  src/Tribe/Tickets_View.php
  src/resources/js/frontend-ticket-form.js
  src/resources/js/tickets-block.js
  src/resources/postcss/tickets.pcss
  src/views/blocks/rsvp/form/quantity-minus.php
  src/views/blocks/rsvp/form/quantity-plus.php
  src/views/blocks/tickets/content-description.php
  src/views/blocks/tickets/extra.php
  src/views/blocks/tickets/quantity-add.php
  src/views/blocks/tickets/quantity-remove.php
  src/views/blocks/tickets/submit-button-modal.php
  src/views/blocks/tickets/submit-button.php
  src/views/modal/item-remove.php
  src/views/modal/registration-js.php
  src/views/tickets/orders.php
  src/views/tickets/tpp.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Frontend/__snapshots__/Tickets_FormTest__test_render_snapshot_with_available_tickets__1.php
Labels: code review

#1564 fix(sale calcs): Fix calculations with sale prices.
  src/resources/js/tickets-block.js
  src/resources/js/tickets-registration-page.js
  src/views/blocks/tickets/extra-price.php
Labels: merge

#1566 Just changed the requirement back to the current version.
  src/Tribe/Plugin_Register.php
Labels: merge

#1568 Sort properties and minify svg's.
  src/resources/icons/freemius-logo.svg
  src/resources/icons/mailplane.svg
  src/resources/icons/megaphone.svg
  src/resources/icons/plug.svg
  src/resources/icons/settings.svg
  src/resources/icons/stethoscope.svg
  src/resources/icons/user.svg
  src/resources/postcss/freemius.pcss
Labels: merge

#1565 Correct some logic around empty start/end dates
  readme.txt
  src/Tribe/Ticket_Object.php
Labels: merge

#1573 merge 20.01 into 20.01.1
  composer.lock
  event-tickets.php
  lang/event-tickets.pot
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Commerce/PayPal/Frontend/Tickets_Form.php
  src/Tribe/Events/Views/V2/Hooks.php
  src/Tribe/Main.php
  src/Tribe/Plugin_Register.php
  src/Tribe/Tickets.php
  src/Tribe/Tickets_View.php
  src/resources/js/frontend-ticket-form.js
  src/resources/js/tickets-block.js
  src/resources/postcss/tickets.pcss
  src/template-tags/tickets.php
  src/views/blocks/rsvp/form/quantity-minus.php
  src/views/blocks/rsvp/form/quantity-plus.php
  src/views/blocks/tickets/content-description.php
  src/views/blocks/tickets/extra.php
  src/views/blocks/tickets/quantity-add.php
  src/views/blocks/tickets/quantity-remove.php
  src/views/blocks/tickets/submit-button-modal.php
  src/views/blocks/tickets/submit-button.php
  src/views/modal/item-remove.php
  src/views/modal/registration-js.php
  src/views/tickets/orders.php
  src/views/tickets/tpp.php
  src/views/v2/day/event/cost.php
  src/views/v2/list/event/cost.php
  src/views/v2/map/event-cards/event-card/actions/cost.php
  src/views/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/cost.php
  src/views/v2/month/mobile-events/mobile-day/mobile-event/cost.php
  src/views/v2/photo/event/cost.php
  src/views/v2/week/grid-body/events-day/event/tooltip/cost.php
  src/views/v2/week/mobile-events/day/event/cost.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Frontend/__snapshots__/Tickets_FormTest__test_render_snapshot_with_available_tickets__1.php
Labels: code review

#1572 back out
  readme.txt
  src/Tribe/Commerce/Currency.php
Labels: merge

#1567 fix(global stock): Ensure we update the event when we add our first global stock ticket.
  package-lock.json
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Data_API.php
  src/views/blocks/tickets/opt-out-hidden.php
Labels: merge

#1569 additional strings and changelog
  readme.txt
  src/Tribe/Status/Abstract_Commerce.php
  src/admin-views/attendees.php
  src/admin-views/editor/fieldset/advanced.php
  src/admin-views/editor/fieldset/settings-provider.php
  src/admin-views/editor/panel/list.php
  src/admin-views/editor/panel/settings.php
  src/admin-views/editor/panel/ticket.php
  src/admin-views/meta-box.php
  src/admin-views/privacy.php
  src/admin-views/ticket-type-history.php
  src/admin-views/tpp-metabox-sku.php
  src/admin-views/tpp-orders.php
  src/admin-views/tribe-options-tickets.php
  src/views/blocks/attendees/description.php
  src/views/blocks/rsvp/form/error.php
  src/views/blocks/rsvp/form/submit-button.php
  src/views/blocks/rsvp/messages/success.php
  src/views/blocks/tickets/registration/summary/title.php
  src/views/tickets/email.php
  src/views/tickets/orders-pp-tickets.php
  src/views/tickets/orders-rsvp.php
  src/views/tickets/rsvp.php
Labels: merge

#1577 ET-604 - disable rsvp form when password protect is enabled on posts …
  readme.txt
  src/Tribe/RSVP.php
Labels: merge

#1578 fix(buy button): Tickets block buy button style overridden by theme.
  readme.txt
  src/resources/postcss/components/_all.pcss
  src/resources/postcss/components/buttons/_link.pcss
  src/resources/postcss/components/buttons/_small.pcss
  src/resources/postcss/tickets.pcss
Labels: merge
