Repository the-events-calendar/event-tickets, pull requests merged in 2021-07, with the labels that each got.

#2037 [ET-1145] Feature/et 1145 add export button attendees title
  readme.txt
  src/Tribe/Attendees.php
  src/Tribe/Attendees_Table.php
  src/admin-views/attendees.php
Labels: code review

#2034 Tweak/etp 702 hide edit column on print
  readme.txt
  src/resources/js/tickets-attendees.js
  src/resources/postcss/tickets-report-print.pcss
Labels: code review, enhance

#2038 [ET-1107] Add delete functionality for the tickets area in the classic editor.
  readme.txt
  src/admin-views/editor/list-row.php
  src/resources/postcss/tickets-tables.pcss
Labels: code review

#2031 [ETP-655]email rename purchaser to attendee
  readme.txt
  src/views/tickets/email.php
Labels: code review, merge

#2042 [ET-1107] Remove in classic editor > Update width.
  src/resources/postcss/tickets-tables.pcss
Labels: code review

#2043 Added a new action for `tribe_tabbed_view_heading_after_text_label`. …
  src/Tribe/Attendees.php
Labels: code review

#2045 RadioControl needs to be type='radio' shockingly... not type='text'
  src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/template.js
Labels: code review

#2044 [Tests] exclude acceptance until we have nvm running, to avoid problems with tric.
  .github/workflows/tests-php.yml
Labels: code review
