Repository the-events-calendar/event-tickets, pull requests merged in 2021-02, with the labels that each got.

#1935 Reset box-shadow for checkboxes and radios on tickets forms.
  src/resources/postcss/tickets-forms.pcss
Labels: merge

#1934 [ET-999] Add is_ticket_cache_enabled() method that allows turning off ticket object cache and fix in stock cache storage
  src/Tribe/Ticket_Object.php
Labels: merge

#1936 [ETP-490] [ETP-522] [ETP-509] [ETP-485] Handle email send / resend functionality for Attendees ORM
  src/Tribe/Attendee_Repository.php
  src/Tribe/Tickets.php
Labels: code review, merge

#1938 [ET-926] ET > Handle email resend limitations for spam prevention
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
  src/Tribe/Tickets_Handler.php
  src/views/tickets/orders.php
Labels: merge

#1939 [ETP-640] Update sales/stock for RSVPs
  src/Tribe/Attendee_Repository.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/RSVP.php
  src/Tribe/Repositories/Attendee/Commerce.php
  src/Tribe/Repositories/Attendee/RSVP.php
  src/Tribe/Tickets.php
Labels: merge

#1932 Adding execution of tests using GH Workflow
  .github/workflows/tests-php.yml
Labels: merge

#1943 Fix wpunit tests.
  tests/wpunit/Tribe/Tickets/RSVPTest.php
  tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set opt-in__1.php
  tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set success__1.php
Labels: merge

#1942 Fix integration tests - Turn cache off for inventory tests.
  tests/integration/RSVP_Tickets_Test.php
Labels: merge

#1944 Remove `codecept_debug` from test
  tests/integration/RSVP_Tickets_Test.php
Labels: code review

#1946 [ETP-487] [ETP-517] Add function to get active providers for a post
  src/Tribe/Assets.php
  src/Tribe/Tickets.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_regular_tickets_block__1.php
  tests/wpunit/Tribe/Tickets/TicketsTest.php
Labels: code review

#1950 [ET-1022] Highlight ticketed/unticketed filters when current.
  readme.txt
  src/Tribe/Admin/Views/Ticketed.php
Labels: merge

#1949 [ETP-360] Prevent the AR page from using the title from draft pages.
  readme.txt
  src/Tribe/Attendee_Registration/Main.php
Labels: merge

#1951 Add Columns for Ticket Holder Name and Email for CSV export
  readme.txt
  src/Tribe/Attendees.php
  tests/wpunit/Tribe/Tickets/Attendees_Test.php
Labels: merge

#1952 Inverted SQL quotes for MySQL 8.0 compatiblity
  readme.txt
  src/Tribe/Attendee_Repository.php
  src/Tribe/Repositories/Traits/Post_Attendees.php
Labels: merge

#1956 [ETP-516] Show modal if no ar tickets in cart, or submit.
  src/resources/js/v2/tickets-block.js
  src/views/v2/tickets/item.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/ItemTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_wit_whatever_data_attribute__1.php
Labels: merge

#1955 [ETP-639] Set local vars for ticket template to fix showing same ticket for all posts within Query loop
  readme.txt
  src/Tribe/Tickets_View.php
Labels: merge
