Repository the-events-calendar/event-tickets, pull requests merged in 2021-11, with the labels that each got.

#2174 Added tests for `is_active` schema
  tests/wpunit/Tribe/Tickets/ORM/Tickets/SchemaTest.php
Labels: code review

#2160 Feature/et 1254 cart tests
  src/Tickets/Commerce/Cart.php
  src/Tickets/Commerce/Cart/Unmanaged_Cart.php
  tests/wpunit/Tickets/Commerce/Cart/Unmanaged_CartTest.php
  tests/wpunit/Tickets/Commerce/CartTest.php
Labels: merge

#2126 [ETP-703] Cancelled Tickets checkbox not hiding from manual attendee editing
  readme.txt
  src/Tribe/Tickets.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render__1.php
Labels: code review

#2177 TC Update Paypal Link on Setup
  src/admin-views/admin-welcome-message.php
Labels: merge

#2176 [ET-1240] Modify TribeCommerce legacy notice logic.
  src/Tribe/Admin/Settings/Service_Provider.php
Labels: merge

#2180 Setup -> Set Up in Settings CTA
  src/admin-views/admin-welcome-message.php
Labels: merge

#2179 Flush transients whens saving plugin options
  src/Tickets/Commerce/Gateways/PayPal/Hooks.php
  src/Tickets/Commerce/Gateways/PayPal/Signup.php
Labels: merge

#2181 [ET-1240] fix grammar
  src/Tribe/Admin/Settings/Service_Provider.php
Labels: code review

#2184 Include the assets via a hook into the shortcode template with print …
  src/Tickets/Commerce/Gateways/PayPal/Assets.php
  src/Tickets/Commerce/Hooks.php
  src/Tickets/Commerce/Shortcodes/Checkout_Shortcode.php
Labels: code review

#2183 TC > Checkout > Set width for the checkout columns.
  src/resources/postcss/tickets-commerce/_checkout.pcss
Labels: merge

#2185 [ET-1240] Add button and link
  src/Tribe/Admin/Settings/Service_Provider.php
Labels: code review

#2187 Spotfix/et 1269 assets flash
  src/Tickets/Commerce/Assets.php
  src/Tickets/Commerce/Gateways/PayPal/Assets.php
Labels: code review

#2188 ET-1267 - Fix banner text to 'Get started'
  src/Tribe/Admin/Settings/Service_Provider.php
Labels: merge

#2189 Move duplicated pending orders to Not Completed once one of them is Completed
  src/Tickets/Commerce/Flag_Actions/End_Duplicated_Pending_Orders.php
  src/Tickets/Commerce/Flag_Actions/Flag_Action_Handler.php
  src/Tickets/Commerce/Models/Order_Model.php
  src/Tickets/Commerce/Status/Completed.php
Labels: code review

#2190 workaround for empty emails_in_order when sending emails from a manua…
  src/Tickets/Commerce/Flag_Actions/Send_Email.php
Labels: code review

#2193 Remove the version checking piece of Tribe Commerce
  src/functions/commerce/provider.php
Labels: code review

#2194 avoid JS errors on default `obj.showNotice` calls
  src/resources/js/commerce/gateway/paypal/checkout.js
Labels: code review

#2195 [ET-1316] revert PHP 5.6 incompatible codes
  src/Tickets/Commerce/Admin_Tables/Attendees.php
  src/Tickets/Commerce/Reports/Attendees.php
Labels: code review

#2196 Make sure we never pass payee email, merchant ID is enough
  src/Tickets/Commerce/Gateways/PayPal/Client.php
Labels: merge

#2191 Prevent fatals on Checkout shortcode in the wrong page
  src/Tickets/Commerce/Cart.php
Labels: code review

#2197 make sure emails are only sent after all processing is done, when in …
  src/Tickets/Commerce/Flag_Actions/Send_Email.php
Labels: merge

#2198 Updates on readme. Move entries to changelog.txt
  changelog.txt
  readme.txt
Labels: merge

#2199 [ET-1314] TC > Success shortcode block editor
  src/Tickets/Commerce/Shortcodes/Success_Shortcode.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render__0.snapshot.html
Labels: code review

#2202 [ET-1320] fixes fatal error being caused in attendee repo
  readme.txt
  src/Tribe/Attendee_Repository.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/InactiveTest.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render__0.snapshot.html
Labels: code review

#2205 [ET-1321] TC > Admin > modal after connecting to paypal
  readme.txt
  src/Tribe/Assets.php
  src/admin-views/settings/tickets-commerce/paypal/main.php
  src/admin-views/settings/tickets-commerce/paypal/modal/signup-complete.php
  src/admin-views/settings/tickets-commerce/paypal/modal/signup-complete/content.php
  src/admin-views/settings/tickets-commerce/paypal/modal/signup-complete/notice-test-mode.php
  src/resources/js/admin/tickets-commerce-settings.js
  src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss
Labels: merge

#2206 implement archiving attendees
  src/Tickets/Commerce/Attendee.php
  src/Tickets/Commerce/Flag_Actions/Archive_Attendees.php
  src/Tickets/Commerce/Models/Attendee_Model.php
  src/Tickets/Commerce/Models/Order_Model.php
  src/Tickets/Commerce/Repositories/Attendees_Repository.php
  src/Tribe/Tickets_View.php
Labels: merge

#2208 update version numbers
  src/Tribe/Main.php
Labels: code review, merge

#2203 [ET-1232] Auto generate TicketsCommerce Checkout and Order Success page.
  readme.txt
  src/Tickets/Commerce/Payments_Tab.php
  src/Tickets/Hooks.php
Labels: code review

#2209 ET-1318 - issues when selecting countries
  readme.txt
  src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss
Labels: code review, merge

#2210 Fix operations with non-US currencies and formats
  readme.txt
  src/Tickets/Commerce/Currency.php
  src/Tickets/Commerce/Legacy_Compat.php
  src/Tickets/Commerce/Order.php
  src/Tickets/Commerce/Utils/Price.php
  tests/unit/Tribe/Tickets/Commerce/Utils/PriceTest.php
Labels: code review, in-qa

#2211 Tickets Commerce should not interact with Tribe Commerce
  src/Tickets/Commerce/Legacy_Compat.php
  src/Tickets/Commerce/Utils/Price.php
Labels: code review
