Repository the-events-calendar/event-tickets, pull requests merged in 2021-06, with the labels that each got.

#2016 Prevent events being listed as Free on the day of the event
  readme.txt
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
Labels: code review

#2017 Make sure we revert to false by default for excluding
  readme.txt
  src/Tribe/Tickets.php
Labels: code review

#2028 [ETP-725] Using callback for asset data to allow filtering.
  readme.txt
  src/Tribe/Assets.php
Labels: merge

#2027 Fix/etp 111 hook not passing ticket
  changelog.txt
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
Labels: merge

#2024 [ET-1135] - Add support for HTML in ticket description.
  readme.txt
  src/Tribe/Tickets.php
Labels: code review, merge

#2025 Fix/et 1134 email from displays encoded html entities
  changelog.txt
  readme.txt
  src/Tribe/Tickets.php
Labels: code review, merge

#2021 [ETP-730] special characters not exporting
  changelog.txt
Labels: code review

#2030 [ET-1143] Update wp org screenshots.
  readme.txt
Labels: code review
