Repository the-events-calendar/event-tickets, pull requests merged in 2021-03, with the labels that each got.

#1945 Fix acceptance tests on GHA
  .github/workflows/tests-php.yml
  composer.json
  tests/_data/dump-acceptance.sql
Labels: merge

#1958 Remove TravisCI
  .travis.yml
  package.json
  tests.md
Labels: code review, merge

#1961 [ET-1042] Disable creating users by default for new attendees
  readme.txt
  src/Tribe/Tickets.php
Labels: merge

#1960 Fix JS tests
  src/modules/blocks/rsvp/__tests__/__snapshots__/index.test.js.snap
  src/modules/blocks/ticket/__tests__/__snapshots__/index.test.js.snap
  src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/__tests__/template.test.js
  src/modules/blocks/tickets/__tests__/__snapshots__/index.test.js.snap
  src/modules/blocks/tickets/availability/__tests__/__snapshots__/template.test.js.snap
  src/modules/data/blocks/rsvp/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/rsvp/__tests__/__snapshots__/sagas.test.js.snap
  src/modules/data/blocks/rsvp/__tests__/sagas.test.js
  src/modules/data/blocks/rsvp/reducers/__tests__/__snapshots__/details.test.js.snap
  src/modules/data/blocks/rsvp/reducers/__tests__/__snapshots__/temp-details.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/constants.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/sagas.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/types.test.js.snap
  src/modules/data/blocks/ticket/__tests__/sagas.test.js
  src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/tickets.test.js.snap
  src/modules/data/blocks/ticket/reducers/tickets/__tests__/__snapshots__/ticket.test.js.snap
  src/modules/data/blocks/ticket/reducers/tickets/ticket/__tests__/__snapshots__/details.test.js.snap
  src/modules/data/blocks/ticket/reducers/tickets/ticket/__tests__/__snapshots__/temp-details.test.js.snap
Labels: merge

#1962 Fix ET vimeo video URL for WP.org
  readme.txt
Labels: merge

#1959 Add JS tests on GH Actions.
  .github/workflows/tests-js.yml
  src/modules/blocks/rsvp/__tests__/__snapshots__/index.test.js.snap
  src/modules/blocks/ticket/__tests__/__snapshots__/index.test.js.snap
  src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/__tests__/template.test.js
  src/modules/blocks/tickets/__tests__/__snapshots__/index.test.js.snap
  src/modules/blocks/tickets/availability/__tests__/__snapshots__/template.test.js.snap
  src/modules/data/blocks/rsvp/__tests__/__snapshots__/reducer.test.js.snap
  src/modules/data/blocks/rsvp/__tests__/__snapshots__/sagas.test.js.snap
  src/modules/data/blocks/rsvp/__tests__/sagas.test.js
  src/modules/data/blocks/rsvp/reducers/__tests__/__snapshots__/details.test.js.snap
  src/modules/data/blocks/rsvp/reducers/__tests__/__snapshots__/temp-details.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/actions.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/constants.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/sagas.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/types.test.js.snap
  src/modules/data/blocks/ticket/__tests__/sagas.test.js
  src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/tickets.test.js.snap
  src/modules/data/blocks/ticket/reducers/tickets/__tests__/__snapshots__/ticket.test.js.snap
  src/modules/data/blocks/ticket/reducers/tickets/ticket/__tests__/__snapshots__/details.test.js.snap
  src/modules/data/blocks/ticket/reducers/tickets/ticket/__tests__/__snapshots__/temp-details.test.js.snap
Labels: merge

#1965 [ET-982] PHP cleanup for blocks editor code.
  src/Tribe/Editor/Assets.php
  src/Tribe/Editor/Attendee_Registration.php
  src/Tribe/Editor/Blocks/Attendees.php
  src/Tribe/Editor/Blocks/Rsvp.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Editor/Blocks/Tickets_Item.php
  src/Tribe/Editor/Compatibility/Tickets.php
  src/Tribe/Editor/Configuration.php
  src/Tribe/Editor/Meta.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Editor/REST/Compatibility.php
  src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
  src/Tribe/Editor/Template.php
Labels: code review

#1964 [ET-982] Aesthetic updates for blocks.
  readme.txt
  src/Tribe/Editor/Assets.php
  src/Tribe/Editor/Attendee_Registration.php
  src/Tribe/Editor/Blocks/Attendees.php
  src/Tribe/Editor/Blocks/Rsvp.php
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Editor/Blocks/Tickets_Item.php
  src/Tribe/Editor/Compatibility/Tickets.php
  src/Tribe/Editor/Configuration.php
  src/Tribe/Editor/Meta.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Editor/REST/Compatibility.php
  src/Tribe/Editor/REST/V1/Endpoints/Single_Ticket.php
  src/Tribe/Editor/Template.php
  src/modules/blocks/rsvp/container-header/style.pcss
  src/modules/blocks/rsvp/container/style.pcss
  src/modules/blocks/rsvp/style.pcss
  src/modules/blocks/ticket/style.pcss
  src/modules/blocks/tickets/availability/style.pcss
  src/modules/blocks/tickets/container/style.pcss
  src/modules/blocks/tickets/style.pcss
  src/modules/elements/action-button/style.pcss
  src/modules/elements/action-dashboard/style.pcss
  src/modules/elements/date-time-range-picker/style.pcss
  src/modules/elements/inactive-block/style.pcss
  src/modules/elements/settings-dashboard/style.pcss
  src/resources/postcss/attendees.pcss
Labels: merge

#1966 [ET-951] Move duration field out of advanced section on ET blocks
  readme.txt
  src/modules/blocks/rsvp/advanced-options/template.js
  src/modules/blocks/rsvp/container-content/container.js
  src/modules/blocks/rsvp/container-content/template.js
  src/modules/blocks/rsvp/duration/style.pcss
  src/modules/blocks/rsvp/move-delete/__tests__/__snapshots__/template.test.js.snap
  src/modules/blocks/rsvp/move-delete/__tests__/template.test.js
  src/modules/blocks/rsvp/move-delete/container.js
  src/modules/blocks/rsvp/move-delete/style.pcss
  src/modules/blocks/rsvp/move-delete/template.js
  src/modules/blocks/ticket/container-content/advanced-options/template.js
  src/modules/blocks/ticket/container-content/duration/__tests__/__snapshots__/template.test.js.snap
  src/modules/blocks/ticket/container-content/duration/__tests__/template.test.js
  src/modules/blocks/ticket/container-content/duration/container.js
  src/modules/blocks/ticket/container-content/duration/style.pcss
  src/modules/blocks/ticket/container-content/duration/template.js
  src/modules/blocks/ticket/container-content/style.pcss
  src/modules/blocks/ticket/container-content/template.js
Labels: merge

#1968 [GH]Add initial PR template.
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: code review

#1969 [ET-1043] Fixed showing notices for localize script on attendee list page
  readme.txt
  src/Tribe/Attendees.php
  src/resources/js/tickets-attendees.js
Labels: merge

#1971 [ET-981] Add confirmation dialog for bulk deletion of attendees.
  readme.txt
  src/Tribe/Attendees.php
  src/admin-views/attendees.php
  src/resources/js/tickets-attendees.js
Labels: merge

#1974 Added filter on ORM update for future enhancements.
  src/Tribe/Attendee_Repository.php
Labels: merge

#1963 [ET-985] Hide view orders button from RSVP only events
  readme.txt
  src/admin-views/editor/button-view-orders.php
Labels: merge

#1972 [ET-959] Add help banner for Ticket Settings tab.
  readme.txt
  src/Tribe/Admin/Settings/Service_Provider.php
  src/Tribe/Assets.php
  src/Tribe/Main.php
  src/admin-views/settings/getting-started.php
  src/resources/postcss/tickets-admin-settings.pcss
Labels: merge

#1976 [ETP-684] add border
  readme.txt
  src/resources/postcss/tickets-admin.pcss
Labels: merge

#1978 [ET-959] Adjusted banner content area
  src/resources/postcss/tickets-admin-settings.pcss
Labels: merge
