Repository the-events-calendar/event-tickets, pull requests merged in 2021-09, with the labels that each got.

#2071 Skip running PHP tests if no PHP
  .github/workflows/tests-php.yml
Labels: merge

#2072 [ET-1155] Sharedcap test fix
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Stock/SharedCapacityTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/ItemTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_if_has_provider_and_provider_has_same_class_as_ticket_provider__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_wit_whatever_data_attribute__1.php
Labels: code review, merge

#2077 [ET-1174] cast price attribute data to string
  changelog.txt
  readme.txt
  src/views/v2/tickets/item.php
Labels: code review

#2068 [ET-1064] Display TC pages with post status
  src/Tickets/Commerce/Checkout.php
  src/Tickets/Commerce/Hooks.php
  src/Tickets/Commerce/Success.php
  src/views/v2/commerce/checkout/must-login/registration.php
Labels: merge

#2080 [ET-1174] version updated for template
  src/views/v2/tickets/item.php
Labels: code review, merge

#2082 Unmanaged cart cannot be additive.
  src/Tickets/Commerce/Cart.php
  src/Tickets/Commerce/Cart/Cart_Interface.php
  src/Tickets/Commerce/Cart/Unmanaged_Cart.php
Labels: code review

#2075 [ET-1064] Revamp and re-structure TC settings.
  src/Tickets/Commerce/Gateways/Manager.php
  src/Tickets/Commerce/Gateways/PayPal/Settings.php
  src/Tickets/Commerce/Gateways/PayPal/Signup.php
  src/Tickets/Commerce/Settings.php
  src/admin-views/payments/tickets-commerce.php
  src/admin-views/settings/tickets-commerce/paypal-commerce/connect-with-paypal.php
  src/admin-views/settings/tickets-commerce/paypal-commerce/connect-with-paypal/errors.php
  src/admin-views/settings/tickets-commerce/paypal-commerce/introduction.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/connection.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/paypal-status.php
  src/admin-views/settings/tickets-commerce/paypal/connect/inactive.php
  src/admin-views/settings/tickets-commerce/paypal/connect/logo.php
  src/admin-views/settings/tickets-commerce/paypal/connect/logo/features.php
  src/admin-views/settings/tickets-commerce/paypal/connect/logo/image.php
  src/admin-views/settings/tickets-commerce/paypal/main.php
  src/admin-views/settings/tickets-commerce/paypal/signup-link.php
  src/resources/images/admin/paypal-logo.svg
  src/resources/postcss/tickets-admin-settings.pcss
  src/resources/postcss/tickets-admin/settings/_all.pcss
  src/resources/postcss/tickets-admin/settings/_banners.pcss
  src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss
  tests/_support/Partials/V2AdminTestCase.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/ActiveTest.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/InactiveTest.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/LogoTest.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/ActiveTest__test_should_render__1.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/ActiveTest__test_should_render_empty__1.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render__1.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render_empty__1.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/LogoTest__test_should_render__1.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/LogoTest__test_should_render_without_list__1.php
Labels: code review

#2081 [ET-1197] Fix price formatting for ticket totals
  readme.txt
  src/resources/js/v2/tickets-block.js
  src/resources/js/v2/tickets-utils.js
Labels: question, code review

#2085 [ET-1089] enable multiline input for ticket rsvp titles in block editor
  readme.txt
  src/modules/blocks/rsvp/container-header/style.pcss
  src/modules/blocks/rsvp/container-header/template.js
  src/modules/blocks/ticket/container-header/title/style.pcss
  src/modules/blocks/ticket/container-header/title/template.js
Labels: merge

#2092 [ET-1169] tweak padding for going dropdown
  readme.txt
  src/resources/postcss/rsvp-v1.pcss
Labels: code review, merge

#2070 [ET-1179] Removed style causing overlapping text
  readme.txt
  src/resources/postcss/tickets/_block.pcss
Labels: code review, merge

#2088 TribeCommerce and Ticket Commerce parallel fixes.
  src/Tickets/Commerce/Hooks.php
  src/Tickets/Commerce/Legacy_Compat.php
  src/Tickets/Commerce/Shortcodes/Checkout_Shortcode.php
  src/Tribe/Commerce/PayPal/Main.php
  src/admin-views/tribe-options-tickets.php
  src/functions/commerce/provider.php
Labels: code review

#2093 [ET-1169] ensure arrow shows if set by theme
  readme.txt
  src/resources/postcss/rsvp-v1.pcss
Labels: code review

#2091 [ET-1205] Fix ticket settings update breaking provider meta data.
  src/Tickets/Commerce/Hooks.php
  src/Tickets/Commerce/Legacy_Compat.php
  src/Tickets/Commerce/Settings.php
Labels: code review

#2054 [ETP-543] Use `tickets_provider` instead of `provider` to prevent WooCommerce conflicts
  readme.txt
  src/Tribe/Attendee_Registration/Main.php
  src/Tribe/Commerce/Cart.php
  src/Tribe/Tickets.php
  src/template-tags/tickets.php
  src/views/modal/registration.php
  src/views/registration-js/content.php
  src/views/registration-js/mini-cart.php
  src/views/registration/content.php
Labels: code review, merge

#2094 [ET-1169] just remove top and bottom padding
  src/resources/postcss/rsvp-v1.pcss
Labels: code review

#2086 Tickets Commerce PayPal Webhooks
  composer.json
  composer.lock
  package-lock.json
  src/Tickets/Commerce/Gateways/PayPal/Ajax_Request_Handler.php
  src/Tickets/Commerce/Gateways/PayPal/Client.php
  src/Tickets/Commerce/Gateways/PayPal/Hooks.php
  src/Tickets/Commerce/Gateways/PayPal/Models/PayPal_Order.php
  src/Tickets/Commerce/Gateways/PayPal/Models/PayPal_Payment.php
  src/Tickets/Commerce/Gateways/PayPal/Models/Webhook_Config.php
  src/Tickets/Commerce/Gateways/PayPal/On_Boarding_Redirect_Handler.php
  src/Tickets/Commerce/Gateways/PayPal/Provider.php
  src/Tickets/Commerce/Gateways/PayPal/REST/On_Boarding_Endpoint.php
  src/Tickets/Commerce/Gateways/PayPal/REST/Webhook_Endpoint.php
  src/Tickets/Commerce/Gateways/PayPal/Repositories/Authorization.php
  src/Tickets/Commerce/Gateways/PayPal/Repositories/Order.php
  src/Tickets/Commerce/Gateways/PayPal/Repositories/Webhooks.php
  src/Tickets/Commerce/Gateways/PayPal/Webhooks.php
  src/Tickets/Commerce/Gateways/PayPal/Webhooks/Events.php
  src/Tickets/Commerce/Gateways/PayPal/Webhooks/Handler.php
  src/Tickets/Commerce/Gateways/PayPal/Webhooks/Headers.php
  src/Tickets/Commerce/Gateways/PayPal/Webhooks/Listeners/Event_Listener.php
  src/Tickets/Commerce/Gateways/PayPal/Webhooks/Listeners/Payment_Capture_Completed.php
  src/Tickets/Commerce/Gateways/PayPal/Webhooks/Listeners/Payment_Capture_Denied.php
  src/Tickets/Commerce/Gateways/PayPal/Webhooks/Listeners/Payment_Capture_Refunded.php
  src/Tickets/Commerce/Gateways/PayPal/Webhooks/Listeners/Payment_Capture_Reversed.php
  src/Tickets/Commerce/Gateways/PayPal/Webhooks/Listeners/Payment_Event_Listener.php
  src/Tickets/Commerce/Gateways/PayPal/Webhooks/Webhook_Checker.php
  src/Tickets/Commerce/Gateways/PayPal/Webhooks/Webhook_Register.php
  src/Tickets/Commerce/Gateways/PayPal/Webhooks/Webhooks_Route.php
  src/Tribe/Commerce/PayPal/Main.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/ActiveTest__test_should_render__1.php
  tests/commerce_integration/_bootstrap.php
  tests/wpunit/Tribe/REST/V1/Endpoints/PayPal_Commerce/Payment_Capture_CompletedTest.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Stock/SharedCapacityTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_if_has_provider_and_provider_has_same_class_as_ticket_provider__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_wit_whatever_data_attribute__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemsTest__test_should_render_if_not_empty_tickets_on_sale__1.php
  tests/wpunit/_bootstrap.php
Labels: code review

#2089 [ETP-703] Disable resend of tickets from Attendees page
  readme.txt
  src/Tribe/Attendees_Table.php
Labels: code review

#2090 Fixed PayPal Order capture API fail
  src/Tickets/Commerce/Gateways/PayPal/Client.php
  src/Tickets/Commerce/Gateways/PayPal/REST/Order_Endpoint.php
  src/resources/js/commerce/gateway/paypal/checkout.js
Labels: code review

#2079 [ET-1186] Enhancement - Add loader/spinner on Ticket Commerce Checkout page
  src/Tickets/Commerce/Assets.php
  src/Tickets/Commerce/Gateways/PayPal/Assets.php
  src/resources/js/commerce/gateway/paypal/checkout.js
  src/resources/js/v2/tickets-commerce.js
  src/views/v2/commerce/checkout.php
  src/views/v2/commerce/gateway/paypal/checkout-script.php
  src/views/v2/components/loader/loader.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Components/Loader/LoaderTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Components/Loader/__snapshots__/LoaderTest__test_should_render_loader_without_hidden_class__1.php
Labels: merge

#2096 [ET-1201] Disable free ticket for TicketCommerce and TribeCommerce
  readme.txt
  src/Tribe/Editor.php
  src/admin-views/editor/fieldset/price.php
Labels: merge

#2098 [ET-1212] Loader not hiding and PayPal buttons not showing up.
  src/resources/js/commerce/gateway/paypal/checkout.js
Labels: code review

#2102 [ET-1189] Fix typo on TC payments settings
  src/Tickets/Commerce/Settings.php
  src/admin-views/settings/tickets-commerce/paypal/connect/inactive.php
  src/admin-views/tribe-commerce-settings.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render__1.php
Labels: merge

#2097 Reports: Orders
  src/Tickets/Assets.php
  src/Tickets/Commerce/Admin_Tables/Orders.php
  src/Tickets/Commerce/Assets.php
  src/Tickets/Commerce/Gateways/PayPal/REST/Order_Endpoint.php
  src/Tickets/Commerce/Hooks.php
  src/Tickets/Commerce/Module.php
  src/Tickets/Commerce/Provider.php
  src/Tickets/Commerce/Reports/Event.php
  src/Tickets/Commerce/Reports/Orders.php
  src/Tickets/Commerce/Reports/Report_Abstract.php
  src/Tickets/Commerce/Reports/Ticket.php
  src/Tickets/Commerce/Ticket.php
  src/Tickets/Hooks.php
  src/admin-views/commerce/reports/orders.php
  src/admin-views/commerce/reports/orders/summary.php
  src/resources/js/commerce/gateway/paypal/checkout.js
  src/resources/js/tickets-provider.js
  src/resources/js/v2/tickets-commerce.js
Labels: code review

#2105 [ET-1199] Fix showing Capacity field twice in Classic RSVP ticket editor metabox.
  src/admin-views/commerce/metabox/capacity.php
Labels: code review, merge

#2106 Spotfix/remove changelog file from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: merge

#2103 [ET-1177] Late escape, code amendments.
  src/views/v2/commerce/order/description.php
  src/views/v2/commerce/order/details.php
  src/views/v2/commerce/order/footer/links/back-home.php
  src/views/v2/commerce/order/footer/links/browse-events.php
Labels: merge

#2100 Fix - PayPal capture not working outside US
  src/Tickets/Commerce/Gateways/PayPal/REST/Order_Endpoint.php
  src/resources/js/commerce/gateway/paypal/checkout.js
Labels: merge

#2109 [ET-1221] Avoid printing PayPal buttons if there are no tickets in cart for checkout.
  src/Tickets/Commerce/Gateways/PayPal/Buttons.php
Labels: code review

#2115 TC - store cart hash with order
  src/Tickets/Commerce/Order.php
  src/Tickets/Commerce/Repositories/Order_Repository.php
Labels: merge
