Repository the-events-calendar/event-tickets, pull requests merged in 2021-12, with the labels that each got.

#2216 [ET-1344] Fix 'Maximum function nesting' error
  readme.txt
  src/Tickets/Commerce/Legacy_Compat.php
  src/Tickets/Commerce/Ticket.php
  src/Tickets/Commerce/Utils/Price.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/Item/__snapshots__/ItemSubtotalTest__test_should_render_cart_item_subtotal__0.snapshot.html
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/__snapshots__/CartFooterTest__test_should_render_cart__0.snapshot.html
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/__snapshots__/CartTest__test_should_render_cart__0.snapshot.html
Labels: code review

#2215 [ET-1343] remove wp cache flush
  readme.txt
  src/Tribe/Cache/Transient_Cache.php
Labels: code review

#2214 [ETP-764] Manual Attendee Not Working
  .github/workflows/tests-php.yml
  composer.lock
  readme.txt
  src/Tickets/Commerce/Repositories/Tickets_Repository.php
  src/template-tags/tickets.php
  tests/unit.suite.dist.yml
  tests/unit/_bootstrap.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Handler/IPNTest.php
  tests/wpunit/Tribe/Tickets/Commerce/Utils/PriceTest.php
Labels: enhance, code review

#2217 [ET-1291] - Tickets Commerce & Tribe Commerce with shared cap won't allow tickets for second ticket
  readme.txt
  src/resources/js/v2/tickets-block.js
Labels: merge

#2223 [ETP-763] RSVP ARI needs tribe common dependency
  src/Tribe/Editor/Blocks/Rsvp.php
Labels: code review

#2222 Update Jest testing for block editor JS files
  .github/workflows/tests-js.yml
  jest.config.js
  jest.config.json
  jest.setup.js
  package-lock.json
  package.json
  src/modules/.eslintrc
  src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/__tests__/__snapshots__/template.test.js.snap
  src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/__tests__/template.test.js
  src/modules/data/blocks/rsvp/__tests__/__snapshots__/sagas.test.js.snap
  src/modules/data/blocks/rsvp/__tests__/reducer.test.js
  src/modules/data/blocks/rsvp/__tests__/sagas.test.js
  src/modules/data/blocks/rsvp/reducers/__tests__/details.test.js
  src/modules/data/blocks/rsvp/reducers/__tests__/temp-details.test.js
  src/modules/data/blocks/ticket/__tests__/__snapshots__/sagas.test.js.snap
  src/modules/data/blocks/ticket/__tests__/sagas.test.js
  src/modules/data/blocks/ticket/__tests__/selectors.test.js
  src/modules/data/blocks/ticket/reducers/__tests__/tickets.test.js
  src/modules/data/blocks/ticket/reducers/tickets/__tests__/ticket.test.js
  src/modules/data/blocks/ticket/reducers/tickets/ticket/__tests__/details.test.js
  src/modules/data/blocks/ticket/reducers/tickets/ticket/__tests__/temp-details.test.js
Labels: code review, merge

#2226 Fix element index files for modules
  src/modules/blocks/rsvp/container/template.js
  src/modules/blocks/rsvp/inactive-block/template.js
  src/modules/blocks/ticket/container/template.js
  src/modules/blocks/tickets/container/template.js
  src/modules/elements/action-button/__tests__/element.test.js
  src/modules/elements/action-button/index.js
  src/modules/elements/action-dashboard/index.js
  src/modules/elements/attendees-registration/index.js
  src/modules/elements/container-panel/__tests__/element.test.js
  src/modules/elements/container-panel/index.js
  src/modules/elements/date-time-range-picker/index.js
  src/modules/elements/inactive-block/__tests__/element.test.js
  src/modules/elements/inactive-block/index.js
  src/modules/elements/index.js
  src/modules/elements/label-with-tooltip/__tests__/element.test.js
  src/modules/elements/label-with-tooltip/index.js
  src/modules/elements/numeric-label/index.js
  src/modules/elements/settings-dashboard/index.js
  src/modules/elements/warning-button/index.js
Labels: code review
