Repository the-events-calendar/event-tickets, pull requests merged in 2021-01, with the labels that each got.

#1916 updating readme
  readme.txt
Labels: code review

#1917 update plugin header
  event-tickets.php
Labels: merge

#1920 [ETP-627] Add compatibility to multiple shortcodes in the same page
  readme.txt
  src/resources/js/tickets-block.js
  src/resources/js/v2/tickets-block.js
Labels: merge

#1921 [ETP-629] Localize tribe tickets utils.
  readme.txt
  src/Tribe/Assets.php
Labels: merge

#1923 [ET-994] More specifically hook onto the trash link for the delete confirmation
  readme.txt
  src/resources/js/tickets-attendees.js
Labels: merge

#1924 [ET-995] Prevent problems with fatal errors from tickets that no longer exist
  readme.txt
  src/Tribe/Commerce/PayPal/Gateway.php
Labels: merge

#1918 [ETP-624] MA > Capitalize `Attendee`
  readme.txt
  src/resources/postcss/tickets-admin.pcss
Labels: merge

#1928 Fix bad merge conflict resolution.
  src/admin-views/tribe-options-tickets.php
Labels: code review

#1925 [ET-927] ET MA BE Part 2: Implement Orders API and integrate with Attendees API work
  src/Tribe/Admin/Manager/Service_Provider.php
  src/Tribe/Attendee_Repository.php
  src/Tribe/Repositories/Attendee/Commerce.php
  src/Tribe/Repositories/Attendee/RSVP.php
  src/Tribe/Repositories/Order.php
  src/Tribe/Service_Providers/ORM.php
  src/Tribe/Tickets.php
  src/template-tags/tickets.php
  tests/wpunit/Tribe/Tickets/ORM/Orders/CreateTest.php
Labels: hold, merge

#1930 [ET-926] ET MA BE Part 3: Clean up logic for order creation and rely less on $ticket object
  src/Tribe/Attendee_Repository.php
  src/Tribe/Repositories/Order.php
Labels: code review

#1933 Use the correct method to determine if we have a shortcode or not.
  src/Tribe/Attendee_Registration/Main.php
  src/Tribe/Attendee_Registration/Template.php
Labels: merge
