Repository the-events-calendar/event-tickets, pull requests merged in 2021-04, with the labels that each got.

#1981 [ET-1078] Blocks > Fix RSVP & Tickets block description
  package.json
  readme.txt
  src/modules/blocks/rsvp/container-header/style.pcss
  src/modules/blocks/rsvp/container-header/template.js
  src/modules/blocks/ticket/container-content/advanced-options/move-delete/style.pcss
  src/modules/blocks/ticket/container-header/description/style.pcss
  src/modules/blocks/ticket/container-header/description/template.js
  src/modules/blocks/ticket/container-header/price/style.pcss
  src/modules/blocks/ticket/container-header/title/style.pcss
  src/modules/elements/container-panel/style.pcss
  src/modules/elements/inactive-block/style.pcss
  src/modules/elements/settings-dashboard/style.pcss
Labels: merge

#1973 [ET-1055] Added a filter for attendee CSV export delimiter.
  readme.txt
  src/Tribe/Attendees.php
Labels: merge

#1983 [ET-1079] Add Attendees nav button on Admin bar
  readme.txt
  src/Tribe/Admin/Manager/Service_Provider.php
Labels: merge

#1982 [ET-1056] Add translation support for going/not going status labels
  readme.txt
  src/Tribe/RSVP/Status/Going.php
  src/Tribe/RSVP/Status/Not_Going.php
Labels: merge

#1979 [ET-1051] Fix override folder comment on templates
  readme.txt
  src/views/tickets/attendees-email.php
  src/views/tickets/orders-pp-tickets.php
  src/views/tickets/orders-rsvp.php
  src/views/tickets/orders.php
  src/views/tickets/tpp-return-to-cart.php
  src/views/tickets/tpp-success.php
  src/views/tickets/view-link.php
Labels: merge

#1988 Add tracker to KB links for Event Settings Banner
  src/Tribe/Admin/Settings/Service_Provider.php
Labels: code review, merge

#1987 [ET-984] moved check in button to new template and added disabled attribute
  readme.txt
  src/Tribe/Attendees_Table.php
  src/admin-views/attendees-table/check-in-button.php
Labels: merge

#1989 [ET-1078] Update package.json and lock for the packager
  package-lock.json
  package.json
Labels: merge

#1991 Fix compatibility for TwentyTwentyOne.
  src/resources/postcss/tickets-forms.pcss
  src/resources/postcss/tickets/_block-footer.pcss
Labels: merge

#1992 [ET-984] Fixed misplaced logic for Check In button
  src/Tribe/Attendees_Table.php
Labels: merge

#1993 [ET-1079] Make use of `is_singular` to support pages
  src/Tribe/Admin/Manager/Service_Provider.php
Labels: merge

#1995 [ETP-699] AR fields > Fix edit
  src/resources/js/tickets.js
Labels: merge

#2002 [ETP-719] Fix localize for tickets admin manager (manual attendees problem)
  readme.txt
  src/Tribe/Assets.php
  src/resources/js/admin/tickets-manager.js
Labels: code review
