Repository the-events-calendar/event-tickets, pull requests merged in 2021-05, with the labels that each got.

#1996 [ET-768] Attendee table check-in i18n
  readme.txt
  src/resources/postcss/tickets-report.pcss
Labels: merge

#1998 [ET-767] Improve a11y on tickets & rsvp forms
  readme.txt
  src/admin-views/editor/list-row.php
  src/views/blocks/rsvp/form/quantity-input.php
  src/views/blocks/tickets/quantity-number.php
  src/views/tickets/rsvp.php
  src/views/v2/rsvp/ari/sidebar/quantity/input.php
  src/views/v2/tickets/item/quantity/number.php
  tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Content__test_should_render_content__1.php
  tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Content__test_should_render_out_of_stock__1.php
  tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Content__test_should_render_unlimited__1.php
  tests/wpunit/Tribe/Tickets/Partials/RSVP/__snapshots__/Form__test_should_render_form__1.php
  tests/wpunit/Tribe/Tickets/Partials/Tickets/QuantityTest.php
  tests/wpunit/Tribe/Tickets/Partials/Tickets/__snapshots__/Quantity__test_should_render_quantity_available__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/RSVP/ARI/Sidebar/__snapshots__/QuantityTest__test_should_render_ar_sidebar_quantity__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/RSVP/ARI/__snapshots__/SidebarTest__test_should_render_ar_sidebar__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Quantity/NumberTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Quantity/__snapshots__/NumberTest__test_should_render_disabled_number_when_must_login_is_true__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/Quantity/__snapshots__/NumberTest__test_should_render_number_html__1.php
  tests/wpunit/Tribe/Tickets/RSVPTest.php
  tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set ari__1.php
Labels: merge

#2001 [ETP-594] Aesthetic changes for the ticket ui in classic editor.
  readme.txt
  src/admin-views/editor/list-row.php
  src/resources/postcss/tickets-tables.pcss
Labels: merge

#1997 [ETP-715] Tickets block > Update footer calculations
  readme.txt
  src/resources/js/v2/tickets-block.js
Labels: merge

#2004 [ETP-594] Add `table-layout: fixed` for chrome overflow.
  src/resources/postcss/tickets-tables.pcss
Labels: merge

#2003 [ET-1053] Hide past/future tickets from showing up in TEC cost range for Events.
  src/Tribe/Tickets.php
  tests/wpunit/Tribe/Tickets/Tickets/CostRangeTest.php
Labels: merge

#1999 [ET-791] Fix Attendee List block's shown attendance count
  readme.txt
  src/Tribe/Editor/Blocks/Attendees.php
  src/Tribe/Events/Attendees_List.php
  src/views/blocks/attendees/description.php
Labels: merge

#2006 [ETP-715] adjust cart checkout data
  src/resources/js/v2/tickets-block.js
Labels: merge

#2005 [ETP-594] DQA for ETP-594
  src/resources/postcss/tickets-tables.pcss
Labels: merge

#2012 GitHub Action-based zip packaging
  .github/workflows/zip.yml
Labels: code review, merge

#2011 [ET-1114] Fix number calculation for prices with thousands separator and no decimals
  readme.txt
  src/resources/js/tickets-block.js
  src/resources/js/v2/tickets-utils.js
Labels: merge

#2010 [ET-1121] Move complete list of changelog entries to `changelog.txt`
  .github/PULL_REQUEST_TEMPLATE.md
  changelog.txt
  readme.txt
Labels: merge

#2014 Install product taskmaster from npm
  gulpfile.js
  package-lock.json
  package.json
  webpack.config.js
Labels: code review, hold, merge

#2013 [ETP-651] Fix Shared capacity stock sync on attendee deletion
  readme.txt
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Ticket_Object.php
  src/Tribe/Tickets.php
  src/Tribe/Tickets_Handler.php
  tests/wpunit/Tribe/Tickets/Commerce/PayPal/Stock/SharedCapacityTest.php
Labels: merge
