Repository the-events-calendar/event-tickets, pull requests merged in 2022-02, with the labels that each got.

#2258 [ET-1376] stripe general settings
  src/Tickets/Commerce/Abstract_Order.php
  src/Tickets/Commerce/Gateways/Contracts/Abstract_Gateway.php
  src/Tickets/Commerce/Gateways/Contracts/Abstract_Merchant.php
  src/Tickets/Commerce/Gateways/Contracts/REST_Endpoint_Interface.php
  src/Tickets/Commerce/Gateways/Contracts/Signup_Interface.php
  src/Tickets/Commerce/Gateways/Contracts/WhoDat_Interface.php
  src/Tickets/Commerce/Gateways/Manager.php
  src/Tickets/Commerce/Gateways/Stripe/Gateway.php
  src/Tickets/Commerce/Gateways/Stripe/Merchant.php
  src/Tickets/Commerce/Gateways/Stripe/REST/Order_Endpoint.php
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
  src/Tickets/Commerce/Gateways/Stripe/Signup.php
  src/Tickets/Commerce/Gateways/Stripe/Status.php
  src/Tickets/Commerce/Gateways/Stripe/WhoDat.php
  src/Tickets/Commerce/Payments_Tab.php
  src/admin-views/settings/featured/content.php
  src/admin-views/settings/featured/link.php
  src/admin-views/settings/tickets-commerce/gateways/button.php
  src/admin-views/settings/tickets-commerce/gateways/item.php
  src/admin-views/settings/tickets-commerce/gateways/status.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/actions.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/actions/refresh-access-token.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/actions/refresh-connection.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/actions/refresh-user-info.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/actions/refresh-webhook.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/paypal-status.php
  src/admin-views/settings/tickets-commerce/stripe/connect/help-links/configuring.php
  src/admin-views/settings/tickets-commerce/stripe/connect/help-links/troubleshooting.php
  src/resources/js/commerce/gateway/base.js
  src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss
  src/views/v2/commerce/checkout/cart.php
  src/views/v2/commerce/checkout/cart/billing-details.php
  src/views/v2/commerce/checkout/cart/billing_identification.php
  src/views/v2/commerce/gateway/stripe/payment_element.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/Stripe/Connect/ActiveTest.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/Stripe/Connect/InactiveTest.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/Stripe/Connect/LogoTest.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/Stripe/Connect/__snapshots__/ActiveTest__test_should_render__0.snapshot.html
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/Stripe/Connect/__snapshots__/InactiveTest__test_should_render__0.snapshot.html
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/Stripe/Connect/__snapshots__/LogoTest__test_should_render__0.snapshot.html
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/Stripe/Connect/__snapshots__/LogoTest__test_should_render_without_list__0.snapshot.html
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/CartTest.php
Labels: code review

#2261 Fix/stripe minor fixes
  src/Tickets/Commerce/Gateways/Stripe/Assets.php
  src/Tickets/Commerce/Gateways/Stripe/Client.php
  src/Tickets/Commerce/Gateways/Stripe/Gateway.php
  src/Tickets/Commerce/Gateways/Stripe/Merchant.php
  src/Tickets/Commerce/Gateways/Stripe/REST/Return_Endpoint.php
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/actions.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/actions/refresh-access-token.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/actions/refresh-connection.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/actions/refresh-user-info.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/actions/refresh-webhook.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/paypal-status.php
  src/resources/js/commerce/gateway/base.js
  src/resources/js/commerce/gateway/stripe/checkout.js
  src/views/tickets/email.php
Labels: merge

#2265 Modify the Stripe JS to better adhere to our Standards
  src/Tickets/Commerce/Gateways/Stripe/Assets.php
  src/Tickets/Commerce/Gateways/Stripe/Client.php
  src/resources/js/commerce/gateway/stripe/checkout.js
  src/views/v2/commerce/gateway/stripe/card-element.php
  src/views/v2/commerce/gateway/stripe/form.php
  src/views/v2/commerce/gateway/stripe/payment-element.php
Labels: code review

#2269 Fix failing tests on the bucket branch `bucket/wp-inner-block-component-deprecation`
  package-lock.json
  package.json
Labels: merge

#2263 [ET-1385] Enabled default will be true if Gateway is connected
  src/Tickets/Commerce/Gateways/PayPal/Gateway.php
Labels: code review

#2278 Bump version number on `readme.txt`
  readme.txt
Labels: code review

#2273 Feature/etp 770 payment methods
  src/Tickets/Commerce/Gateways/Stripe/Assets.php
  src/Tickets/Commerce/Gateways/Stripe/Client.php
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
  src/Tickets/Commerce/Settings.php
  src/resources/js/commerce/gateway/stripe/checkout.js
Labels: code review, merge

#2266 Remove deprecated `wp.editor.InnerBlocks` component in favor of `wp.blockEditor.InnerBlocks` [ET-1367]
  package-lock.json
  package.json
  readme.txt
  src/modules/blocks/ticket/index.js
  src/modules/blocks/tickets/container/template.js
  src/modules/blocks/tickets/index.js
Labels: code review

#2280 Add placeholder for statement descriptor
  src/Tickets/Commerce/Gateways/Stripe/Client.php
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
Labels: merge

#2281 remove settings check for collecting billing details
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
  src/resources/js/commerce/gateway/stripe/checkout.js
Labels: code review, merge

#2271 [ET-1369] Checkout Front-end: multiple gateways toggle
  src/Tickets/Commerce/Assets.php
  src/Tickets/Commerce/Gateways/Contracts/Abstract_Gateway.php
  src/Tickets/Commerce/Gateways/PayPal/Assets.php
  src/Tickets/Commerce/Gateways/PayPal/Buttons.php
  src/Tickets/Commerce/Gateways/PayPal/Gateway.php
  src/Tickets/Commerce/Gateways/PayPal/Hooks.php
  src/Tickets/Commerce/Gateways/Stripe/Assets.php
  src/Tickets/Commerce/Gateways/Stripe/Gateway.php
  src/Tickets/Commerce/Gateways/Stripe/Hooks.php
  src/Tickets/Commerce/Gateways/Stripe/Stripe_Elements.php
  src/Tickets/Commerce/Shortcodes/Checkout_Shortcode.php
  src/resources/js/commerce/gateway/base.js
  src/resources/js/commerce/gateway/toggler.js
  src/resources/postcss/tickets-commerce/_checkout.pcss
  src/resources/postcss/tickets-commerce/gateway/paypal/_advanced-payments.pcss
  src/resources/postcss/tickets-commerce/gateway/stripe.pcss
  src/resources/postcss/tickets-commerce/gateway/stripe/_all.pcss
  src/resources/postcss/tickets-commerce/gateway/stripe/_stripe.pcss
  src/views/v2/commerce/checkout.php
  src/views/v2/commerce/checkout/cart.php
  src/views/v2/commerce/checkout/cart/billing-details.php
  src/views/v2/commerce/gateway/gateways.php
  src/views/v2/commerce/gateway/paypal/container.php
  src/views/v2/commerce/gateway/stripe/card-element.php
  src/views/v2/commerce/gateway/stripe/container.php
  src/views/v2/commerce/gateway/stripe/payment-element.php
Labels: enhance, code review

#2275 Performance improvements for the Blocks Assets
  readme.txt
  src/Tribe/Editor/Blocks/Tickets.php
  src/Tribe/Editor/Provider.php
Labels: code review

#2283 fix missing requires_source status
  src/Tickets/Commerce/Gateways/Stripe/Status.php
Labels: merge

#2285 Stripe Minor Fixes
  src/Tickets/Commerce/Gateways/Stripe/Hooks.php
  src/Tickets/Commerce/Gateways/Stripe/REST/Return_Endpoint.php
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
  src/resources/js/commerce/gateway/base.js
Labels: code review

#2284 [ET-1387] FE audit - Part 1
  src/Tickets/Commerce/Gateways/PayPal/Gateway.php
  src/Tickets/Commerce/Gateways/Stripe/Gateway.php
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
  src/Tickets/Commerce/Payments_Tab.php
  src/Tickets/Commerce/Utils/Currency.php
  src/admin-views/settings/featured/link.php
  src/admin-views/settings/tickets-commerce/gateways.php
  src/admin-views/settings/tickets-commerce/gateways/toggle.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/connection.php
  src/admin-views/settings/tickets-commerce/stripe/connect/inactive.php
  src/admin-views/settings/tickets-commerce/stripe/connect/logo/image.php
  src/admin-views/settings/tickets-commerce/stripe/main.php
  src/admin-views/settings/tickets-commerce/stripe/signup-link.php
  src/resources/images/admin/stripe-logo.png
  src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss
  src/resources/postcss/tickets-commerce/_checkout.pcss
  src/views/v2/commerce/gateway/stripe/card-element.php
  src/views/v2/commerce/gateway/stripe/container.php
  src/views/v2/commerce/gateway/stripe/payment-element.php
Labels: code review

#2287 [ET-1403] Fixed Tickets Commerce PayPal JS not getting loaded
  src/Tickets/Commerce/Gateways/PayPal/Assets.php
  src/Tickets/Commerce/Gateways/Stripe/Assets.php
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
Labels: merge

#2290 get statement descriptor in different forms
  src/Tickets/Commerce/Gateways/Stripe/Client.php
Labels: merge

#2295 [ET-1400] Remove usd from klarna
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
Labels: code review

#2296 Use proper formatting for JS data on tickets block
  src/Tribe/Editor/Blocks/Tickets.php
Labels: code review

#2289 [ET-1390] Stripe Checkout Card Element: Styling
  src/Tickets/Commerce/Gateways/Stripe/Stripe_Elements.php
  src/resources/postcss/tickets-commerce/gateway/stripe/_stripe.pcss
  src/views/v2/commerce/gateway/stripe/card-element.php
Labels: merge

#2282 [ET-1370] Stripe payment element styling
  src/Tickets/Commerce/Gateways/Stripe/Assets.php
  src/resources/js/commerce/gateway/stripe/checkout.js
Labels: merge

#2288 [ET-1369] Checkout Toggle: Some JS Tweaks
  src/resources/js/commerce/gateway/toggler.js
Labels: merge

#2298 Sync changelog.
  changelog.txt
Labels: code review

#2301 Fix snapshot tests for juravenator branch
  tests/wpunit/Tribe/Tickets/Partials/V2/RSVP/ARI/__snapshots__/SidebarTest__test_should_render_ar_sidebar__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/TicketsTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_regular_tickets_block__1.php
Labels: code review, merge

#2302 Fix for Notice on Checkout
  src/resources/js/commerce/gateway/paypal/checkout.js
Labels: code review

#2306 [ET-1355] DQA Modifcations: PayPal Section
  src/Tickets/Commerce/Gateways/PayPal/REST/On_Boarding_Endpoint.php
  src/Tickets/Commerce/Gateways/PayPal/Settings.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-access-token.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-connection.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-user-info.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-webhook.php
  src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/ActiveTest.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/ActiveTest__test_should_render__0.snapshot.html
Labels: code review

#2307 [ET-1379] Remove anonymous purchase notice after ET-1378 was implemented.
  readme.txt
  src/Tickets/Commerce/Admin/Notices.php
Labels: code review

#2305 Deny Connections to Accounts we can't serve
  src/Tickets/Commerce/Gateways/Stripe/Client.php
  src/Tickets/Commerce/Gateways/Stripe/Gateway.php
  src/Tickets/Commerce/Gateways/Stripe/Hooks.php
  src/Tickets/Commerce/Gateways/Stripe/Merchant.php
  src/Tickets/Commerce/Gateways/Stripe/REST/Return_Endpoint.php
Labels: enhance, code review

#2294 [ET-1362] Improve get_ticket() usage and fallbacks
  readme.txt
  src/Tickets/Commerce/Ticket.php
  src/Tribe/CSV_Importer/RSVP_Importer.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/RSVP.php
Labels: code review

#2309 [ET-1396] TC > Stripe > Implement the loader for the stripe checkout.
  src/resources/js/commerce/gateway/stripe/checkout.js
Labels: code review

#2310 Fix npm lint problem.
  src/resources/js/v2/tickets-commerce.js
Labels: merge

#2304 [ET-1387] Stripe audit II
  src/Tickets/Commerce/Admin/Featured_Settings.php
  src/Tickets/Commerce/Gateways/Stripe/Client.php
  src/Tickets/Commerce/Gateways/Stripe/Merchant.php
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
  src/Tickets/Commerce/Payments_Tab.php
  src/Tickets/Commerce/Settings.php
  src/admin-views/settings/featured.php
  src/admin-views/settings/featured/container.php
  src/admin-views/settings/featured/content.php
  src/admin-views/settings/featured/description.php
  src/admin-views/settings/featured/links.php
  src/admin-views/settings/featured/title.php
  src/admin-views/settings/tickets-commerce/gateways.php
  src/admin-views/settings/tickets-commerce/gateways/brand.php
  src/admin-views/settings/tickets-commerce/gateways/button.php
  src/admin-views/settings/tickets-commerce/gateways/container.php
  src/admin-views/settings/tickets-commerce/gateways/item.php
  src/admin-views/settings/tickets-commerce/gateways/status.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/actions.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-access-token.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-connection.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-user-info.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/actions/refresh-webhook.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/connection.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/paypal-status.php
  src/admin-views/settings/tickets-commerce/paypal/connect/active/webhooks.php
  src/admin-views/settings/tickets-commerce/paypal/connect/help-links.php
  src/admin-views/settings/tickets-commerce/paypal/connect/inactive.php
  src/admin-views/settings/tickets-commerce/paypal/connect/logo.php
  src/admin-views/settings/tickets-commerce/paypal/connect/logo/image.php
  src/admin-views/settings/tickets-commerce/paypal/main.php
  src/admin-views/settings/tickets-commerce/paypal/modal/signup-complete/content.php
  src/admin-views/settings/tickets-commerce/paypal/modal/signup-complete/notice-test-mode.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/stripe-status.php
  src/resources/images/admin/stripe-connect-hover.svg
  src/resources/images/admin/stripe-connect.svg
  src/resources/postcss/tickets-commerce/gateway/stripe/_stripe.pcss
  src/views/v2/commerce/checkout.php
  src/views/v2/commerce/checkout/gateways.php
  src/views/v2/commerce/checkout/purchaser-info.php
  src/views/v2/commerce/checkout/purchaser-info/name.php
  src/views/v2/commerce/gateway/stripe/card-element.php
  src/views/v2/commerce/gateway/stripe/payment-element.php
Labels: code review

#2313 [ET-1369] QA Modifications: Toggle Enhancement
  src/resources/js/commerce/gateway/toggler.js
Labels: code review, merge

#2314 [ET-1390] DQA Modifications: Card Element Styling
  src/Tickets/Commerce/Gateways/Stripe/Assets.php
  src/resources/js/commerce/gateway/stripe/checkout.js
  src/resources/postcss/tickets-commerce/gateway/stripe/_stripe.pcss
Labels: code review

#2317 Implement the stripe currency section with messaging.
  src/admin-views/settings/tickets-commerce/stripe/connect/active.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/stripe-currency.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/stripe-status.php
  src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss
Labels: merge

#2299 PaymentIntents fallback
  src/Tickets/Commerce/Gateways/Contracts/Abstract_Requests.php
  src/Tickets/Commerce/Gateways/Contracts/Requests_Interface.php
  src/Tickets/Commerce/Gateways/Stripe/Application_Fee.php
  src/Tickets/Commerce/Gateways/Stripe/Assets.php
  src/Tickets/Commerce/Gateways/Stripe/Client.php
  src/Tickets/Commerce/Gateways/Stripe/Gateway.php
  src/Tickets/Commerce/Gateways/Stripe/Hooks.php
  src/Tickets/Commerce/Gateways/Stripe/Merchant.php
  src/Tickets/Commerce/Gateways/Stripe/Payment_Intent.php
  src/Tickets/Commerce/Gateways/Stripe/Payment_Intent_Handler.php
  src/Tickets/Commerce/Gateways/Stripe/Provider.php
  src/Tickets/Commerce/Gateways/Stripe/REST/Order_Endpoint.php
  src/Tickets/Commerce/Gateways/Stripe/Requests.php
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
  src/Tickets/Commerce/Order.php
Labels: code review

#2315 [ET-1368] Fix stripe error notices not showing up for invalid purchaser.
  src/Tickets/Commerce/Abstract_Order.php
  src/Tickets/Commerce/Gateways/Stripe/REST/Order_Endpoint.php
  src/resources/js/commerce/gateway/paypal/checkout.js
  src/resources/js/commerce/gateway/stripe/checkout.js
Labels: code review

#2245 [CT-51] Undefined Meta index returned on CE/CTE Pages
  readme.txt
  src/Tribe/Tickets.php
Labels: code review, innovation

#2321 Spotfix - Fixed fatal typo on stripe settings title
  src/admin-views/settings/tickets-commerce/stripe/connect/active/stripe-status.php
Labels: code review

#2323 [ET-1408] Stripe: Hide Settings if Not Connected
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
Labels: code review

#2324 [ET-1413] Fix/et 1413 stripe checkout error display
  src/resources/js/commerce/gateway/stripe/checkout.js
Labels: code review, merge

#2325 Correct release date.
  readme.txt
Labels: code review, merge

#2318 [ET-1410] Implement modal that triggers after a successful connection with Stripe.
  src/Tickets/Commerce/Gateways/Stripe/REST/Return_Endpoint.php
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
  src/admin-views/settings/tickets-commerce/paypal/modal/signup-complete.php
  src/admin-views/settings/tickets-commerce/stripe/connect/logo/features.php
  src/admin-views/settings/tickets-commerce/stripe/main.php
  src/admin-views/settings/tickets-commerce/stripe/modal/signup-complete.php
  src/admin-views/settings/tickets-commerce/stripe/modal/signup-complete/content.php
  src/admin-views/settings/tickets-commerce/stripe/modal/signup-complete/notice-test-mode.php
  src/resources/js/admin/tickets-commerce-settings.js
  src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss
Labels: code review, merge

#2328 [ET-1410] DQA Modifications: Fix Modal Styling
  src/admin-views/settings/tickets-commerce/paypal/modal/signup-complete.php
Labels: code review

#2330 Fix/stripe misc issues
  src/Tickets/Commerce/Gateways/Contracts/Abstract_Gateway.php
  src/Tickets/Commerce/Gateways/PayPal/Hooks.php
  src/Tickets/Commerce/Gateways/Stripe/REST/Return_Endpoint.php
  src/Tickets/Commerce/Gateways/Stripe/Webhooks/Account_Webhook.php
  src/Tickets/Commerce/Gateways/Stripe/Webhooks/Events.php
Labels: merge

#2333 Spotfix/dqa stripe
  src/admin-views/settings/tickets-commerce/stripe/connect/active/button.php
  src/resources/postcss/tickets-commerce/_checkout.pcss
  src/views/v2/commerce/checkout/purchaser-info.php
  src/views/v2/commerce/checkout/purchaser-info/name.php
Labels: code review

#2334 Fix for Checkout Headers in Twenty Twenty theme
  src/resources/postcss/tickets-commerce/_checkout.pcss
Labels: code review, merge

#2336 [ET-1390] Add Error Messages for Separate CardElement Fields
  src/resources/js/commerce/gateway/stripe/checkout.js
Labels: code review

#2339 fix charge webhooks
  src/Tickets/Commerce/Gateways/Stripe/Webhooks/Charge_Webhook.php
  src/Tickets/Commerce/Gateways/Stripe/Webhooks/Events.php
  src/Tickets/Commerce/Gateways/Stripe/Webhooks/Payment_Intent_Webhook.php
  src/Tickets/Commerce/Order.php
Labels: merge

#2340 DQA - Stripe
  src/Tickets/Commerce/Gateways/Stripe/Assets.php
  src/Tickets/Commerce/Gateways/Stripe/Hooks.php
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
Labels: code review

#2342 Fix: Use `is_connected()` instead of `is_active()`
  src/Tickets/Commerce/Payments_Tab.php
  src/admin-views/settings/tickets-commerce/gateways/status.php
Labels: code review

#2343 Spotfix/dqa wehbooks
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
  src/Tickets/Commerce/Gateways/Stripe/Webhooks.php
Labels: code review

#2344 DQA Mods: Disabled Gateways Alert and Toggle Spacing
  src/resources/postcss/tickets-commerce/_checkout.pcss
  src/views/v2/commerce/checkout/footer/gateway-error.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Footer/GatewayErrorTest.php
Labels: merge

#2347 Spotfix - Empty cart showing error from Stripe gateway
  src/Tickets/Commerce/Gateways/Stripe/Payment_Intent.php
  src/resources/js/commerce/gateway/stripe/checkout.js
Labels: code review, merge

#2348 Adjust currency messages
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
  src/admin-views/settings/tickets-commerce/stripe/connect/active/stripe-currency.php
Labels: code review

#2349 Introduce the concept of a "final" post status
  src/Tickets/Commerce/Status/Denied.php
  src/Tickets/Commerce/Status/Pending.php
  src/Tickets/Commerce/Status/Refunded.php
  src/Tickets/Commerce/Status/Reversed.php
  src/Tickets/Commerce/Status/Status_Abstract.php
  src/Tickets/Commerce/Status/Status_Interface.php
  src/Tickets/Commerce/Status/Voided.php
Labels: merge

#2346 [ET-1418] TicketsCommerce Checkout unavailable notice logic fixed for 0 available gateways.
  src/Tickets/Commerce/Module.php
  src/Tickets/Commerce/Payments_Tab.php
  src/Tickets/Commerce/Shortcodes/Checkout_Shortcode.php
  src/views/v2/commerce/checkout/footer/gateway-error.php
  src/views/v2/commerce/checkout/gateways.php
Labels: code review

#2350 Test creating payment intents using proper values per currency
  src/Tickets/Commerce/Gateways/Stripe/Hooks.php
  src/Tickets/Commerce/Gateways/Stripe/Payment_Intent.php
  src/Tickets/Commerce/Utils/Currency.php
  src/Tickets/Commerce/Utils/Value.php
Labels: merge

#2351 [ET-1342] Set release date, add entry, synch changelog.
  changelog.txt
  readme.txt
Labels: code review
