Repository the-events-calendar/event-tickets, pull requests merged in 2022-05, with the labels that each got.

#2394 [ET-1502] Fix Fatal Error When Exporting Attendees in PHP 8
  readme.txt
  src/Tribe/Attendees.php
Labels: enhance, code review

#2395 [ET-1504] Fix Typo in Value Utility for Tickets Commerce
  readme.txt
  src/Tickets/Commerce/Utils/Value.php
Labels: merge

#2396 Fix check to include assets in the tickets settings.
  src/Tribe/Assets.php
Labels: code review

#2397 Tweaks to Upsell CSS
  src/resources/postcss/tickets-admin.pcss
  src/resources/postcss/tickets-report.pcss
Labels: code review

#2398 Fixing network settings for ET/TEC (and all the suite)
  readme.txt
  src/Tribe/Admin/Settings.php
Labels: code review

#2399 Remove Minimum Height on Attendees Page
  src/resources/postcss/tickets-report.pcss
Labels: code review

#2400 Tickets menu > Implement new menu icon.
  src/Tribe/Admin/Settings.php
Labels: code review

#2403 remove validation of keys and use format of the key
  src/Tickets/Commerce/Settings.php
Labels: code review

#2404 Fix Events/Tickets menu SVG blink on load
  src/Tribe/Admin/Settings.php
Labels: code review

#2405 Fix/admin menu qa repairs
  src/Tribe/Integrations/Freemius.php
  src/Tribe/Integrations/Manager.php
  src/admin-views/admin-welcome-message.php
  src/resources/postcss/freemius.pcss
Labels: code review

#2411 Remove trailing comma.
  src/admin-views/tribe-options-tickets.php
Labels: code review

#2416 Adding `Version` readme entries.
  readme.txt
Labels: code review

#2414 [ET-1434] Blocks Editor - Fix Encoding Issue in TEC Price Block Caused by TC
  readme.txt
  src/Tickets/Commerce/Legacy_Compat.php
Labels: code review

#2408 [ET-1229] JEST Tests - tickets-utils.js
  .github/workflows/tests-js.yml
  package.json
  src/modules/blocks/ticket/container-content/attendee-collection/iac-setting/__tests__/template.test.js
  src/resources/js/.eslintrc
  src/resources/js/v2/__tests__/tickets-utils.test.js
Labels: merge

#2409 [ET-1520] Fix - Avoid loading partner JS everywhere on WP Admin
  readme.txt
  src/Tickets/Commerce/Gateways/PayPal/Assets.php
Labels: merge

#2420 [ET-1521] Settings > Add permalinks configuration notice
  changelog.txt
  readme.txt
  src/Tickets/Commerce/Admin/Notices.php
Labels: code review, merge

#2417 [ET-1454] Tickets Commerce - Add New Currencies for Stripe
  readme.txt
  src/Tickets/Commerce/Utils/Currency.php
Labels: code review

#2422 [ET-1525] Add plugin action links
  readme.txt
  src/Tickets/Admin/Hooks.php
  src/Tickets/Admin/Plugin_Action_Links.php
Labels: code review

#2419 [ET-1456] Tickets Commerce - Add New Currencies for Stripe
  readme.txt
  src/Tickets/Commerce/Utils/Currency.php
Labels: code review

#2423 [ET-1455] Tickets Commerce - Add New Currencies for Stripe
  readme.txt
  src/Tickets/Commerce/Utils/Currency.php
Labels: code review

#2424 [ET-1457] Tickets Commerce - Add New Currencies for Stripe
  src/Tickets/Commerce/Utils/Currency.php
Labels: code review
