Repository the-events-calendar/event-tickets, pull requests merged in 2022-07, with the labels that each got.

#2456 updated version according to release schedule changes
  event-tickets.php
  package.json
  readme.txt
  src/Tribe/Main.php
Labels: code review

#2455 Hotfix: Freemius update
  event-tickets.php
  readme.txt
  src/Tribe/Main.php
Labels: merge

#2451 Tests - Add TicketsCommerce basic capacity tests
  tests/_support/Commerce/TicketsCommerce/Ticket_Maker.php
  tests/commerce_integration/TEC/Tickets/Commerce/Stock/CapacityTest.php
Labels: code review

#2453 [ET-1543] - Fix searching attendees using purhcaser name and email for TicketsCommerce
  readme.txt
  src/Tribe/Attendee_Repository.php
Labels: code review

#2461 Make sure before array_merge we cast as array both ends of the merge
  src/Tribe/Tickets_Handler.php
Labels: code review

#2458 [ET-1506] Fixed RSVP confirmation error messages.
  readme.txt
  src/Tribe/Editor/Blocks/Rsvp.php
  src/Tribe/RSVP.php
  tests/wpunit/Tribe/Tickets/RSVPTest.php
Labels: code review

#2447 [ET-1527] TicketsCommerce Orders column sorting
  readme.txt
  src/Tickets/Commerce/Admin_Tables/Orders.php
  src/Tickets/Commerce/Repositories/Order_Repository.php
Labels: code review

#2459 [ET-1146] Fix - Show proper unavailable message for Past events
  readme.txt
  src/views/v2/tickets/item/inactive.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/InactiveTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/Item/__snapshots__/InactiveTest__test_should_render_if_has_tickets_on_sale_is_false__1.php
Labels: code review, merge

#2463 [ET-1539] Add TC to Tickets Home Page
  readme.txt
  src/admin-views/admin-welcome-message.php
Labels: code review

#2462 [ETP-801] - Fix shared capacity calculation issues for Ticket Block
  readme.txt
  src/resources/js/v2/__tests__/tickets-utils.test.js
  src/resources/js/v2/tickets-block.js
  src/resources/js/v2/tickets-utils.js
Labels: code review

#2465 [ET-1542] Enhancement - TicketsCommerce Stripe Dashboard now shows additional meta data.
  readme.txt
  src/Tickets/Commerce/Gateways/Stripe/Payment_Intent_Handler.php
  src/Tickets/Commerce/Order.php
  src/Tickets/Commerce/Ticket.php
Labels: code review

#2464 [ET-1544] ET Blocks Appear in Wrong Place in Non-Event Posts
  readme.txt
  src/Tribe/Editor/Template/Overwrite.php
Labels: code review

#2432 [ET-1526] Add sorting support for Attendee Report page colums
  readme.txt
  src/Tribe/Attendee_Repository.php
  src/Tribe/Attendees_Table.php
  src/Tribe/Tickets.php
  src/resources/postcss/tickets-report.pcss
Labels: code review
