Repository the-events-calendar/event-tickets, pull requests merged in 2022-09, with the labels that each got.

#2482 [ETP-819] Properly save the check-in details for attendees on check-in.
  readme.txt
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
Labels: code review

#2479 [ETP-812] Fixed showing Checkout not available and credit card fields at the same time for PayPal in TicketsCommerce.
  src/Tickets/Commerce/Gateways/Stripe/Payment_Intent_Handler.php
  src/resources/js/commerce/gateway/paypal/checkout.js
  src/views/v2/commerce/gateway/paypal/advanced-payments.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Gateway/PayPal/__snapshots__/AdvancedPayments__test_should_render__0.snapshot.html
Labels: code review

#2484 [ET-1580] Add `attendance` information to the `events` REST API endpoint.
  readme.txt
  src/Tribe/REST/V1/Main.php
Labels: code review

#2488 Fix nullable param in function signature.
  readme.txt
  src/Tickets/Custom_Tables/V1/Provider.php
Labels: code review

#2491 Tests - Fixed failing tests
  tests/_bootstrap.php
  tests/wpunit/Tribe/Tickets/Template_Tags/GetPostTotalsTest.php
  tests/wpunit/Tribe/Tickets/Template_Tags/GlobalStockTest.php
Labels: merge

#2483 [ETP-820] Add template tag to properly check if The Events Calendar is active.
  readme.txt
  src/template-tags/tickets.php
Labels: code review

#2470 [ET-1567] Fix - TicketsCommerce ticketed events not showing up for Events ORM query.
  readme.txt
  src/Tribe/Repositories/Traits/Post_Tickets.php
Labels: merge

#2497 [ET-1588] Enhancement - Check IN or Check out attendee using attendee REST API endpoints.
  readme.txt
  src/Tickets/Commerce/Module.php
  src/Tribe/Attendee_Repository.php
  src/Tribe/REST/V1/Endpoints/Single_Attendee.php
  tests/wpunit/Tribe/Tickets/ORM/Attendees/RSVP/CreateTest.php
  tests/wpunit/Tribe/Tickets/ORM/Attendees/RSVP/UpdateTest.php
Labels: code review

#2500 Spotfix - Fixed Attendee REST API orderby not working.
  src/Tribe/REST/V1/Endpoints/Attendee_Archive.php
  src/Tribe/REST/V1/Post_Repository.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Admin/PayPal/Connect/__snapshots__/InactiveTest__test_should_render__0.snapshot.html
Labels: code review, merge

#2499 Unify the way we return attendee information on the REST API endpoint.
  src/Tribe/REST/V1/Endpoints/Single_Attendee.php
  src/Tribe/REST/V1/Post_Repository.php
Labels: code review

#2503 [ET-1591] Spotfix - Attendee REST API support for orderby `title` should search by full_name data
  readme.txt
  src/Tribe/Attendee_Repository.php
  src/Tribe/REST/V1/Attendee_Repository.php
  src/Tribe/REST/V1/Endpoints/Attendee_Archive.php
Labels: code review

#2473 [ETP-810] multiple ticket forms on same page
  changelog.txt
  src/resources/js/v2/tickets-block.js
Labels: code review, in-qa
