Repository the-events-calendar/event-tickets, pull requests merged in 2022-11, with the labels that each got.

#2514 [ET-1549] DQA adjustments
  src/admin-views/settings/emails/message-templates/list-title.php
  src/resources/postcss/tickets-admin/settings/_emails.pcss
Labels: code review, merge

#2520 [ETP-815] Fixed shared cap sync causing tickets to use lower capacity all the time.
  readme.txt
  src/Tribe/REST/V1/Endpoints/Ticket_Archive.php
  src/Tribe/Tickets_Handler.php
  tests/commerce_integration/TEC/Tickets/Commerce/Stock/CapacityTest.php
Labels: code review

#2475 [ET-1568] ticket order
  changelog.txt
  readme.txt
  src/resources/js/tickets.js
Labels: code review

#2522 [ET-1614] - Display the Webhook validation response from Stripe for TicketsCommerce.
  readme.txt
  src/Tickets/Commerce/Gateways/Stripe/Webhooks.php
  src/resources/js/admin/gateway/stripe/webhooks.js
Labels: merge
