Repository the-events-calendar/event-tickets, pull requests merged in 2022-01, with the labels that each got.

#2234 Fix/re merge et 1331
  changelog.txt
  src/Tickets/Commerce/Abstract_Order.php
  src/Tickets/Commerce/Admin_Tables/Orders.php
  src/Tickets/Commerce/Cart.php
  src/Tickets/Commerce/Cart/Unmanaged_Cart.php
  src/Tickets/Commerce/Currency.php
  src/Tickets/Commerce/Gateways/Manual/Order.php
  src/Tickets/Commerce/Gateways/PayPal/REST/Order_Endpoint.php
  src/Tickets/Commerce/Legacy_Compat.php
  src/Tickets/Commerce/Models/Order_Model.php
  src/Tickets/Commerce/Models/Ticket_Model.php
  src/Tickets/Commerce/Module.php
  src/Tickets/Commerce/Order.php
  src/Tickets/Commerce/Reports/Attendees.php
  src/Tickets/Commerce/Reports/Orders.php
  src/Tickets/Commerce/Shortcodes/Checkout_Shortcode.php
  src/Tickets/Commerce/Ticket.php
  src/Tickets/Commerce/Utils/Currency.php
  src/Tickets/Commerce/Utils/Price.php
  src/Tickets/Commerce/Utils/Value.php
  src/Tribe/Commerce/Currency.php
  src/admin-views/commerce/reports/orders/summary.php
  src/admin-views/editor/column-body-price.php
  src/views/v2/commerce/checkout/cart/footer/total.php
  src/views/v2/commerce/checkout/cart/item.php
  src/views/v2/commerce/checkout/cart/item/price.php
  src/views/v2/commerce/checkout/cart/item/sub-total.php
  src/views/v2/commerce/order/details/total.php
  src/views/v2/commerce/ticket/price.php
  tests/_data/remap/orders/1.json
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/CartFooterTest.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/CartTest.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/Item/ItemSubtotalTest.php
  tests/commerce_integration/TEC/Tickets/Commerce/Partials/Checkout/Cart/Item/__snapshots__/ItemPriceTest__test_should_render_cart_item_details__0.snapshot.html
  tests/wpunit/Tribe/Tickets/Commerce/Utils/PriceTest.php
Labels: code review

#2231 [ET-1331] Add anonymous purchases notice
  readme.txt
  src/Tickets/Commerce/Admin/Notices.php
Labels: code review

#2230 [ET-1350] Add block editor tickets category icon
  readme.txt
  src/Tribe/Editor.php
  src/Tribe/Editor/Assets.php
  src/resources/images/tec-tickets-logo.svg
Labels: code review, merge

#2232 [ET-1319] Fixed Attendee Report on Posts & Pages
  readme.txt
  src/Tribe/Attendees.php
Labels: code review

#2236 [ET-1350] - Add icon to block editor tickets category
  src/Tribe/Editor/Assets.php
  src/resources/postcss/tickets-admin-blocks.pcss
Labels: code review, merge

#2238 Fix Iguanodon!
  src/Tribe/Editor/Assets.php
Labels: code review, merge

#2240 [ET-1349] Duplicate ticket - Fixes after QA findings
  src/Tribe/Tickets.php
  src/resources/postcss/tickets-tables.pcss
Labels: merge

#2241 [ETP-497] - Fixed initial saving of shared capacity data
  src/Tribe/Tickets_Handler.php
Labels: merge

#2243 [ET-1349] Duplicate Ticket - one more DQA change
  src/resources/postcss/tickets-tables.pcss
Labels: code review, merge

#2244 [ET-1349] Duplicate Ticket - fix for wrapping icons on mobile
  src/resources/postcss/tickets-tables.pcss
Labels: code review, merge

#2246 apply TC cost reset to a TEC filter
  src/Tickets/Commerce/Legacy_Compat.php
Labels: merge

#2247 [ET-1349] Duplicate Ticket - remove duplicate button from CT
  src/admin-views/editor/list-row.php
Labels: code review, merge

#2249 [ET-1349] Duplicate Ticket - remove duplicate button on CT (attempt #2)
  src/admin-views/editor/list-row.php
Labels: code review

#2250 Remove deprecated wp.editor.InnerBlocks component in favor of wp.blockEditor.InnerBlocks [ET-1367]
  readme.txt
  src/modules/blocks/ticket/index.js
  src/modules/blocks/tickets/container/template.js
  src/modules/blocks/tickets/index.js
Labels: code review, needs release, needs tests

#2256 [ET-1356] gateways list
  src/Tickets/Commerce/Gateways/Contracts/Abstract_Gateway.php
  src/Tickets/Commerce/Gateways/Manager.php
  src/Tickets/Commerce/Payments_Tab.php
  src/admin-views/settings/tickets-commerce/gateways/button.php
  src/admin-views/settings/tickets-commerce/gateways/item.php
  src/admin-views/settings/tickets-commerce/gateways/status.php
  src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss
Labels: code review
