Repository the-events-calendar/event-tickets, pull requests merged in 2023-10, with the labels that each got.

#2790 [ET-1874] My Tickets Redesign: Move opt out checkbox after tickets list
  src/resources/postcss/my-tickets/_orders.pcss
  src/resources/postcss/rsvp-v1.pcss
  src/resources/postcss/tpp.pcss
  src/views/tickets/my-tickets/tickets-list.php
  src/views/tickets/orders-pp-tickets.php
  src/views/tickets/orders-rsvp.php
Labels: code review, merge

#2793 Re-styled settings block
  readme.txt
  src/modules/blocks/ticket/container-header/price/style.pcss
  src/modules/blocks/ticket/container-header/quantity/style.pcss
  src/modules/blocks/tickets/availability/style.pcss
  src/modules/blocks/tickets/container/template.js
  src/modules/blocks/tickets/header-image/style.pcss
  src/modules/blocks/tickets/header-image/template.js
  src/modules/elements/settings-dashboard/__tests__/__snapshots__/element.test.js.snap
  src/modules/elements/settings-dashboard/__tests__/element.test.js
  src/modules/elements/settings-dashboard/element.js
  src/modules/elements/settings-dashboard/style.pcss
  src/modules/icons/close.svg
  src/modules/icons/index.js
Labels: code review, merge

#2788 Move the location of service provider to avoid problems with ECP
  readme.txt
  src/Tribe/Main.php
Labels: code review

#2794 Using react-number-format to display price given the decimal and thousands separators from wordpress settings
  package-lock.json
  package.json
  readme.txt
  src/Tribe/Editor/Configuration.php
  src/modules/blocks/ticket/container-content/price/__tests__/__snapshots__/template.test.js.snap
  src/modules/blocks/ticket/container-content/price/__tests__/template.test.js
  src/modules/blocks/ticket/container-content/price/container.js
  src/modules/blocks/ticket/container-content/price/style.pcss
  src/modules/blocks/ticket/container-content/price/template.js
  src/modules/blocks/ticket/container-header/price/container.js
  src/modules/blocks/ticket/container-header/price/template.js
  src/modules/data/blocks/ticket/__tests__/__snapshots__/constants.test.js.snap
  src/modules/data/blocks/ticket/__tests__/__snapshots__/selectors.test.js.snap
  src/modules/data/blocks/ticket/reducers/__tests__/__snapshots__/tickets.test.js.snap
  src/modules/data/blocks/ticket/reducers/tickets/__tests__/__snapshots__/ticket.test.js.snap
  src/modules/data/blocks/ticket/reducers/tickets/ticket.js
  src/modules/data/blocks/ticket/selectors.js
  src/modules/data/blocks/ticket/utils.js
  src/modules/elements/card/style.pcss
Labels: code review

#2791 [ET-1812] Series details on event summary for orders page.
  src/Tickets/Commerce/Gateways/PayPal/Order.php
  src/Tickets/Flexible_Tickets/Base.php
  tests/_support/Commerce/TicketsCommerce/Order_Maker.php
  tests/ft_integration/Tribe/Tickets/OrderReportTest.php
  tests/ft_integration/Tribe/Tickets/__snapshots__/OrderReportTest__test_tc_order_report_display__event in a series with no orders__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/OrderReportTest__test_tc_order_report_display__event in a series with one order__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/OrderReportTest__test_tc_order_report_display__event with no orders__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/OrderReportTest__test_tc_order_report_display__event with one order__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/OrderReportTest__test_tc_order_report_display__recurring event with no order__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/OrderReportTest__test_tc_order_report_display__recurring event with one order__0.snapshot.html
Labels: code review

#2799 [ET-1810] TicketsCommerce Orders Report page design update.
  readme.txt
  src/Tickets/Commerce/Gateways/PayPal/Order.php
  src/Tickets/Commerce/Module.php
  src/Tickets/Commerce/Reports/Data/Order_Summary.php
  src/Tickets/Commerce/Reports/Orders.php
  src/Tickets/Commerce/Ticket.php
  src/Tribe/RSVP.php
  src/Tribe/Ticket_Object.php
  src/Tribe/Tickets.php
  src/admin-views/commerce/reports/orders.php
  src/admin-views/commerce/reports/orders/summary.php
  src/resources/postcss/tickets-report.pcss
  tests/_support/Commerce/Ticket_Maker.php
  tests/_support/Commerce/TicketsCommerce/Order_Maker.php
  tests/integration/Tribe/Admin/OrderReportTest.php
  tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with 1 pending and 1 completed order__0.snapshot.html
  tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with multiple tickets and orders__0.snapshot.html
  tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with multiple tickets in same order__0.snapshot.html
  tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with no orders__0.snapshot.html
  tests/integration/Tribe/Admin/__snapshots__/OrderReportTest__test_tc_order_report_display__event with one order__0.snapshot.html
  tests/integration/_bootstrap.php
Labels: code review

#2808 [ETWP-62] Add confirmed attendees to rsvp block
  readme.txt
  src/Tribe/RSVP.php
  src/resources/postcss/rsvp/_all.pcss
  src/resources/postcss/rsvp/_attendees.pcss
  src/views/v2/rsvp/attendees.php
  src/views/v2/rsvp/attendees/attendee.php
  src/views/v2/rsvp/attendees/title.php
  src/views/v2/rsvp/content.php
  tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockV2Test__test_should_render_ticket_block with data set 0__1.php
  tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockV2Test__test_should_render_ticket_block with data set 1__1.php
  tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockV2Test__test_should_render_ticket_block with data set 2__1.php
  tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockV2Test__test_should_render_ticket_block_after_update with data set 0__1.php
  tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockV2Test__test_should_render_ticket_block_after_update with data set 1__1.php
  tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockV2Test__test_should_render_ticket_block_after_update with data set 2__1.php
  tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockV2Test__test_should_render_ticket_block_after_update with data set 3__1.php
  tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockV2Test__test_should_render_ticket_block_after_update with data set 4__1.php
  tests/wpunit/Tribe/Tickets/Commerce/RSVP/__snapshots__/RSVPBlockV2Test__test_should_render_ticket_block_after_update with data set 5__1.php
  tests/wpunit/Tribe/Tickets/RSVPTest.php
  tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set initial state__1.php
  tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set opt-in__1.php
  tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set success__1.php
Labels: merge

#2813 Fixed font sizes, icon positions, first click on the action buttons
  src/modules/blocks/rsvp/duration-label/style.pcss
  src/modules/blocks/rsvp/header-image/template.js
  src/modules/blocks/rsvp/not-going/styles.pcss
  src/modules/blocks/rsvp/settings-dashboard/template.js
  src/modules/blocks/rsvp/style.pcss
  src/modules/blocks/ticket/container-content/attendees-registration/style.pcss
  src/modules/blocks/ticket/container-content/capacity/template.js
  src/modules/blocks/ticket/container-content/title/container.js
  src/modules/blocks/ticket/container-header/price/style.pcss
  src/modules/blocks/ticket/container-header/price/template.js
  src/modules/blocks/ticket/container-header/quantity/style.pcss
  src/modules/blocks/ticket/container-header/title/attendee-registration-icons/style.pcss
  src/modules/blocks/ticket/container-header/title/container.js
  src/modules/blocks/ticket/container-header/title/style.pcss
  src/modules/blocks/tickets/availability/__tests__/__snapshots__/template.test.js.snap
  src/modules/blocks/tickets/availability/style.pcss
  src/modules/blocks/tickets/availability/template.js
  src/modules/blocks/tickets/capacity-table/row/style.pcss
  src/modules/blocks/tickets/capacity-table/style.pcss
  src/modules/blocks/tickets/header-image/style.pcss
  src/modules/data/blocks/ticket/__tests__/__snapshots__/constants.test.js.snap
  src/modules/data/blocks/ticket/constants.js
  src/modules/data/blocks/ticket/selectors.js
  src/modules/elements/action-button/__tests__/__snapshots__/element.test.js.snap
  src/modules/elements/action-button/element.js
  src/modules/elements/action-button/style.pcss
  src/modules/elements/action-dashboard/__tests__/__snapshots__/element.test.js.snap
  src/modules/elements/action-dashboard/__tests__/element.test.js
  src/modules/elements/action-dashboard/element.js
  src/modules/elements/settings-dashboard/style.pcss
  src/modules/icons/settings.svg
Labels: code review

#2814 [ET-1909] My Tickets: Fix Section Titles
  readme.txt
  src/views/tickets/orders-tc-tickets.php
Labels: code review

#2811 [ETWP-39] Move QR endpoint
  src/Tickets/QR/Connector.php
  src/Tickets/QR/Observer.php
  src/Tribe/Data_API.php
  src/Tribe/REST/V1/Documentation/QR_Definition_Provider.php
  src/Tribe/REST/V1/Endpoints/QR.php
  src/Tribe/REST/V1/Post_Repository.php
  src/Tribe/REST/V1/Service_Provider.php
  tests/_data/classes/Dummy_Endpoint.php
  tests/_support/Factories/QR.php
  tests/_support/Factories/REST/V1/QR_Response.php
  tests/_support/Testcases/QR_TestCase.php
  tests/_support/Testcases/REST/V1/QR_TestCase.php
  tests/restv1/QR/ScanCest.php
  tests/wpunit/Tribe/REST/V1/Endpoints/Single_QRTest.php
  tests/wpunit/Tribe/REST/V1/Post_RepositoryTest.php
Labels: code review

#2816 Fixed validation in limit input. Fixed tooltips
  src/modules/blocks/ticket/container-content/capacity/template.js
  src/modules/blocks/ticket/container-header/quantity/style.pcss
  src/modules/blocks/ticket/container-header/quantity/template.js
  src/modules/blocks/ticket/container-header/title/attendee-registration-icons/style.pcss
  src/modules/blocks/tickets/availability/__tests__/__snapshots__/template.test.js.snap
  src/modules/blocks/tickets/availability/style.pcss
  src/modules/blocks/tickets/availability/template.js
Labels: code review

#2810 Fixed orders title
  readme.txt
  src/Tickets/Commerce/Reports/Orders.php
Labels: code review

#2819 [ETWP-46] Wallet Plus: Restyle My Tickets Page for Passes
  src/resources/postcss/my-tickets/_orders.pcss
  src/resources/postcss/rsvp-v1.pcss
  src/views/tickets/my-tickets/attendee-label.php
Labels: code review

#2817 [ETWP-47] [ETWP-70] Include Wallet Links on EDD/Woo Confirmation/Checkout page
  src/resources/postcss/components/_all.pcss
  src/resources/postcss/components/attendees-list/_attendees.pcss
  src/views/components/attendees-list/attendees.php
  src/views/components/attendees-list/attendees/attendee.php
  src/views/components/attendees-list/attendees/title.php
  src/views/v2/commerce/order/attendees/attendee.php
  src/views/v2/commerce/order/attendees/title.php
  src/views/v2/commerce/success.php
Labels: merge

#2823 Attendees list with BEM, misc fixes.
  src/resources/postcss/components/attendees-list/_attendees.pcss
  src/views/components/attendees-list/attendees.php
  src/views/components/attendees-list/attendees/attendee.php
  src/views/components/attendees-list/title.php
Labels: code review
