Repository the-events-calendar/event-tickets, pull requests merged in 2023-09, with the labels that each got.

#2750 [ET-1799] - Series pass panel added helper text link.
  src/Tickets/Flexible_Tickets/Metabox.php
  src/Tickets/Flexible_Tickets/Series_Passes.php
  src/Tribe/Metabox.php
  src/admin-views/editor/panel/list.php
  src/admin-views/editor/panel/ticket.php
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with tickets and RSVPs__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of a series with passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of series with no passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with no passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets and no series passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets, series has passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with tickets, RSVPs and passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with RSVP__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with ticket__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with tickets and RSVPs__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event without tickets__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with RSVP__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with ticket__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event without ticket__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html
Labels: code review

#2758 Attendees Page: DQA Tweaks
  src/resources/postcss/tickets-admin/attendees/_table.pcss
Labels: code review

#2760 [ET-1815] buttons styling overrides
  readme.txt
  src/resources/postcss/tickets-commerce/_checkout.pcss
Labels: code review

#2755 Added tribe-common-full-style to tickets editor and re-styled inactive RSVP block
  readme.txt
  src/Tribe/Editor/Assets.php
  src/modules/blocks/rsvp/inactive-block/template.js
  src/modules/blocks/rsvp/style.pcss
Labels: code review

#2759 [ET-1646] - Feat - Update recurring tickets notice to match helper text notices.
  src/Tribe/Editor/Warnings.php
  src/resources/js/tickets.js
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of a series with passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of series with no passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets and no series passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets, series has passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with tickets, RSVPs and passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with RSVP__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with ticket__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with tickets and RSVPs__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event without tickets__0.snapshot.html
Labels: code review

#2761 [ET-1791] Tweak - Adjustments as per feedback.
  src/Tickets/Flexible_Tickets/Base.php
  src/Tickets/Flexible_Tickets/template-tags.php
  src/admin-views/flexible-tickets/ticket-types-column/default.php
  src/resources/postcss/tickets-admin.pcss
  tests/ft_integration/TEC/Tickets/Flexible_Tickets/__snapshots__/Series_MetaboxesTest__test_events_list with data set Series has recurring event with series pass__1.php
  tests/ft_integration/TEC/Tickets/Flexible_Tickets/__snapshots__/Series_MetaboxesTest__test_events_list with data set Series has single event with RSVP and ticket__1.php
  tests/ft_integration/TEC/Tickets/Flexible_Tickets/__snapshots__/Series_MetaboxesTest__test_events_list with data set Series has single event with RSVP ticket__1.php
  tests/ft_integration/TEC/Tickets/Flexible_Tickets/__snapshots__/Series_MetaboxesTest__test_events_list with data set Series has single event with RSVP, ticket and series pass__1.php
  tests/ft_integration/TEC/Tickets/Flexible_Tickets/__snapshots__/Series_MetaboxesTest__test_events_list with data set Series has single event with no tickets__1.php
Labels: code review

#2764 Tweak - Update series prompt notice
  src/admin-views/flexible-tickets/series-pass-event-notice.php
  tests/ft_integration/TEC/Tickets/Flexible_Tickets/Templates/__snapshots__/Admin_ViewsTest__should_render_template_correctly__series-pass-event-notice__0.snapshot.html
  tests/ft_integration/TEC/Tickets/Flexible_Tickets/Templates/__snapshots__/Admin_ViewsTest__should_render_template_correctly_when_filtering_series_pass_labels__series-pass-event-notice__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of a series with passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of series with no passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets and no series passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets, series has passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with tickets, RSVPs and passes__0.snapshot.html
Labels: code review

#2763 [ET-1841] Feat - My Tickets page view links language tweaks.
  src/Tribe/RSVP.php
  src/views/blocks/attendees/view-link.php
  src/views/tickets/view-link.php
  tests/integration/Tribe/Tickets/MyTickets/MyTicketsTest.php
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_legacy_my_tickets_view_link__event with 1 RSVP and 2 ticket purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_legacy_my_tickets_view_link__post with 1 RSVP and 1 ticket purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_legacy_my_tickets_view_link__post with 1 RSVP and 2 ticket purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_legacy_my_tickets_view_link__post with 1 rsvp purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_legacy_my_tickets_view_link__post with 1 ticket purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_legacy_my_tickets_view_link__post with 2 RSVP and 1 ticket purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_legacy_my_tickets_view_link__post with 3 RSRVP and 2 Ticket purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_legacy_my_tickets_view_link__post with 3 rsvp purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_legacy_my_tickets_view_link__post with 3 tickets purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_my_tickets_view_link__event with 1 RSVP and 2 ticket purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_my_tickets_view_link__post with 1 RSVP and 1 ticket purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_my_tickets_view_link__post with 1 RSVP and 2 ticket purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_my_tickets_view_link__post with 1 rsvp purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_my_tickets_view_link__post with 1 ticket purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_my_tickets_view_link__post with 2 RSVP and 1 ticket purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_my_tickets_view_link__post with 3 RSRVP and 2 Ticket purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_my_tickets_view_link__post with 3 rsvp purchased__0.snapshot.html
  tests/integration/Tribe/Tickets/MyTickets/__snapshots__/MyTicketsTest__test_my_tickets_view_link__post with 3 tickets purchased__0.snapshot.html
Labels: code review

#2765 Re-styled Inactive Tickets Block in Block Editor.
  readme.txt
  src/modules/blocks/rsvp/inactive-block/template.js
  src/modules/blocks/rsvp/style.pcss
  src/modules/blocks/tickets/action-buttons/settings/template.js
  src/modules/blocks/tickets/action-dashboard/template.js
  src/modules/blocks/tickets/container/container.js
  src/modules/blocks/tickets/container/style.pcss
  src/modules/blocks/tickets/container/template.js
  src/modules/blocks/tickets/dashboard/container.js
  src/modules/blocks/tickets/dashboard/template.js
  src/modules/blocks/tickets/inactive/inactive.js
  src/modules/elements/action-button/style.pcss
  src/modules/elements/action-dashboard/__tests__/__snapshots__/element.test.js.snap
  src/modules/elements/action-dashboard/element.js
  src/modules/elements/card/element.js
  src/modules/elements/card/index.js
  src/modules/elements/card/style.pcss
  src/modules/elements/index.js
  src/modules/icons/index.js
  src/modules/icons/settings.svg
Labels: code review

#2490 Correct the typo for the dev composer package name
  composer.json
Labels: merge

#2769 Re-styled inactive state with tickets
  readme.txt
  src/modules/blocks/ticket/container-header/description/style.pcss
  src/modules/blocks/ticket/container-header/price/container.js
  src/modules/blocks/ticket/container-header/price/style.pcss
  src/modules/blocks/ticket/container-header/price/template.js
  src/modules/blocks/ticket/container-header/quantity/quantity-bar/style.pcss
  src/modules/blocks/ticket/container-header/quantity/style.pcss
  src/modules/blocks/ticket/container-header/quantity/template.js
  src/modules/blocks/ticket/container-header/style.pcss
  src/modules/blocks/ticket/container-header/title/style.pcss
  src/modules/blocks/ticket/style.pcss
  src/modules/blocks/tickets/availability/__tests__/__snapshots__/template.test.js.snap
  src/modules/blocks/tickets/availability/style.pcss
  src/modules/blocks/tickets/availability/template.js
  src/modules/blocks/tickets/container/container.js
  src/modules/blocks/tickets/container/style.pcss
  src/modules/blocks/tickets/container/template.js
  src/modules/blocks/tickets/inactive/inactive.js
  src/modules/blocks/tickets/style.pcss
  src/modules/elements/action-button/style.pcss
  src/modules/elements/action-dashboard/style.pcss
  src/modules/elements/card/element.js
  src/modules/elements/card/style.pcss
  src/modules/elements/container-panel/__tests__/__snapshots__/element.test.js.snap
  src/modules/elements/container-panel/element.js
  src/modules/elements/container-panel/style.pcss
  src/modules/icons/attendees.svg
  src/modules/icons/orders.svg
Labels: code review

#2774 [ET-1784] My Tickets: Redesign
  src/Tribe/Assets.php
  src/Tribe/Tickets_View.php
  src/resources/postcss/my-tickets/_orders.pcss
  src/resources/postcss/rsvp-v1.pcss
  src/resources/postcss/tpp.pcss
  src/views/tickets/my-tickets.php
  src/views/tickets/my-tickets/attendee-label.php
  src/views/tickets/my-tickets/orders-list.php
  src/views/tickets/my-tickets/ticket-information.php
  src/views/tickets/my-tickets/tickets-list.php
  src/views/tickets/my-tickets/title.php
  src/views/tickets/my-tickets/user-details.php
  src/views/tickets/orders-pp-tickets.php
  src/views/tickets/orders-rsvp.php
  src/views/tickets/orders-tc-tickets.php
  src/views/tickets/orders.php
Labels: code review

#2780 [ET-1875] Tickets Emails: Fix Status showing incorrectly in other languages
  readme.txt
  src/Tickets/Commerce/Models/Order_Model.php
  src/Tickets/Emails/Admin/Preview_Data.php
  src/views/emails/template-parts/body/order/payment-info.php
Labels: code review, merge

#2783 Enhancement/ET-1835 add/edit ticket re style
  readme.txt
  src/modules/blocks/ticket/container-content/advanced-options/move-delete/__tests__/__snapshots__/template.test.js.snap
  src/modules/blocks/ticket/container-content/advanced-options/template.js
  src/modules/blocks/ticket/container-content/attendee-collection/style.pcss
  src/modules/blocks/ticket/container-content/attendees-registration/style.pcss
  src/modules/blocks/ticket/container-content/capacity/style.pcss
  src/modules/blocks/ticket/container-content/capacity/template.js
  src/modules/blocks/ticket/container-content/description/__tests__/__snapshots__/template.test.js.snap
  src/modules/blocks/ticket/container-content/description/__tests__/template.test.js
  src/modules/blocks/ticket/container-content/description/container.js
  src/modules/blocks/ticket/container-content/description/styles.pcss
  src/modules/blocks/ticket/container-content/description/template.js
  src/modules/blocks/ticket/container-content/duration/style.pcss
  src/modules/blocks/ticket/container-content/price/__tests__/__snapshots__/template.test.js.snap
  src/modules/blocks/ticket/container-content/price/__tests__/template.test.js
  src/modules/blocks/ticket/container-content/price/container.js
  src/modules/blocks/ticket/container-content/price/style.pcss
  src/modules/blocks/ticket/container-content/price/template.js
  src/modules/blocks/ticket/container-content/style.pcss
  src/modules/blocks/ticket/container-content/template.js
  src/modules/blocks/ticket/container-content/title/__tests__/__snapshots__/template.test.js.snap
  src/modules/blocks/ticket/container-content/title/__tests__/template.test.js
  src/modules/blocks/ticket/container-content/title/container.js
  src/modules/blocks/ticket/container-content/title/styles.pcss
  src/modules/blocks/ticket/container-content/title/template.js
  src/modules/blocks/ticket/container-header/template.js
  src/modules/blocks/ticket/container-header/title/template.js
  src/modules/blocks/ticket/dashboard/move-delete/__tests__/__snapshots__/template.test.js.snap
  src/modules/blocks/ticket/dashboard/move-delete/__tests__/template.test.js
  src/modules/blocks/ticket/dashboard/move-delete/container.js
  src/modules/blocks/ticket/dashboard/move-delete/style.pcss
  src/modules/blocks/ticket/dashboard/move-delete/template.js
  src/modules/blocks/ticket/dashboard/style.pcss
  src/modules/blocks/ticket/dashboard/template.js
  src/modules/blocks/ticket/style.pcss
  src/modules/blocks/tickets/container/container.js
  src/modules/blocks/tickets/container/template.js
  src/modules/elements/action-dashboard/style.pcss
  src/modules/elements/attendees-registration/style.pcss
  src/modules/elements/card/style.pcss
  src/modules/elements/container-panel/style.pcss
  src/modules/elements/date-time-range-picker/style.pcss
  src/modules/elements/label-with-tooltip/style.pcss
Labels: code review

#2781 Include a new Facade that handles QR code properly for WordPress
  .gitignore
  composer.json
  composer.lock
  package-safelist.json
  readme.txt
  src/Tickets/Provider.php
  src/Tickets/QR/Controller.php
  src/Tickets/QR/QR.php
  tests/integration/TEC/Tickets/QR/QR_Test.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_base64 with data set should_allow_basic_url__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_base64 with data set should_allow_folder_usage__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_base64 with data set should_allow_json_encoded__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_base64 with data set should_allow_json_encodeded__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_base64 with data set should_allow_random_text__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_base64 with data set should_allow_url_with_query_args__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_file with data set should_allow_basic_url__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_file with data set should_allow_folder_usage__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_file with data set should_allow_json_encoded__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_file with data set should_allow_random_text__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_file with data set should_allow_url_with_query_args__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_string with data set should_allow_basic_url__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_string with data set should_allow_folder_usage__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_string with data set should_allow_json_encoded__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_string with data set should_allow_json_encodeded__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_string with data set should_allow_random_text__1.php
  tests/integration/TEC/Tickets/QR/__snapshots__/QR_Test__should_create_png_as_string with data set should_allow_url_with_query_args__1.php
  vendor/phpqrcode/LICENSE
  vendor/phpqrcode/qrbitstream.php
  vendor/phpqrcode/qrconfig.php
  vendor/phpqrcode/qrconst.php
  vendor/phpqrcode/qrencode.php
  vendor/phpqrcode/qrimage.php
  vendor/phpqrcode/qrinput.php
  vendor/phpqrcode/qrlib.php
  vendor/phpqrcode/qrmask.php
  vendor/phpqrcode/qrrscode.php
  vendor/phpqrcode/qrspec.php
  vendor/phpqrcode/qrsplit.php
  vendor/phpqrcode/qrtools.php
Labels: code review

#2784 [ETP-866] Shared Capacity Incorrect when moving tickets (Tickets Commerce)
  readme.txt
  src/Tickets/Commerce/Ticket.php
  tests/commerce_integration/TEC/Admin/MoveTicketsTest.php
Labels: code review

#2789 Removing Comment to fix build process.
  src/modules/elements/attendees-registration/style.pcss
Labels: code review
