Repository the-events-calendar/event-tickets, pull requests merged in 2023-01, with the labels that each got.

#2533 [ET-1603] PQA update - Update text for Pending order stock handler
  src/Tickets/Commerce/Settings.php
Labels: merge

#2529 Fix handling some provisional IDs.
  readme.txt
  src/Tickets/Commerce/Repositories/Attendees_Repository.php
  src/Tickets/Custom_Tables/V1/Provider.php
  src/Tickets/Event.php
  src/Tribe/Abstract_Attendance_Totals.php
  src/Tribe/Attendees_Table.php
  src/Tribe/Main.php
  src/Tribe/Ticket_Repository.php
  tests/_support/Ct1_integrationTester.php
  tests/_support/Helper/Ct1_integration.php
  tests/_support/Traits/CT1/CT1_Fixtures.php
  tests/_support/Traits/CT1/CT1_Test_Utils.php
  tests/ct1_integration.suite.dist.yml
  tests/ct1_integration/Attendees_TableTest.php
  tests/ct1_integration/_bootstrap.php
Labels: code review

#2518 [ET-1551] New Email Template files and styling
  src/Tickets/Emails/Email_Template.php
  src/admin-views/settings/emails/email-template.php
  src/admin-views/settings/emails/email-template/body.php
  src/admin-views/settings/emails/email-template/body/add-links.php
  src/admin-views/settings/emails/email-template/body/date.php
  src/admin-views/settings/emails/email-template/body/event-description.php
  src/admin-views/settings/emails/email-template/body/event-image.php
  src/admin-views/settings/emails/email-template/body/event-location.php
  src/admin-views/settings/emails/email-template/body/event-title.php
  src/admin-views/settings/emails/email-template/body/footer-content.php
  src/admin-views/settings/emails/email-template/body/footer-credit.php
  src/admin-views/settings/emails/email-template/body/footer.php
  src/admin-views/settings/emails/email-template/body/greeting.php
  src/admin-views/settings/emails/email-template/body/header-image.php
  src/admin-views/settings/emails/email-template/body/header.php
  src/admin-views/settings/emails/email-template/body/qr-image.php
  src/admin-views/settings/emails/email-template/body/recipient-name.php
  src/admin-views/settings/emails/email-template/body/ticket-info.php
  src/admin-views/settings/emails/email-template/body/top-link.php
  src/admin-views/settings/emails/email-template/main.php
  src/admin-views/settings/emails/email-template/preview.php
  src/admin-views/settings/emails/email-template/style.php
  src/resources/icons/link.svg
  src/resources/icons/map-pin.svg
  src/resources/icons/phone.svg
  src/resources/images/example-event-image.png
  src/resources/images/example-qr.png
Labels: code review

#2521 [ET-1547] Tickets Emails > Modal Preview
  src/Tickets/Emails/Admin/Preview_Modal.php
  src/Tickets/Emails/Assets.php
  src/Tickets/Emails/Email_Template.php
  src/Tickets/Emails/Emails_Tab.php
  src/Tickets/Emails/Hooks.php
  src/Tickets/Emails/Provider.php
  src/Tickets/Emails/Settings.php
  src/admin-views/settings/emails/email-template/body.php
  src/admin-views/settings/emails/email-template/body/add-links.php
  src/admin-views/settings/emails/email-template/body/date.php
  src/admin-views/settings/emails/email-template/body/event-description.php
  src/admin-views/settings/emails/email-template/body/event-image.php
  src/admin-views/settings/emails/email-template/body/event-location.php
  src/admin-views/settings/emails/email-template/body/event-title.php
  src/admin-views/settings/emails/email-template/body/footer-content.php
  src/admin-views/settings/emails/email-template/body/footer-credit.php
  src/admin-views/settings/emails/email-template/body/footer.php
  src/admin-views/settings/emails/email-template/body/greeting.php
  src/admin-views/settings/emails/email-template/body/header-image.php
  src/admin-views/settings/emails/email-template/body/header.php
  src/admin-views/settings/emails/email-template/body/qr-image.php
  src/admin-views/settings/emails/email-template/body/recipient-name.php
  src/admin-views/settings/emails/email-template/body/ticket-info.php
  src/admin-views/settings/emails/email-template/body/top-link.php
  src/admin-views/settings/emails/email-template/main.php
  src/admin-views/settings/emails/email-template/preview.php
  src/admin-views/settings/emails/email-template/style.php
  src/resources/js/admin/tickets-emails.js
  src/resources/postcss/tickets-admin/settings/_emails.pcss
Labels: code review

#2538 Fix parsing provisional IDs on event edit screen.
  .github/workflows/tests-php.yml
  readme.txt
  src/Tribe/Metabox.php
  tests/_support/Traits/CT1/CT1_Fixtures.php
  tests/ct1_integration.suite.dist.yml
  tests/ct1_integration/Attendees_TableTest.php
  tests/ct1_integration/MetaboxTest.php
Labels: code review, merge

#2540 ETP Tickets Emails Settings
  src/Tickets/Emails/Email_Template.php
  src/Tickets/Emails/Settings.php
  src/admin-views/settings/emails/email-template/body/qr-image.php
  src/resources/images/example-qr.png
  src/views/v2/emails/email-template.php
  src/views/v2/emails/email-template/body.php
  src/views/v2/emails/email-template/body/add-links.php
  src/views/v2/emails/email-template/body/date.php
  src/views/v2/emails/email-template/body/event-description.php
  src/views/v2/emails/email-template/body/event-image.php
  src/views/v2/emails/email-template/body/event-location.php
  src/views/v2/emails/email-template/body/event-title.php
  src/views/v2/emails/email-template/body/footer-content.php
  src/views/v2/emails/email-template/body/footer-credit.php
  src/views/v2/emails/email-template/body/footer.php
  src/views/v2/emails/email-template/body/greeting.php
  src/views/v2/emails/email-template/body/header-image.php
  src/views/v2/emails/email-template/body/header.php
  src/views/v2/emails/email-template/body/recipient-name.php
  src/views/v2/emails/email-template/body/ticket-info.php
  src/views/v2/emails/email-template/body/top-link.php
  src/views/v2/emails/email-template/main.php
  src/views/v2/emails/email-template/preview.php
  src/views/v2/emails/email-template/style.php
Labels: code review

#2544 Upgrade Composer to v2
  .github/workflows/zip.yml
  composer.json
  composer.lock
  src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss
Labels: code review
