Repository the-events-calendar/event-tickets, pull requests merged in 2023-05, with the labels that each got.

#2619 Update to avoid creating more bloat on main Module files
  src/Tickets/Emails/Email_Abstract.php
  src/Tickets/Emails/Email_Sender.php
  src/Tickets/Emails/Hooks.php
  src/Tickets/Emails/Legacy.php
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
Labels: code review, needs tests

#2611 Tickets Emails - Dynamizing Attendees & Improving Placeholders
  src/Tickets/Commerce/Flag_Actions/Send_Email_Completed_Order.php
  src/Tickets/Commerce/Flag_Actions/Send_Email_Purchase_Receipt.php
  src/Tickets/Emails/Admin/Preview_Data.php
  src/Tickets/Emails/Admin/Preview_Modal.php
  src/Tickets/Emails/Email/Completed_Order.php
  src/Tickets/Emails/Email/Purchase_Receipt.php
  src/Tickets/Emails/Email/Ticket.php
  src/Tickets/Emails/Email_Abstract.php
  src/views/v2/emails/template-parts/body/order/attendees-table/attendee-email.php
  src/views/v2/emails/template-parts/body/order/attendees-table/attendee-name.php
  src/views/v2/emails/template-parts/body/order/attendees-table/ticket-id.php
  src/views/v2/emails/template-parts/body/order/attendees-table/ticket-title.php
  src/views/v2/emails/template-parts/body/ticket/holder-name.php
  src/views/v2/emails/template-parts/body/ticket/security-code.php
  src/views/v2/emails/template-parts/body/ticket/ticket-name.php
Labels: merge

#2624 fixes preview issues
  src/Tickets/Emails/Admin/Preview_Data.php
  src/Tickets/Emails/Admin/Preview_Modal.php
Labels: code review

#2618 [ET-1623] Tickets Emails: Fix tooltip in RSVP email settings
  src/Tickets/Emails/Email/RSVP.php
Labels: merge

#2626 Rest API tests passing
  .github/new-workflows/tests-php.yml
  .github/workflows/tests-php.yml
  src/Tickets/Emails/Provider.php
  tests/restv1/PayPal/SingleTicketCest.php
  tests/restv1/PayPal/TicketArchiveByPostCest.php
  tests/restv1/RSVP/SingleTicketCest.php
  tests/restv1/RSVP/TicketArchiveByPostCest.php
Labels: code review

#2627 Address code review requests to Dispatcher from Original PR #2621
  src/Tickets/Emails/Dispatcher.php
Labels: code review

#2625 Move non-attendance email to Tickets Emails codebase
  src/Tickets/Commerce/Order.php
  src/Tickets/Emails/Hooks.php
  src/Tickets/Emails/Legacy_Hijack.php
  src/Tribe/RSVP.php
  tests/commerce_integration/_bootstrap.php
  tests/integration/Tribe/Tickets/Commerce/PayPal/PayPalTest.php
Labels: code review

#2632 Update emails descriptions, use new link for the tickets emails docs.
  src/Tickets/Emails/Email/Completed_Order.php
  src/Tickets/Emails/Email/Purchase_Receipt.php
  src/Tickets/Emails/Email/RSVP.php
  src/Tickets/Emails/Email/RSVP_Not_Going.php
  src/Tickets/Emails/Email/Ticket.php
Labels: code review

#2630 Make $tickets a Lazy_Collection in the Order_Model
  readme.txt
  src/Tickets/Commerce/Models/Order_Model.php
Labels: code review

#2633 [ET-1698] Fix - Glance items attendee count performance issue.
  readme.txt
  src/Tickets/Admin/Glance_Items.php
  src/Tickets/Admin/Provider.php
Labels: code review

#2628 Adding Tests to Tickets Emails
  src/Tickets/Commerce/Models/Order_Model.php
  src/Tickets/Emails/Admin/Emails_Tab.php
  src/Tickets/Emails/Admin/Preview_Data.php
  src/Tickets/Emails/Admin/Preview_Modal.php
  src/Tickets/Emails/Email/Completed_Order.php
  src/Tickets/Emails/Email/Purchase_Receipt.php
  src/Tickets/Emails/Email/RSVP.php
  src/Tickets/Emails/Email/RSVP_Not_Going.php
  src/Tickets/Emails/Email/Ticket.php
  src/Tickets/Emails/Email_Abstract.php
  src/Tickets/Emails/Hooks.php
  src/Tickets/Emails/Legacy_Hijack.php
  src/Tickets/Emails/Post_Type.php
  src/Tickets/Emails/Provider.php
  src/resources/js/admin/tickets-emails.js
  src/views/v2/emails/template-parts/body/order/payment-info.php
  src/views/v2/emails/template-parts/body/order/purchaser-details/date.php
  src/views/v2/emails/template-parts/body/order/ticket-totals.php
  src/views/v2/emails/template-parts/body/order/ticket-totals/ticket-price.php
  src/views/v2/emails/template-parts/body/order/ticket-totals/ticket-quantity.php
  src/views/v2/emails/template-parts/body/order/ticket-totals/ticket-row.php
  src/views/v2/emails/template-parts/body/order/ticket-totals/ticket-title.php
  tests/_support/Emails/Email/Dummy_Email.php
  tests/integration/TEC/Tickets/Emails/Admin/Emails_TabTest.php
  tests/integration/TEC/Tickets/Emails/Admin/Preview_ModalTest.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_general_settings__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings_with_invalid_id__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_modal_button__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_modal_content__1.php
  tests/integration/TEC/Tickets/Emails/Post_TypeTest.php
Labels: code review

#2636 On the Completed Email and Purchase Receipt pass the correct order ID.
  src/Tickets/Commerce/Flag_Actions/Send_Email_Completed_Order.php
  src/Tickets/Commerce/Flag_Actions/Send_Email_Purchase_Receipt.php
  src/Tickets/Commerce/Module.php
Labels: code review

#2607 [ET-1637] Enhancement - Add JSON LD data for Ticket, RSVP, Completed and Purchaser receipt emails
  readme.txt
  src/Tickets/Emails/Admin/Preview_Data.php
  src/Tickets/Emails/Email/Completed_Order.php
  src/Tickets/Emails/Email/Purchase_Receipt.php
  src/Tickets/Emails/Email/RSVP.php
  src/Tickets/Emails/Email/Ticket.php
  src/Tickets/Emails/JSON_LD/Event_Schema.php
  src/Tickets/Emails/JSON_LD/JSON_LD_Abstract.php
  src/Tickets/Emails/JSON_LD/Order_Schema.php
  src/Tickets/Emails/JSON_LD/Preview_Schema.php
  src/Tickets/Emails/JSON_LD/Reservation_Schema.php
  src/views/v2/emails/template-parts/header/head/json-ld.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
Labels: merge

#2634 Tickets Emails: DQA Modifications
  src/Tickets/Emails/Admin/Emails_Tab.php
  src/Tickets/Emails/Admin/Settings.php
  src/Tickets/Emails/Email/Completed_Order.php
  src/Tickets/Emails/Email/Purchase_Receipt.php
  src/Tickets/Emails/Email/RSVP.php
  src/Tickets/Emails/Email/RSVP_Not_Going.php
  src/Tickets/Emails/Email/Ticket.php
  src/resources/postcss/tickets-admin/settings/_emails.pcss
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_general_settings__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
Labels: code review

#2642 [ET-1734] Tickets Emails: Various DQA CSS Tweaks - Part 2
  src/views/emails/template-parts/header/head/styles.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
Labels: merge

#2635 Tickets Emails > Make preview responsive to context
  src/Tickets/Emails/Admin/Preview_Modal.php
  src/resources/js/admin/tickets-emails.js
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
Labels: code review

#2645 Tickets Emails: Remove Plural Settings and Set New Defaults
  src/Tickets/Emails/Email/RSVP.php
  src/Tickets/Emails/Email/Ticket.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_rsvp_without_using_ticket_settings__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
Labels: code review

#2646 [ET-1734] Tickets Emails: Modify Enabled Labels
  src/Tickets/Emails/Email/Completed_Order.php
  src/Tickets/Emails/Email/Purchase_Receipt.php
  src/Tickets/Emails/Email/RSVP.php
  src/Tickets/Emails/Email/RSVP_Not_Going.php
  src/Tickets/Emails/Email/Ticket.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_rsvp_without_using_ticket_settings__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
Labels: code review

#2640 Tickets Emails > Remove unused templates, add info to WP.org page
  readme.txt
  src/views/emails/admin-failed-order.php
  src/views/emails/failed-order/body.php
  src/views/emails/template.php
Labels: code review

#2647 Notices for Tickets Emails
  src/Tickets/Emails/Admin/Notice_Extension.php
  src/Tickets/Emails/Admin/Notice_Upgrade.php
  src/Tickets/Emails/Provider.php
Labels: code review

#2648 Fix - Misc php notices fixed.
  src/Tickets/Commerce/Gateways/Stripe/Gateway.php
  src/Tickets/Emails/Admin/Preview_Modal.php
  src/Tribe/RSVP.php
  src/resources/js/admin/tickets-emails.js
  tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set ari__1.php
Labels: code review

#2650 Fix - Include ARF and QR Code into general email preview.
  src/resources/js/admin/tickets-emails.js
Labels: code review

#2652 Tickets Emails > Adjust description and add missing link to KB
  src/Tickets/Emails/Admin/Emails_Tab.php
Labels: code review

#2654 Rename from `add-content` to `additional-content` and include in all emails.
  src/Tickets/Emails/Email/Completed_Order.php
  src/Tickets/Emails/Email/Purchase_Receipt.php
  src/Tickets/Emails/Email/RSVP.php
  src/Tickets/Emails/Email/RSVP_Not_Going.php
  src/Tickets/Emails/Email/Ticket.php
  src/Tickets/Emails/Email_Abstract.php
  src/resources/js/admin/tickets-emails.js
  src/views/emails/new-order/body.php
  src/views/emails/purchase-receipt/body.php
  src/views/emails/rsvp-not-going/body.php
  src/views/emails/rsvp/body.php
  src/views/emails/template-parts/body/additional-content.php
  src/views/emails/template-parts/header/head/styles.php
  src/views/emails/ticket/body.php
  tests/integration/TEC/Tickets/Emails/Admin/Emails_TabTest.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_general_settings__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_rsvp_without_using_ticket_settings__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
Labels: code review

#2655 [ET-1627] Tickets Emails: Template Snapshot Testing
  tests/integration/TEC/Tickets/Emails/TemplateTest.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php
Labels: merge

#2656 Fixing RestV1 tests
  .github/workflows/tests-php.yml
  tests/restv1/PayPal/SingleTicketCest.php
  tests/restv1/PayPal/TicketArchiveByPostCest.php
  tests/restv1/RSVP/SingleTicketCest.php
  tests/restv1/RSVP/TicketArchiveByPostCest.php
Labels: code review

#2657 Tickets Emails: Preview Button Styling Tweaks
  src/resources/postcss/tickets-admin/settings/_emails.pcss
Labels: code review

#2658 [TE-6DB9] Fix -Ticket Emails settings live preview for Footer content and additional content.
  src/resources/js/admin/tickets-emails.js
Labels: code review

#2659 Replace placeholders everywhere in the Email
  src/Tickets/Emails/Email_Abstract.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php
Labels: code review

#2653 [ET-1696] 'No provider message' does not display properly when providers are disabled.
  readme.txt
  src/Tribe/Editor/Warnings.php
  src/resources/js/tickets.js
  tests/wpunit/Tribe/Editor/WarningsTest.php
  tests/wpunit/Tribe/Editor/__snapshots__/WarningsTest__render_notice_display_correctly with data set Test with all values filled__1.php
  tests/wpunit/Tribe/Editor/__snapshots__/WarningsTest__render_notice_display_correctly with data set Test with blank additionalClasses__1.php
  tests/wpunit/Tribe/Editor/__snapshots__/WarningsTest__render_notice_display_correctly with data set Test with blank condition__1.php
  tests/wpunit/Tribe/Editor/__snapshots__/WarningsTest__render_notice_display_correctly with data set Test with blank depends_on__1.php
  tests/wpunit/Tribe/Editor/__snapshots__/WarningsTest__render_notice_display_correctly with data set Test with blank message__1.php
  tests/wpunit/Tribe/Editor/__snapshots__/WarningsTest__render_notice_display_correctly with data set Test with blank type__1.php
Labels: code review

#2663 [TE-EC26] Fix - Toggling Use Ticket Email option should not remove other field's data.
  src/Tickets/Emails/Admin/Preview_Modal.php
  src/Tickets/Emails/Email/RSVP.php
  src/Tickets/Emails/Hooks.php
Labels: code review, merge

#2664 Tickets Emails: Modify Enabled Toggle for all Emails
  src/Tickets/Emails/Email/Completed_Order.php
  src/Tickets/Emails/Email/Purchase_Receipt.php
  src/Tickets/Emails/Email/RSVP.php
  src/Tickets/Emails/Email/RSVP_Not_Going.php
  src/Tickets/Emails/Email/Ticket.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_rsvp_without_using_ticket_settings__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set ticket__1.php
Labels: code review

#2666 [TE-31DB] Fix - Apply contrast text color for live preview.
  src/Tickets/Emails/Admin/Preview_Modal.php
Labels: code review

#2668 Tickets Emails: Additional Content Fixes
  src/Tickets/Emails/Admin/Preview_Modal.php
  src/views/emails/template-parts/header/head/styles.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php
Labels: code review, merge

#2665 Tickets Emails: RSVP should use Ticket context when applicable
  src/Tickets/Emails/Email/RSVP.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php
Labels: merge

#2639 [ET-1737] Orders Page has incorrect Titles
  readme.txt
  src/Tickets/Commerce/Reports/Orders.php
  src/Tribe/Commerce/Orders_Tabbed_View.php
  tests/wpunit/Tickets/Commerce/Reports/OrdersTest.php
Labels: code review

#2670 Tickets Emails Issue TE-DECF: Add Space Below Not Going Text
  src/views/emails/rsvp-not-going/body.php
  src/views/emails/template-parts/header/head/styles.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php
Labels: code review, merge

#2671 Tickets Emails: Mobile Styling Tweaks
  src/views/emails/template-parts/header/head/styles.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php
Labels: merge
