Repository the-events-calendar/event-tickets, pull requests merged in 2023-06, with the labels that each got.

#2672 Use the gateway ID instead of Order->ID
  src/Tickets/Emails/Admin/Preview_Data.php
  src/Tickets/Emails/Email/Completed_Order.php
  src/Tickets/Emails/Email/Purchase_Receipt.php
  src/views/emails/new-order/body.php
  src/views/emails/template-parts/body/order/order-gateway-data.php
  src/views/emails/template-parts/body/order/order-total.php
  src/views/emails/template-parts/body/order/purchaser-details/order-number.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
Labels: code review

#2675 TE-1732 Tickets Emails: Mobile Ticket Styling
  src/views/emails/template-parts/body/ticket/holder-name.php
  src/views/emails/template-parts/body/ticket/security-code.php
  src/views/emails/template-parts/body/ticket/ticket-name.php
  src/views/emails/template-parts/body/tickets.php
  src/views/emails/template-parts/header/head/styles.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php
Labels: code review

#2673 Improvements to site_address and site_url placeholders for Emails.
  src/Tickets/Emails/Admin/Preview_Data.php
  src/Tickets/Emails/Admin/Preview_Modal.php
  src/Tickets/Emails/Email_Abstract.php
Labels: code review

#2677 TE-7ACB Tickets Emails: Set Additional Content Field Sizes to Large
  src/Tickets/Emails/Email/Completed_Order.php
  src/Tickets/Emails/Email/Purchase_Receipt.php
  src/Tickets/Emails/Email/RSVP_Not_Going.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Emails_TabTest__it_should_match_stored_json_for_settings with data set rsvp-not-going__1.php
Labels: code review

#2674 [ET-1767] Attendee Registration Loop issue on certain themes.
  readme.txt
  src/Tribe/Attendee_Registration/Template.php
Labels: code review

#2681 TE-21E0 Fix Styling Issues on Gmail
  src/views/emails/template-parts/body/tickets.php
  src/views/emails/template-parts/header/head/styles.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php
Labels: code review

#2682 Tickets Emails: CSS Tweak
  src/views/emails/template-parts/header/head/styles.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php
Labels: merge

#2676 [ET-1729] Refactor - Move the methods from the Gateway into the Order controller
  src/Tickets/Commerce/Abstract_Order.php
  src/Tickets/Commerce/Admin_Tables/Orders.php
  src/Tickets/Commerce/Gateways/Contracts/Abstract_Gateway.php
  src/Tickets/Commerce/Gateways/Contracts/Gateway_Interface.php
  src/Tickets/Commerce/Gateways/Manual/Gateway.php
  src/Tickets/Commerce/Gateways/PayPal/Gateway.php
  src/Tickets/Commerce/Gateways/PayPal/Order.php
  src/Tickets/Commerce/Gateways/Stripe/Gateway.php
  src/Tickets/Commerce/Gateways/Stripe/Order.php
  src/views/emails/template-parts/body/order/order-gateway-data.php
Labels: code review

#2683 Updating Snapshots to Fix Tests
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php
Labels: code review

#2684 TE-40EB Tickets Emails: Update Excerpt Styling
  src/views/emails/template-parts/header/head/styles.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/Admin/__snapshots__/Preview_ModalTest__it_should_match_snapshot_for_individual_email_preview with data set ticket__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set completed-order__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set purchase-receipt__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp-not-going__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set rsvp__1.php
  tests/integration/TEC/Tickets/Emails/__snapshots__/TemplateTest__it_should_match_snapshot with data set ticket__1.php
Labels: code review

#2687 Ensure that Sandbox JS also uses the production JS
  readme.txt
  src/Tickets/Commerce/Gateways/PayPal/Assets.php
  src/Tickets/Commerce/Gateways/PayPal/Client.php
Labels: code review, needs artifact

#2691 Attendee Registration needs to be in a try/catch
  src/Tribe/Attendee_Registration/Rewrite.php
  src/Tribe/Attendee_Registration/Service_Provider.php
  src/Tribe/Attendee_Registration/Template.php
  src/Tribe/Tickets.php
  src/views/registration/content.php
Labels: code review

#2689 [ET-1737] Spotfix - EDD Not displaying proper title.
  src/Tribe/Commerce/Orders_Tabbed_View.php
Labels: code review

#2699 Preventing fatals reported by customers on WP.org
  src/Tribe/Status/Manager.php
Labels: code review

#2700 Move from tad_DI52_ServiceProvider to Service Provider Contract
  src/Tickets/Admin/Hooks.php
  src/Tickets/Admin/Provider.php
  src/Tickets/Assets.php
  src/Tickets/Commerce/Admin/Notices.php
  src/Tickets/Commerce/Assets.php
  src/Tickets/Commerce/Flag_Actions/Flag_Action_Handler.php
  src/Tickets/Commerce/Gateways/Manual/Assets.php
  src/Tickets/Commerce/Gateways/Manual/Hooks.php
  src/Tickets/Commerce/Gateways/Manual/Provider.php
  src/Tickets/Commerce/Gateways/PayPal/Assets.php
  src/Tickets/Commerce/Gateways/PayPal/Hooks.php
  src/Tickets/Commerce/Gateways/PayPal/Provider.php
  src/Tickets/Commerce/Gateways/PayPal/REST.php
  src/Tickets/Commerce/Gateways/Stripe/Assets.php
  src/Tickets/Commerce/Gateways/Stripe/Hooks.php
  src/Tickets/Commerce/Gateways/Stripe/Provider.php
  src/Tickets/Commerce/Gateways/Stripe/REST.php
  src/Tickets/Commerce/Hooks.php
  src/Tickets/Commerce/Legacy_Compat.php
  src/Tickets/Commerce/Payments_Tab.php
  src/Tickets/Commerce/Provider.php
  src/Tickets/Commerce/Status/Status_Handler.php
  src/Tickets/Custom_Tables/V1/Migration/Maintenance_Mode/Provider.php
  src/Tickets/Custom_Tables/V1/Provider.php
  src/Tickets/Emails/Assets.php
  src/Tickets/Emails/Email_Handler.php
  src/Tickets/Emails/Hooks.php
  src/Tickets/Emails/Provider.php
  src/Tickets/Hooks.php
  src/Tickets/Provider.php
  src/Tickets/Recurrence/Hooks.php
  src/Tickets/Recurrence/Provider.php
  src/Tickets/Site_Health/Provider.php
  src/Tribe/Admin/Home/Service_Provider.php
  src/Tribe/Admin/Manager/Service_Provider.php
  src/Tribe/Admin/Provider.php
  src/Tribe/Admin/Settings/Service_Provider.php
  src/Tribe/Attendee_Registration/Service_Provider.php
  src/Tribe/Editor/Provider.php
  src/Tribe/Editor/REST/V1/Service_Provider.php
  src/Tribe/Events/Service_Provider.php
  src/Tribe/Events/Views/V2/Hooks.php
  src/Tribe/Events/Views/V2/Service_Provider.php
  src/Tribe/Promoter/Service_Provider.php
  src/Tribe/REST/V1/Service_Provider.php
  src/Tribe/Service_Provider.php
  src/Tribe/Service_Providers/Customizer.php
  src/Tribe/Service_Providers/ORM.php
Labels: code review

#2701 Fix event tickets emails overrides not working.
  readme.txt
  src/Tickets/Emails/Email_Template.php
Labels: merge

#2706 [ET-1764] Add notice and documentation for Paystack
  readme.txt
  src/Tribe/Admin/Notices.php
Labels: code review

#2705 [ET-1736] Check Ajax Before Stripe Errors
  readme.txt
  src/Tickets/Commerce/Gateways/Stripe/Hooks.php
Labels: code review
