Repository the-events-calendar/event-tickets, pull requests merged in 2023-03, with the labels that each got.

#2559 Fix - removed cart clear from cart save process to avoid empty cart.
  src/Tickets/Commerce/Cart.php
  src/Tickets/Commerce/Cart/Unmanaged_Cart.php
Labels: code review, merge

#2561 [ET-1645] Fix placeholder for translation on the Tickets Settings title.
  readme.txt
  src/Tribe/Admin/Settings.php
Labels: code review

#2550 [ET-1368] Tickets Emails > Classes for emails, CPT, etc.
  src/Tickets/Emails/Admin/Emails_Tab.php
  src/Tickets/Emails/Admin/Settings.php
  src/Tickets/Emails/Email/Ticket.php
  src/Tickets/Emails/Email_Abstract.php
  src/Tickets/Emails/Email_Handler.php
  src/Tickets/Emails/Email_Sender.php
  src/Tickets/Emails/Hooks.php
  src/Tickets/Emails/Provider.php
  src/Tribe/Admin/Settings.php
Labels: code review, merge

#2555 [ET-1599] Auto Generate Default Emails and Email Settings
  src/Tickets/Emails/Admin/Emails_Tab.php
  src/Tickets/Emails/Admin/Settings.php
  src/Tickets/Emails/Email/Ticket.php
  src/Tickets/Emails/Email_Abstract.php
  src/Tickets/Emails/Email_Handler.php
  src/Tickets/Emails/Hooks.php
  src/admin-views/settings/back-link.php
  src/admin-views/settings/emails/message-templates.php
  src/admin-views/settings/emails/message-templates/list-action.php
  src/admin-views/settings/emails/message-templates/list-icon.php
  src/admin-views/settings/emails/message-templates/list-item.php
  src/admin-views/settings/emails/message-templates/list-recipient.php
  src/admin-views/settings/emails/message-templates/list-title.php
  src/resources/postcss/tickets-admin-settings.pcss
  src/resources/postcss/tickets-admin/settings/_all.pcss
Labels: code review

#2564 [ET-1654] Add the Attendee count for the site to the `At a Glance` admin widget.
  readme.txt
  src/Tickets/Admin/Glance_Items.php
  src/Tickets/Admin/Hooks.php
  src/Tribe/Assets.php
  src/resources/postcss/tickets-admin-wp.pcss
Labels: code review

#2565 Fix race condition. Update version in package lock
  package-lock.json
  src/Tribe/Main.php
Labels: merge

#2570 [ET-1678] Fix - Fixed showing unlimited tickets as sold out on calendar views
  readme.txt
  src/Tribe/Tickets.php
  tests/commerce_integration/TEC/Tickets/Commerce/Stock/EventStockTest.php
Labels: code review

#2572 Prevent fatal for non-admin users.
  readme.txt
  src/Tribe/Attendees_Table.php
Labels: code review

#2568 Tickets Emails: New Emails and Settings
  src/Tickets/Emails/Email/Completed_Order.php
  src/Tickets/Emails/Email/Failed_Order.php
  src/Tickets/Emails/Email/Purchase_Receipt.php
  src/Tickets/Emails/Email/Ticket.php
  src/Tickets/Emails/Email_Abstract.php
  src/Tickets/Emails/Email_Handler.php
  src/views/v2/emails/customer-purchase-receipt.php
Labels: code review

#2574 [ET-1617] Tickets Emails > Toggle and backwards compatibility
  src/Tickets/Commerce/Payments_Tab.php
  src/Tickets/Emails/Admin/Settings.php
  src/Tickets/Emails/Provider.php
  src/admin-views/settings/tickets-commerce/gateways/toggle.php
  src/functions/emails/provider.php
  src/resources/postcss/tickets-admin/settings/_all.pcss
  src/resources/postcss/tickets-admin/settings/_emails.pcss
  src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss
Labels: code review

#2577 [ET-1547] Tickets Emails: Add a handler for the header image in the email preview modal.
  src/Tickets/Emails/Admin/Preview_Modal.php
  src/resources/js/admin/tickets-emails.js
Labels: code review

#2576 Deliver tickets emails with new system (if enabled).
  src/Tickets/Emails/Email/Ticket.php
  src/Tribe/Tickets.php
Labels: code review

#2578 [ET-1623] Add RSVP Email
  src/Tickets/Emails/Email/RSVP.php
  src/Tickets/Emails/Email_Handler.php
Labels: code review

#2579 [ET-1547] Tickets Emails: Preview per email
  src/Tickets/Emails/Admin/Preview_Modal.php
  src/Tickets/Emails/Email/Completed_Order.php
  src/Tickets/Emails/Email/Failed_Order.php
  src/Tickets/Emails/Email/Purchase_Receipt.php
  src/Tickets/Emails/Email/RSVP.php
  src/Tickets/Emails/Email/Ticket.php
  src/Tickets/Emails/Email_Abstract.php
  src/Tickets/Emails/Email_Template.php
  src/resources/js/admin/tickets-emails.js
Labels: code review

#2582 Deliver rsvp emails with new system
  src/Tickets/Emails/Email/Completed_Order.php
  src/Tickets/Emails/Email/Failed_Order.php
  src/Tickets/Emails/Email/Purchase_Receipt.php
  src/Tickets/Emails/Email/RSVP.php
  src/Tickets/Emails/Email/Ticket.php
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
Labels: code review

#2581 [ET-1674] Fix - Tickets/RSVP blocks crashing when hovering over their tooltips.
  readme.txt
  src/modules/elements/label-with-tooltip/__tests__/__snapshots__/element.test.js.snap
  src/modules/elements/label-with-tooltip/element.js
Labels: code review, merge

#2573 [CT-64] Display SKU on Community Tickets (TC)
  readme.txt
  src/Tickets/Commerce/Editor/Metabox.php
Labels: code review

#2588 [ET-1590] Enhancement - Add `post_title` data for created attendees using Tickets Commerce.
  readme.txt
  src/Tickets/Commerce/Attendee.php
  tests/commerce_integration/TEC/Tickets/Attendees_ListTest.php
  tests/commerce_integration/TEC/Tickets/Commerce/Stock/EventStockTest.php
Labels: code review, merge

#2584 [ETP-860] - Enhancement - Add ticket restock functionality upon attendee deletion for TicketsCommerce
  readme.txt
  src/Tickets/Commerce/Attendee.php
  src/Tickets/Commerce/Hooks.php
  src/Tickets/Commerce/Module.php
  src/Tickets/Commerce/Ticket.php
  src/Tribe/Attendees_Table.php
  tests/commerce_integration/TEC/Tickets/Commerce/Stock/UpdateTest.php
Labels: code review

#2563 [ET-1612] Fix - Undefined $going variable on Ajax request.
  readme.txt
  src/Tribe/RSVP.php
  tests/wpunit/Tribe/Tickets/__snapshots__/RSVPTest__it_should_render_rsvp_step with data set ari__1.php
Labels: code review

#2590 Tickets Emails > Abstract email data & context
  src/Tickets/Emails/Email/RSVP.php
  src/Tickets/Emails/Email/Ticket.php
  src/Tickets/Emails/Email_Abstract.php
  src/Tribe/RSVP.php
  src/Tribe/Tickets.php
Labels: code review

#2593 Tickets Emails > Use `get_placeholders` on the format string method to use filtered values
  src/Tickets/Emails/Email_Abstract.php
Labels: code review
