Repository the-events-calendar/event-tickets, pull requests merged in 2024-11, with the labels that each got.

#3367 Fix initial using seating state by considering license status
  changelog.md
  readme.txt
  src/Tickets/Seating/Editor.php
  tests/slr_integration/Editor_Test.php
  tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__expired license - new__0.snapshot.json
  tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__invalid license - new__0.snapshot.json
  tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__no license - new__0.snapshot.json
  tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__service down - new__0.snapshot.json
  tests/slr_integration/__snapshots__/Editor_Test__test_get_store_data__service not connected - new__0.snapshot.json
Labels: needs artifact

#3355 Duplicate layout functionality added
  changelog/feat-duplicate-layout
  src/Tickets/Seating/Admin/Ajax.php
  src/Tickets/Seating/Assets.php
  src/Tickets/Seating/Service/Layouts.php
  src/Tickets/Seating/app/admin/layouts/actions.js
  src/Tickets/Seating/app/admin/maps/actions.js
  src/Tickets/Seating/app/ajax/index.js
  src/Tickets/Seating/app/ajax/localized-data.js
  src/admin-views/seating/components/layouts/card.php
  tests/slr_integration/Admin/Ajax_Test.php
  tests/slr_integration/Admin/__snapshots__/Ajax_Test__test_get_localized_data__0.snapshot.json
  tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_layouts_tab_card_listing__0.snapshot.html
  tests/slr_integration/Admin/__snapshots__/Maps_Layout_Homepage_Test__test_layouts_tab_card_listing_with_1_layout__0.snapshot.html
  tests/slr_integration/__snapshots__/Assets_Test__test_get_utils_data__0.snapshot.json
  tests/slr_jest/_bootstrap.js
  tests/slr_jest/admin/layouts/__snapshots__/add-new-modal.spec.js.snap
  tests/slr_jest/admin/layouts/actions.spec.js
  tests/slr_jest/admin/maps/actions.spec.js
Labels: code review

#3379 [ET-2263] Remove Ticket Duration tooltips
  changelog/tweak-ET-2263-remove-sale-dates-tooltip
  src/Tickets/Admin/Panels_Data/Ticket_Panel_Data.php
  src/admin-views/editor/panel/fields/dates.php
  src/admin-views/editor/panel/ticket.php
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with tickets and RSVPs__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of a series with passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of series with no passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with no passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event by Occurrence provisional ID__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets and no series passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets, series has passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with tickets, RSVPs and passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with RSVP__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with ticket__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with tickets and RSVPs__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event without tickets__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_without_providers__event__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_without_providers__post__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with RSVP__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with ticket and sale price__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with ticket__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event without ticket__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket and sale price__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_with_no_providers__event__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_with_no_providers__post__0.snapshot.html
Labels: code review

#3352 Fix - Reset SLR data when new license is connection is made.
  changelog/fix-reset-slr-data-on-license-update
  src/Tickets/Seating/Uplink.php
  tests/slr_integration/Uplink_Test.php
Labels: code review

#3405 Booking Fees - Change custom table schema version
  src/Tickets/Commerce/Order_Modifiers/Custom_Tables/Order_Modifier_Relationships.php
  src/Tickets/Commerce/Order_Modifiers/Custom_Tables/Order_Modifiers.php
  src/Tickets/Commerce/Order_Modifiers/Custom_Tables/Order_Modifiers_Meta.php
Labels: code review

#3407 [ET-2082] Fix orders not updating on asynchronous/failed payments
  changelog/fix-ET-2082-order-status-not-updating-on-asynchronous-payments
  src/Tickets/Commerce/Gateways/Stripe/Webhooks/Payment_Intent_Webhook.php
  tests/commerce_integration/TEC/Gateways/Stripe/Webhooks/PaymentIntentWebhookTest.php
Labels: code review

#3422 [Booking Fees] Booking Fee Controller tests
  src/Tickets/Commerce/Order_Modifiers/Editor_Config.php
  src/Tickets/Commerce/Order_Modifiers/Modifier_Admin_Handler.php
  src/Tickets/Commerce/Order_Modifiers/Modifiers/Modifier_Abstract.php
  src/Tickets/Commerce/Order_Modifiers/Traits/Valid_Types.php
  tests/_support/Testcases/Order_Modifiers_TestCase.php
  tests/order_modifiers_integration/API/Coupons_Test.php
  tests/order_modifiers_integration/API/Fees_Test.php
  tests/order_modifiers_integration/Admin/Editor_Test.php
  tests/order_modifiers_integration/Checkout/Fees_Test.php
  tests/order_modifiers_integration/Checkout/Gateway/Paypal/Paypal_Fees_Test.php
  tests/order_modifiers_integration/Checkout/Gateway/Stripe/Stripe_Fees_Test.php
  tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $10, Fee $5, Application All__0.snapshot.html
  tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $15, Fee $2, Application Per__0.snapshot.html
  tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $20, Fee $3, Application All__0.snapshot.html
  tests/order_modifiers_integration/Checkout/__snapshots__/Fees_Test__it_should_display_fee_section__Ticket $50, Fee $10, Application Per__0.snapshot.html
  tests/order_modifiers_integration/Fees/Create_Fees_Modifiers_Test.php
  tests/order_modifiers_integration/Modifier_Admin_Handler_Test.php
Labels: hold
