Repository the-events-calendar/event-tickets, pull requests merged in 2024-02, with the labels that each got.

#2925 date change
  readme.txt
Labels: code review

#2933 Innovation: Project Link to Release workflow
  .github/workflows/link-project.yml
Labels: innovation

#2929 [ET-1833][ET-1943][ET-1951][ET-1940] Order Sales calculated incorrectly with failed payment
  readme.txt
  src/Tickets/Commerce/Status/Completed.php
  src/Tickets/Commerce/Status/Not_Completed.php
  src/Tickets/Commerce/Ticket.php
  tests/commerce_integration/TEC/Tickets/Commerce/Stock/CapacityTest.php
Labels: code review, merge

#2937 [ET-2007] Decode html entites in email subject string
  readme.txt
  src/Tickets/Emails/Dispatcher.php
Labels: code review

#2935 [GTRIA-865] fix typo
  src/Tickets/Commerce/Gateways/Contracts/Abstract_Gateway.php
Labels: code review

#2940 [ET-2009] Fix - Sync TicketsCommerce ticket stock on moving attendees.
  readme.txt
  src/Tickets/Commerce/Ticket.php
  tests/commerce_integration/TEC/Admin/MoveTicketsTest.php
Labels: code review

#2944 [ET-2047] Repository fatals when no providers enabled
  readme.txt
  src/Tribe/Repositories/Traits/Post_Tickets.php
Labels: code review
