Repository the-events-calendar/event-tickets, pull requests merged in 2024-09, with the labels that each got.

#3221 Fix state's seat type by post id
  src/Tickets/Seating/app/blockEditor/add-seating-params-to-ajax-save-ticket.js
  src/Tickets/Seating/app/blockEditor/availability-overview.js
  src/Tickets/Seating/app/blockEditor/filters.js
  src/Tickets/Seating/app/blockEditor/header-details.js
  src/Tickets/Seating/app/blockEditor/hook-callbacks.js
  src/Tickets/Seating/app/blockEditor/store/actions.js
  src/Tickets/Seating/app/blockEditor/store/index.js
  src/Tickets/Seating/app/blockEditor/ticket-is-asc.js
  src/modules/data/blocks/ticket/sagas.js
  tests/slr_jest/_bootstrap.js
  tests/slr_jest/blockEditor/add-seating-params-to-ajax-save-ticket.spec.js
  tests/slr_jest/blockEditor/availability-overview.spec.js
  tests/slr_jest/blockEditor/header-details.spec.js
  tests/slr_jest/blockEditor/hook-callbacks.spec.js
  tests/slr_jest/blockEditor/store/__snapshots__/actions.spec.js.snap
  tests/slr_jest/blockEditor/store/actions.spec.js
  tests/slr_jest/blockEditor/store/controls.spec.js
  tests/slr_jest/blockEditor/ticket-is-asc.spec.js
Labels: needs tests

#3225 [GTRIA-1236] Avoid Slow Queries
  changelog/fix-gtria-1236_avoid_slow_queries
  src/Tribe/Query.php
Labels: code review

#3226 Issues from gsheet rel to SL-97
  src/Tickets/Seating/Frontend.php
  src/Tickets/Seating/Frontend/Session.php
  src/Tickets/Seating/Frontend/Timer.php
  src/Tickets/Seating/Tables/Sessions.php
  src/Tickets/Seating/app/frontend/session/style.pcss
  src/resources/postcss/tickets-commerce/admin/orders/single.pcss
  src/views/seating/seat-selection-timer.php
  src/views/v2/tickets/item.php
  tests/_support/Tribe/Tickets/Test/Traits/With_Tickets_Commerce.php
  tests/commerce_integration/TEC/Tickets/Commerce/Shortcodes/__snapshots__/Checkout_ShortcodeTest__ticket_on_sale_should_match_html__1.php
  tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__should_correctly_render_the_email_settings_tab__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/AttendeesTest.php
  tests/ft_integration/Tribe/Tickets/__snapshots__/AttendeesTest__test_display__single event in series with Single Tickets, RSVPs and Series Passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/AttendeesTest__test_display__single event with Single Ticket attendees__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/AttendeesTest__test_display__single event with Single Tickets and RSVP Attendees__0.snapshot.html
  tests/integration/TEC/Tickets/Commerce/Admin/Orders_PageTest.php
  tests/integration/TEC/Tickets/Commerce/Admin/Singular_Order_PageTest.php
  tests/integration/TEC/Tickets/Commerce/Admin/__snapshots__/Singular_Order_PageTest__it_should_match_order_actions_as_admin__0.snapshot.html
  tests/integration/TEC/Tickets/Commerce/Admin_Tables/__snapshots__/Orders_TableTest__it_should_match_display__0.snapshot.html
  tests/slr_integration/Frontend/Session_Test.php
  tests/slr_integration/Frontend/Timer_Test.php
  tests/slr_integration/Frontend/__snapshots__/Session_Test__test_should_get_events_registrations_ticket_seat_label__0.snapshot.json
  tests/slr_integration/Frontend/__snapshots__/Timer_Test__test_render_from_cookie_data__0.snapshot.html
  tests/slr_integration/Frontend/__snapshots__/Timer_Test__test_render_to_sync__0.snapshot.html
  tests/slr_integration/Frontend/__snapshots__/Timer_Test__test_render_to_sync_with_previous_render__0.snapshot.html
  tests/slr_integration/Frontend/__snapshots__/Timer_Test__test_render_with_args__0.snapshot.html
  tests/slr_integration/Frontend_Test.php
  tests/slr_integration/Orders/Controller_Test.php
  tests/slr_integration/Orders/Seats_Report_Test.php
  tests/slr_integration/Orders/__snapshots__/Controller_Test__test_attendee_list_seat_column__single event with 3 regular Ticket attendees__0.snapshot.html
  tests/slr_integration/Orders/__snapshots__/Controller_Test__test_attendee_list_seat_column__single event with 3 seated ticket attendee__0.snapshot.html
  tests/slr_integration/Orders/__snapshots__/Controller_Test__test_attendee_list_seat_column_desc_order__single event with 3 regular Ticket attendees__0.snapshot.html
  tests/slr_integration/Orders/__snapshots__/Controller_Test__test_attendee_list_seat_column_desc_order__single event with 3 seated ticket attendee__0.snapshot.html
  tests/slr_integration/Orders/__snapshots__/Controller_Test__tests_seats_row_actions_added__0.snapshot.json
  tests/slr_integration/Orders/__snapshots__/Seats_Report_Test__test_render_page__1_ticket_1_attendee__0.snapshot.html
  tests/slr_integration/Orders/__snapshots__/Seats_Report_Test__test_render_page__2_tickets_3_attendees__0.snapshot.html
  tests/slr_integration/Orders/__snapshots__/Seats_Report_Test__test_render_page__no_tickets__0.snapshot.html
  tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__five tickets__0.snapshot.html
  tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__one ticket__0.snapshot.html
  tests/slr_integration/__snapshots__/Frontend_Test__should_replace_ticket_block_when_seating_is_enabled__two tickets__0.snapshot.html
  tests/slr_jest/admin/layouts/add-new-modal.spec.js
  tests/slr_jest/frontend/__snapshots__/ticketsBlock.spec.js.snap
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/ItemTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/ItemsTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_if_has_provider_and_provider_has_same_class_as_ticket_provider__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemTest__test_should_render_wit_whatever_data_attribute__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/Tickets/__snapshots__/ItemsTest__test_should_render_if_not_empty_tickets_on_sale__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/TicketsTest.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_regular_tickets_block__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_mini__1.php
  tests/wpunit/Tribe/Tickets/Partials/V2/__snapshots__/TicketsTest__test_should_render_ticket_block_for_is_modal__1.php
Labels: code review

#3233 Fixed bleeding state - added more tests
  src/Tickets/Seating/app/blockEditor/store/selectors.js
  tests/slr_jest/blockEditor/store/__snapshots__/selectors.spec.js.snap
  tests/slr_jest/blockEditor/store/selectors.spec.js
Labels: code review

#3218 Tickets Home > Optimize DB Queries
  src/Tickets/Admin/Tickets/List_Table.php
  src/Tickets/Admin/Tickets/Page.php
  src/Tickets/Commerce/Attendee.php
  src/Tickets/Commerce/Module.php
  src/Tickets/Commerce/Ticket.php
  src/Tribe/Tickets.php
  tests/integration/TEC/Tickets/Admin/Tickets/List_TableTest.php
  tests/integration/TEC/Tickets/Admin/Tickets/PageTest.php
  tests/integration/TEC/Tickets/Admin/Tickets/__snapshots__/List_TableTest__test_search__search existing items__0.snapshot.json
Labels: code review

#3235 Fix SLR meta keys on post/event when user switches between GAC and ASC
  src/Tickets/Seating/app/blockEditor/capacity-form/index.js
Labels: code review, needs tests

#3237 Load the Payment Element if we have Wallets
  changelog/fix-Apple_Google_Pay_display_logic
  src/Tickets/Commerce/Gateways/Stripe/Stripe_Elements.php
  src/resources/js/v2/rsvp-block.js
  src/resources/postcss/tickets-commerce/admin/orders/single.pcss
Labels: needs tests

#3247 Fix/miscalculating event availability because of ordered tickets
  .github/workflows/tests-php-ct1.yml
  .github/workflows/tests-php-ft.yml
  .github/workflows/tests-php.yml
  changelog/fix-miscalculating-event-availability-because-of-ordered-tickets
  src/Tribe/Attendees.php
  tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__should_correctly_render_the_email_settings_tab__0.snapshot.html
  tests/ft_integration/TEC/Tickets/Flexible_Tickets/Series_Passes/__snapshots__/Emails_Test__should_correctly_render_the_series_pass_settings_section__0.snapshot.html
  tests/integration/Tribe/Tickets/AttendeesTest.php
Labels: merge

#3250 [ET-2223] Fix email attendees list functionality
  changelog/fix-ET-2223-email-attendees-list-function
  src/Tribe/Attendees.php
Labels: code review

#3256 Fix/ecp 1826 duplicate events
  changelog/fix-ecp-1826-duplicate-events
  src/Tickets/Integrations/Plugins/Events_Pro/Duplicate_Post.php
  tests/ct1_integration/TEC/Tickets/Integrations/Plugins/Events_Pro/Duplicate_PostTest.php
Labels: code review

#3241 Feat/sl 177 site health
  composer.lock
  src/Tickets/Seating/Controller.php
  src/Tickets/Seating/Health.php
  tests/slr_integration/Health_Test.php
  tests/slr_integration/__snapshots__/Health_Test__it_should_check_ajax_rate_when_rate_is_enough__0.snapshot.json
  tests/slr_integration/__snapshots__/Health_Test__it_should_check_ajax_rate_when_rate_is_not_enough__0.snapshot.json
  tests/slr_integration/__snapshots__/Health_Test__it_should_check_slr_can_see_sass_when_sass_available__0.snapshot.json
  tests/slr_integration/__snapshots__/Health_Test__it_should_check_slr_can_see_sass_when_sass_unavailable__0.snapshot.json
  tests/slr_integration/__snapshots__/Health_Test__it_should_check_slr_valid_license__0.snapshot.json
  tests/slr_integration/__snapshots__/Health_Test__it_should_check_slr_valid_license_with_invalid_license__0.snapshot.json
Labels: code review

#3262 Tickets Commerce > Stripe Gateway > Webhooks: Use Payment Intent Events rather than Charge Events
  changelog/fix-ET-2225-modify-webhook-handling
  src/Tickets/Commerce/Gateways/Stripe/Webhooks/Charge_Webhook.php
  src/Tickets/Commerce/Gateways/Stripe/Webhooks/Events.php
  src/Tickets/Commerce/Gateways/Stripe/Webhooks/Payment_Intent_Webhook.php
Labels: code review

#3252 Modify the label for Tickets Capacity
  .github/workflows/tests-php-ct1.yml
  .github/workflows/tests-php-ft.yml
  .github/workflows/tests-php.yml
  changelog/fix-tickets-block-capcity-text
  src/Tickets/Blocks/Tickets/app/editor/availability/template.js
Labels: code review
