Repository the-events-calendar/event-tickets, pull requests merged in 2024-07, with the labels that each got.

#3087 styling of orders table adjustments
  src/Tickets/Commerce/Admin/Orders_Page.php
  src/Tickets/Commerce/Admin_Tables/Orders_Table.php
  src/Tickets/Commerce/Gateways/Manual/Order.php
  src/Tickets/Commerce/Hooks.php
  src/Tickets/Commerce/Order.php
  src/Tickets/Commerce/Status/Action_Required.php
  src/Tickets/Commerce/Status/Approved.php
  src/Tickets/Commerce/Status/Created.php
  src/Tickets/Commerce/Status/Not_Completed.php
  src/Tickets/Commerce/Status/Reversed.php
  src/Tickets/Commerce/Status/Unsupported.php
  src/Tickets/Commerce/Ticket.php
  src/resources/images/tribe-external-link.svg
  src/resources/js/admin/orders/table.js
  src/resources/postcss/tickets-commerce/admin/orders/table.pcss
  tests/commerce_integration/TEC/Tickets/Commerce/TicketTest.php
  tests/integration/TEC/Tickets/Commerce/Admin/Orders_PageTest.php
  tests/integration/TEC/Tickets/Commerce/Admin_Tables/Orders_TableTest.php
  tests/integration/TEC/Tickets/Commerce/Admin_Tables/__snapshots__/Orders_TableTest__it_should_match_display__0.snapshot.html
  tests/integration/TEC/Tickets/Commerce/Admin_Tables/__snapshots__/Orders_TableTest__it_should_match_search_box__0.snapshot.html
  tests/integration/TEC/Tickets/Commerce/Admin_Tables/__snapshots__/Orders_TableTest__it_should_match_single_row__0.snapshot.html
Labels: code review

#3092 Fix/event name column
  src/Tickets/Commerce/Admin_Tables/Orders_Table.php
  tests/integration/TEC/Tickets/Commerce/Admin_Tables/__snapshots__/Orders_TableTest__it_should_match_display__0.snapshot.html
  tests/integration/TEC/Tickets/Commerce/Admin_Tables/__snapshots__/Orders_TableTest__it_should_match_single_row__0.snapshot.html
Labels: merge

#3097 Fix ID column text wrap
  .puprc
  src/Tickets/Commerce/Admin_Tables/Orders_Table.php
  src/resources/postcss/rsvp-v1.pcss
  src/resources/postcss/tickets-admin/settings/_banners.pcss
  src/resources/postcss/tickets-commerce/admin/orders/table.pcss
  src/resources/postcss/tickets/_block-extras.pcss
Labels: merge

#3100 Fix the mobile styling for the orders table.
  .puprc
  src/Tickets/Commerce/Admin_Tables/Orders_Table.php
  src/resources/postcss/tickets-admin/settings/_tickets-commerce.pcss
  src/resources/postcss/tickets-commerce/admin/orders/table.pcss
  tests/integration/TEC/Tickets/Commerce/Admin_Tables/__snapshots__/Orders_TableTest__it_should_match_display__0.snapshot.html
  tests/integration/TEC/Tickets/Commerce/Admin_Tables/__snapshots__/Orders_TableTest__it_should_match_search_box__0.snapshot.html
  tests/integration/TEC/Tickets/Commerce/Admin_Tables/__snapshots__/Orders_TableTest__it_should_match_single_row__0.snapshot.html
Labels: code review

#3047 Remove VE from app shop. Fix some broken translations.
  src/admin-views/admin-welcome-message.php
  tests/_data/ft_smoketest.sql
  tests/ft_smoketest.suite.dist.yml
Labels: code review

#3116 Uplink - Add additional tests
  tests/wpunit/Tickets/Libraries/Uplink/ControllerTest.php
  tests/wpunit/Tickets/Libraries/Uplink/__snapshots__/ControllerTest__it_should_have_the_fields_for_seating_licenses_with_incorrect_permissions_snapshot__1.php
  tests/wpunit/Tickets/Libraries/Uplink/__snapshots__/ControllerTest__it_should_have_the_fields_for_seating_licenses_with_no_license_snapshot__1.php
  tests/wpunit/Tickets/Libraries/Uplink/__snapshots__/ControllerTest__it_should_have_the_fields_for_seating_licenses_with_valid_license_snapshot__1.php
Labels: code review

#3120 Fix missing provider used for price formatting
  .stylelintrc
  readme.txt
  src/Tickets/Blocks/Tickets/Block.php
  src/resources/js/v2/tickets-block.js
Labels: code review

#3125 Address fields for Stripe payment
  readme.txt
  src/Tickets/Commerce/Gateways/Stripe/Settings.php
  src/admin-views/settings/tickets-commerce/stripe/modal/signup-complete/content.php
  src/resources/js/commerce/gateway/stripe/checkout.js
  src/resources/postcss/tickets-commerce/_checkout.pcss
  src/resources/postcss/tickets-commerce/_success.pcss
  src/resources/postcss/tickets-commerce/gateway/free/_all.pcss
  src/views/v2/commerce/checkout/gateways.php
  src/views/v2/commerce/checkout/purchaser-info.php
  src/views/v2/commerce/checkout/purchaser-info/address.php
  src/views/v2/commerce/checkout/purchaser-info/city.php
  src/views/v2/commerce/checkout/purchaser-info/country.php
  src/views/v2/commerce/checkout/purchaser-info/email.php
  src/views/v2/commerce/checkout/purchaser-info/name.php
  src/views/v2/commerce/checkout/purchaser-info/state.php
  src/views/v2/commerce/checkout/purchaser-info/zip.php
  src/views/v2/commerce/gateway/stripe/payment-element.php
  tests/wpunit/Tickets/Commerce/Shortcodes/__snapshots__/Checkout_ShortcodeTest__ticket_not_on_sale_should_match_html__1.php
  tests/wpunit/Tickets/Commerce/Shortcodes/__snapshots__/Checkout_ShortcodeTest__ticket_on_sale_should_match_html__1.php
Labels: code review

#3131 Update Old ETWP Upsell Notices
  changelog/tweak-remove-etwp-upsell-notices
  src/Tickets/Admin/Upsell.php
  tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__multiple ticket from an event__0.snapshot.html
  tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__multiple ticket with multiple series pass from an event__0.snapshot.html
  tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__single ticket from an event__0.snapshot.html
  tests/ft_integration/TEC/Tickets/Commerce/Checkout/__snapshots__/CheckoutTest__test_ticketscommerce_checkout_template__ticket with series pass from an event__0.snapshot.html
Labels: question, code review

#3129 [SL-36] Feat - Deleting attendee with seat reservation should update the reservation info.
  src/Tickets/Commerce/Attendee.php
  src/Tickets/Seating/Orders/Attendee.php
  src/Tickets/Seating/Orders/Controller.php
  src/resources/js/v2/tickets-block.js
  tests/slr_integration/Orders/Controller_Test.php
Labels: code review

#3128 [SL-62] - Block editor capacity table show Assigned seating row.
  src/Tickets/Seating/Assets.php
  src/Tickets/Seating/app/blockEditor/capacity-table.js
  src/Tickets/Seating/app/blockEditor/filters.js
  src/Tickets/Seating/app/blockEditor/store/index.js
  src/Tickets/Seating/app/blockEditor/store/selectors.js
  tests/slr_integration/__snapshots__/Assets_Test__test_get_utils_data__0.snapshot.json
  tests/slr_jest/_bootstrap.js
  tests/slr_jest/blockEditor/__snapshots__/capacity-table.spec.js.snap
  tests/slr_jest/blockEditor/capacity-table.spec.js
Labels: code review

#3137 Address fields for stripe payment
  src/resources/js/commerce/gateway/stripe/checkout.js
Labels: code review
