Repository the-events-calendar/event-tickets, pull requests merged in 2025-01, with the labels that each got.

#3466 Moved filter to closure to avoid loading issues
  changelog/fix-resolve-resend-fatal
  src/Tribe/Assets.php
Labels: merge

#3474 Fix/duplicated orders and attendees
  changelog/fix-duplicated-orders-and-attendees
  changelog/fix-duplicated-orders-and-attendees-2
  src/Tickets/Commerce/Abstract_Order.php
  src/Tickets/Commerce/Attendee.php
  src/Tickets/Commerce/Cart/Unmanaged_Cart.php
  src/Tickets/Commerce/Flag_Actions/Generate_Attendees.php
  src/Tickets/Commerce/Order.php
  tests/commerce_integration/TEC/Tickets/Commerce/Order_Test.php
Labels: code review

#3476 [ET-2269] Tickets Commerce: Add filter for cart hash cookie name
  changelog/tweak-ET-2269-enable-way-to-customize-cart-cookie-name
  src/Tickets/Commerce/Cart.php
  tests/commerce_integration/TEC/Tickets/Commerce/CartTest.php
Labels: code review

#3477 Introduce Lock Order Mechanism
  changelog/feat-introduce-lock-order-mechanism
  src/Tickets/Commerce/Gateways/Stripe/Hooks.php
  src/Tickets/Commerce/Gateways/Stripe/REST/Order_Endpoint.php
  src/Tickets/Commerce/Gateways/Stripe/REST/Webhook_Endpoint.php
  src/Tickets/Commerce/Gateways/Stripe/Webhooks.php
  src/Tickets/Commerce/Gateways/Stripe/Webhooks/Handler.php
  src/Tickets/Commerce/Order.php
  src/Tickets/Commerce/Provider.php
  tests/_bootstrap.php
  tests/commerce_integration/TEC/Tickets/Commerce/Gateways/Stripe/Hooks_Test.php
  tests/commerce_integration/TEC/Tickets/Commerce/Order_Test.php
  tests/commerce_integration/TEC/Tickets/Commerce/Provider_Test.php
Labels: needs artifact

#3480 Specify status any on upsert query
  src/Tickets/Commerce/Order.php
Labels: code review

#3482 Convert static calls of truncate to dynamic
  src/Tickets/Seating/Service/Layouts.php
  src/Tickets/Seating/Service/Maps.php
  src/Tickets/Seating/Service/Seat_Types.php
  tests/slr_integration/Admin/Ajax_Test.php
  tests/slr_integration/Admin/Maps_Layout_Homepage_Test.php
  tests/slr_integration/Orders/Cart_Test.php
  tests/slr_integration/Service/Seat_Types_Test.php
Labels: code review

#3483 Register ticket blocks assets through stellarwp/assets
  .prettierrc.js
  package-lock.json
  package.json
  src/Tickets/Blocks/Controller.php
  src/Tickets/Blocks/Tickets/Block.php
  src/Tickets/Blocks/Tickets/app/editor/controls/template.js
  tests/integration/TEC/Tickets/Blocks/Tickets/BlockTest.php
Labels: code review

#3485 Enriches ticket management hooks
  changelog/feat-enrich-ticket-management-hooks
  src/modules/data/blocks/ticket/sagas.js
Labels: code review

#3488 Feat/more rsvp hooks
  changelog/feat-more-rsvp-hooks
  src/Tickets/Blocks/Tickets/app/editor/controls/template.js
  src/modules/blocks/rsvp/template.js
  src/modules/data/blocks/rsvp/thunks.js
Labels: code review

#3489 Include status check as part of the transaction
  changelog/fix-include-status-check-as-part-of-the-transaction
  changelog/fix-include-status-check-as-part-of-the-transaction-2
  src/Tickets/Commerce/Order.php
  src/Tickets/Commerce/Status/Refunded.php
  src/Tickets/Commerce/Status/Status_Abstract.php
  src/Tickets/Commerce/Status/Trashed.php
  tests/_bootstrap.php
  tests/commerce_integration/TEC/Tickets/Commerce/Order_Test.php
  tests/commerce_integration/TEC/Tickets/Commerce/Status/Status_Test.php
  tests/commerce_integration/_bootstrap.php
  tests/ct1_integration/_bootstrap.php
  tests/ft_integration/Tribe/Tickets/__snapshots__/OrderReportTest__test_tc_order_report_display__event with a series pass and single ticket orders__0.snapshot.html
  tests/ft_integration/_bootstrap.php
  tests/integration/_bootstrap.php
  tests/slr_integration/_bootstrap.php
Labels: code review

#3497 [ET-2287] Rework hidden Ticket Provider field in Classic Editor
  changelog/task-ET-2287-rework-hidden-ticket-provider-setting
  src/Tribe/Tickets.php
  src/admin-views/commerce/metabox/capacity.php
  src/admin-views/editor/fieldset/advanced.php
  src/admin-views/editor/fieldset/price.php
  src/admin-views/editor/panel/fields/name.php
  src/admin-views/editor/panel/ticket.php
  src/admin-views/rsvp-metabox-capacity.php
  src/admin-views/rsvp-metabox-not-going.php
  src/admin-views/tpp-metabox-capacity.php
  src/admin-views/tpp-metabox-sku.php
  src/resources/js/tickets.js
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with tickets and RSVPs__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of a series with passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__recurring event part of series with no passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with no passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__series with passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event by Occurrence provisional ID__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets and no series passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with no tickets, series has passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event part of a series with tickets, RSVPs and passes__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with RSVP__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with ticket__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event with tickets and RSVPs__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__single event without tickets__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_without_providers__event__0.snapshot.html
  tests/ft_integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_without_providers__post__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with RSVP__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with ticket and sale price__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event with ticket__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__event without ticket__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with RSVP__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket and sale price__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post with ticket__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels__post without ticket__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_with_no_providers__event__0.snapshot.html
  tests/integration/Tribe/Tickets/__snapshots__/MetaboxTest__test_get_panels_with_no_providers__post__0.snapshot.html
  tests/order_modifiers_integration/Admin/__snapshots__/Order_Modifier_Fee_Metabox_Test__it_should_add_fee_section__0.snapshot.html
  tests/order_modifiers_integration/Admin/__snapshots__/Order_Modifier_Fee_Metabox_Test__it_should_add_fee_section_for_fresh_ticket__0.snapshot.html
  tests/order_modifiers_integration/Admin/__snapshots__/Order_Modifier_Fee_Metabox_Test__it_should_add_fee_section_for_series__0.snapshot.html
  tests/order_modifiers_integration/Admin/__snapshots__/Order_Modifier_Fee_Metabox_Test__it_should_not_add_fee_section_for_anything_other_than_ticket__0.snapshot.html
Labels: code review

#3506 Show expected sale/regular price on blocks with woo
  changelog/fix-ET-2100-diff-sale-price-for-woo-with-blocks
  src/Tickets/Blocks/Ticket/app/editor/container-content/sale-price/container.js
  src/Tickets/Blocks/Ticket/app/editor/container-content/sale-price/template.js
  src/Tribe/Editor/Configuration.php
  src/Tribe/REST/V1/Post_Repository.php
  src/modules/data/blocks/ticket/selectors.js
  tests/integration/Tribe/Tickets/REST/V1/Post_RepositoryTest.php
Labels: code review

#3487 [ET-2284] Fixing Translation Issues in ET: Part One
  src/Tickets/Commerce/Gateways/PayPal/Provider.php
  src/Tickets/Commerce/Order_Modifiers/Admin/Order_Modifier_Fee_Metabox.php
  src/Tickets/Commerce/Order_Modifiers/Checkout/Abstract_Fees.php
  src/Tickets/Seating/Health.php
  src/Tickets/Seating/Uplink.php
  src/Tribe/Commerce/Currency.php
  src/Tribe/Commerce/PayPal/Main.php
  src/Tribe/Main.php
  src/Tribe/REST/V1/Messages.php
  src/Tribe/RSVP.php
  src/Tribe/Tickets_Handler.php
  tests/slr_integration/Health_Test.php
Labels: code review

#3424 React 18 compatibility
  .github/workflows/lint.yml.bak
  .github/workflows/tests-js.yml.bak
  .nvmrc
  changelog/fix-TEC-5322-wp-67-packages
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  src/Tickets/Blocks/Ticket/Block.php
  src/Tickets/Blocks/Ticket/app/editor/container-content/advanced-options/ecommerce-options/template.js
  src/Tickets/Blocks/Ticket/app/editor/container-content/advanced-options/sku/template.js
  src/Tickets/Blocks/Ticket/app/editor/container-content/attendees-registration/template.js
  src/Tickets/Blocks/Ticket/app/editor/container-content/capacity/template.js
  src/Tickets/Blocks/Ticket/app/editor/container-content/description/template.js
  src/Tickets/Blocks/Ticket/app/editor/container-content/price/template.js
  src/Tickets/Blocks/Ticket/app/editor/container-content/sale-price/template.js
  src/Tickets/Blocks/Ticket/app/editor/container-content/template.js
  src/Tickets/Blocks/Ticket/app/editor/container-header/quantity/quantity-bar/bar.js
  src/Tickets/Blocks/Ticket/app/editor/container-header/quantity/quantity-bar/element.js
  src/Tickets/Blocks/Ticket/app/editor/container-header/quantity/template.js
  src/Tickets/Blocks/Ticket/app/editor/container-header/title/attendee-registration-icons/container.js
  src/Tickets/Blocks/Ticket/app/editor/container-header/title/attendee-registration-icons/template.js
  src/Tickets/Blocks/Ticket/app/editor/container.js
  src/Tickets/Blocks/Ticket/app/editor/dashboard/container.js
  src/Tickets/Blocks/Ticket/app/editor/hooks.js
  src/Tickets/Blocks/Tickets/app/editor/action-dashboard/container.js
  src/Tickets/Blocks/Tickets/app/editor/capacity-table/row/template.js
  src/Tickets/Seating/app/blockEditor/capacity-form/index.js
  src/Tickets/Seating/app/blockEditor/capacity-form/service-error.js
  src/modules/blocks/attendees/template.js
  src/modules/blocks/rsvp/action-buttons/settings-action-button/template.js
  src/modules/blocks/rsvp/action-dashboard/container.js
  src/modules/blocks/rsvp/move-delete/container.js
  src/modules/data/blocks/rsvp/__tests__/sagas.test.js
  src/modules/data/blocks/rsvp/sagas.js
  src/modules/data/blocks/ticket/__tests__/sagas.test.js
  src/modules/data/blocks/ticket/sagas.js
  src/modules/elements/action-button/__tests__/element.test.js
  src/modules/elements/action-button/element.js
  src/modules/elements/action-dashboard/element.js
  src/modules/elements/date-time-range-picker/element.js
  src/modules/elements/icon-with-tooltip/element.js
  src/modules/elements/label-with-tooltip/element.js
  src/modules/elements/numeric-label/element.js
  src/modules/elements/settings-dashboard/element.js
  tests/ft_integration/Tribe/Tickets/OrderReportTest.php
Labels: code review

#3517 [ET-2287] JavaScript fix to force RSVP provider being set
  src/resources/js/tickets.js
Labels: code review

#3515 Adding get_columns method to all custom tables
  package.json
  src/Tickets/Commerce/Order_Modifiers/Custom_Tables/Order_Modifier_Relationships.php
  src/Tickets/Commerce/Order_Modifiers/Custom_Tables/Order_Modifiers.php
  src/Tickets/Commerce/Order_Modifiers/Custom_Tables/Order_Modifiers_Meta.php
  src/Tickets/Seating/Tables/Layouts.php
  src/Tickets/Seating/Tables/Maps.php
  src/Tickets/Seating/Tables/Seat_Types.php
  src/Tickets/Seating/Tables/Sessions.php
Labels: code review

#3521 Move events ajax response to be outside of tickets commerce
  changelog/tweak-move-ajax-response-for-events-out-of-ticketscommerce
  src/Tickets/Commerce/Admin_Tables/Orders_Table.php
  src/Tickets/Commerce/Hooks.php
  src/Tickets/Hooks.php
  tests/ft_integration/Tribe/Tickets/OrderReportTest.php
  tests/integration/TEC/Tickets/Commerce/Admin_Tables/Orders_TableTest.php
  tests/integration/TEC/Tickets/Commerce/Admin_Tables/__snapshots__/Orders_TableTest__it_should_match_display__0.snapshot.html
  tests/integration/Tribe/Admin/OrderReportTest.php
Labels: code review
